### ISSUE TITLE
Starting v4.0.0-rc2 from Snapshot Crashes Nodeos

### ISSUE THREAD

**Issue by jbuice** [AntelopeIO/leap#1007]
Assumption: Nodeos v4.0.0-rc2 already running and caught up to head then nodeos closes dirty due to my own fault.

Historically, I can take a snapshot from the previous day, delete `/blocks/reversible` and the entire `/state` directory, then start from the snapshot to repair. 

Performing this process with Nodeos v4.0.0-rc2 crashes.

When I revert to 3.2.3, this method is successful. 

Snapshot file: https://snapshots.testnet.telosunlimited.io/telos-testnet-20230405-blknum-227988312.tar.gz
The snapshot was taken with nodeos version 3.1.1

**Comment by matthewdarwin** [comment]
Close this issue?

**Comment by heifner** [comment]
> Close this issue?

Waiting for verification from @jbuice. He is going to test it.

**Comment by jbuice** [comment]
Sorry for the delay. We're good here.

**Comment by heifner** [comment]
Cat: History
