### ISSUE TITLE
Allow settings permissions on unix-socket

### ISSUE THREAD

**Issue by aaroncox** [AntelopeIO/leap#1018]
The current way unix sockets are created requires the permissions to manually be altered each time nodeos starts, before some upstream consumers of the socket are able to access it. After nodeos start, we need to run:

```bash
chmod 777 /path/to/nodeos.sock
```

It would be ideal if we could define what permissions that file is created within the config.ini, either on the same line as the `unix-socket-path`, like so:

```ini
unix-socket-path = /path/to/nodeos.sock:777
```

Alternatively if the above doesn't work, this could also be done via a separate configuration value:

```ini
unix-socket-path = /path/to/nodeos.sock
unix-socket-perm = 777
```

**Comment by heifner** [comment]
I put more-info because if I follow @spoonincode comment this looks like it is a non-issue. I was hoping that @aaroncox would comment.

**Comment by bhazzard** [comment]
We've created a documentation ticket to make this clearer. Not currently slated as a high priority.

**Comment by aaroncox** [comment]
I understand this isn't a high priority - but FWIW, using a unix-socket is the "best practice" in terms of operating an API. Anything we can do to make them work out of the box more effectively will be a net win.
