### ISSUE TITLE
Hot-Reload of specific configuration-parameters

### ISSUE THREAD

**Issue by cmadh** [AntelopeIO/leap#103]
While Node-Operators on WAX recently saw issues in block-production many had to restart nodeos-processes frequently to update specific configuration-parameters like subjective-billing, cpu-efforts, greylists/blacklists/whitelists etc. 

A common approach is to 
1.) Change the configuration (config.ini)
2.) Kill the nodeos-process after successfully producing a round 
3.) Restart immediately to have nodeos running and catched up again when the next round needs to be produced on this producer-node

This approach seems to be unnecessarily complex and error-prone, a possible improvement could be the implementation of a hot-reload on config-change for parameters that can be changed at runtime as an alternative to additional RPC-API-functionallity which always comes with drawbacks like accidentially exposing endpoints to the public.

**Comment by cmadh** [comment]
"specific configuration-parameters" because I assume that not all of them can technically be hot-reloaded within the process and there are some limitations.

**Comment by stephenpdeos** [comment]
@cmadh can you give us a prioritized list of options you'd like configurable and the use case for them? Thanks!

**Comment by stephenpdeos** [comment]
@cmadh just bumping you here, thanks!

**Comment by stephenpdeos** [comment]
@cmadh bumping again, thanks!

**Comment by bhazzard** [comment]
Closing this issue for lack of actionable information.
