### ISSUE TITLE
Produce signed binaries for leap builds

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1032]
Depends on #1717 

```[tasklist]
### Tasks
- [ ] Document approach
- [ ] Coordinate manual signing of the build
```

**Comment by bhazzard** [comment]
move to 5.0.0 (stable) milestone

**Comment by spoonincode** [comment]
Since we successfully signed 5.0.0-rc3, going to consider this closed. There are some follow up items (such as documentation & automation) that may need to be specified, but the manual procedure seems operational now.
