### ISSUE TITLE
Design a solution: enhance nodeos HTTP for better proxy integration

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1034]
To address potential abuse of Nodeos public APIs, we recommend enhancements to the API structure:

- Better support for proxies: Add headers for transaction failure trace, including account name and reason for failure, for more effective load balancing and IP-based throttling.
- Better status codes:
  - Move away from 500 errors: Avoid false positives and enable better traffic management.
  - Semantic status codes: provide information to enable proxies to manage traffic; introduce more specific status codes.

These enhancements will significantly improve support for proxy solutions and prevent potential API abuse. We encourage the Nodeos community to collaborate on their implementation.

**Comment by bhazzard** [comment]
Move to Product Repo.

Get more specific about:
- what headers to add
- format of headers
- what status codes for what scenarios

**Comment by stephenpdeos** [comment]
Related impacted grant https://github.com/eosnetworkfoundation/grant-framework/pull/115
