### ISSUE TITLE
Spike: Decoupled instrumentation feasibility

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1047]
Research what it would take to support instrumentation like DeepMind without it being directly integrated in the leap codebase.

Report findings back to: https://github.com/eosnetworkfoundation/product/issues/151

**Comment by wanderingbort** [comment]
## Goal:

The primary output of this spike should be either:
1. a process flow diagram of Block/Transaction/Action processing that includes explicit "hook" points sufficient to supply the current Deep mind implementation all of its required information. OR
2. a ratrional argument that such a process would be as or more invasive than the existing code base.

## Additional Thoughts:

There are some existing natural lifecycle hooks that are not currently explicit in the code base but may be usefully made explicit.  Such as:

- begin/end block
- begin/end transaction
- begin/end action
- verify/reject authorization

As well as some concepts that could be abstracted. Such as:
- write to "chain state"
- read from "chain state"
- write to console

There is a hope that with minor restructure of the core execution loop we can reduce the total number of "hooks" necessary to implement deep instrumentation. 

This research spike can suggest such restructuring and is not limited to the existing code paths.

This is part of a larger initiative to investigate extracting libraries which could process transactions and/or blocks in service of both leap and another executable.  This may include abstracting chain state storage and dependencies which will expose potential "hooks" etc.

**Comment by heifner** [comment]
https://hackmd.io/VFnEL3wiRX-9FIwXYqMLfg

**Comment by heifner** [comment]
https://github.com/eosnetworkfoundation/product/pull/156
