### ISSUE TITLE
deep mind logging of onblock

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1067]
Currently `onblock` `TRX_OP CREATE onblock ${id} ${trx}` is logged for `onblock` transactions that could fail as it is logged at the creation of the `onblock` and doesn't verify the `onblock` does not fail before reporting it.

**Comment by heifner** [comment]
@systemzax @maoueh @matthewdarwin can anyone verify that `onblock` should only be logged if it actually executes?

**Comment by matthewdarwin** [comment]
I don't know the answer to this off-hand, but can you check how it works in nodeos 2.1 and see if it got broken when the code was re-implemented in 3.0?

**Comment by heifner** [comment]
> I don't know the answer to this off-hand, but can you check how it works in nodeos 2.1 and see if it got broken when the code was re-implemented in 3.0?

It is in the same location in 2.1. But I would argue it was a bug there as well. I see no reason to log an `onblock` that failed to execute. A user might conclude that an `onblock` executed when it actually failed.

**Comment by matthewdarwin** [comment]
Ok we need @maoueh to comment.  He's out for a few days, so we should get input when he is back.

**Comment by stephenpdeos** [comment]
@maoueh any chance you are back to provide input?

**Comment by greg7mdp** [comment]
I have made the change to move this at the end of block creation, but I am not sure it is better?
![image](https://github.com/AntelopeIO/leap/assets/1496907/394f7d34-396b-4ab8-a7ef-43ce0ce1b950)

**Comment by heifner** [comment]
I think it should be logged at time of successful execution. Not at creation and not at end of block. Although, I would question the need to log it separate from the already logged `APPLIED_TRANSACTION`. If a separate log entry is expected then it should be right before or right after the `APPLIED_TRANSACTION`. In this case that would be something like:

```
DMLOG TRX_OP CREATE onblock da9fbe9042e1bc9bd64d7a4506534d492107a29f79ad671c1fea19ae3fb70eb4 01e10b5e02005132b41600000000010000000000ea305500000000221acfa4010000000000ea305500000000a8ed32329801013b3d4b0000000000ea30550000000000015ab65a885a31e441ac485ebd2aeba87bf7ee6e7bcc40bf3a24506ba1000000000000000000000000000000000000000000000000000000000000000062267e8b11d7d8f28e1f991a4de2b08cf92500861af2795765bdc9263cd6f4cd000000000001000021010ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd000000
DMLOG APPLIED_TRANSACTION 3 da9fbe9042e1bc9bd64d7a4506534d492107a29f79ad671c1fea19ae3fb70eb403000000023b3d4b01000000034b2b890c59dad3c04fd9300057ba6285196dc55f32e988a49d6059cd01006400000000000000000000000000000000000000000001010000010000000000ea3055ccfe3b56076237b0b6da2f580652ee1420231b96d3d96b28183769ac932c9e5902000000000000000200000000000000010000000000ea3055020000000000000000000000000000ea30550000000000ea305500000000221acfa4010000000000ea305500000000a8ed32329801013b3d4b0000000000ea30550000000000015ab65a885a31e441ac485ebd2aeba87bf7ee6e7bcc40bf3a24506ba1000000000000000000000000000000000000000000000000000000000000000062267e8b11d7d8f28e1f991a4de2b08cf92500861af2795765bdc9263cd6f4cd000000000001000021010ec7e080177b2c02b278d5088611686b49d739925a92d9bfcacd7fc6b74053bd00000000000000000000da9fbe9042e1bc9bd64d7a4506534d492107a29f79ad671c1fea19ae3fb70eb403000000023b3d4b01000000034b2b890c59dad3c04fd9300057ba6285196dc55f32e988a49d6059cd0000000000000000
```

**Comment by greg7mdp** [comment]
Sounds good, thanks Kevin, I'll move it right before `APPLIED_TRANSACTION` as you suggest, although I guess the original issue still would exist (that it is reported when the onblock can still fail)?

**Comment by maoueh** [comment]
`onblock` is a faillible operation right, so l don't see it as a problem directly having it logged when it has failed. It's not a problem on the opposite side neither to have it skipped, I think it just a matter of what make the most sense.

I recall back in the time a long series of block where the `onblock` was actually failing, it was reported in the eosq explorer as a failed transaction, which helped debugging.

**Comment by greg7mdp** [comment]
Better like this?
![image](https://github.com/AntelopeIO/leap/assets/1496907/52c4c97f-b0c7-4fc5-af12-56d31eefbdcd)
