### ISSUE TITLE
Change the default leap C++ compilation flag to `-std=c++20`

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#1079]
#### Prerequisites:

- [x] #1084
- [x] #922
- [ ] #1121 via (#1116 OR #1192)
- [ ] #1142
- [ ] Start new version of nodeos (compiled with C++20) from old version (generated by nodeos compiled with C++17) state, check integrity hash, ensure it can still sync a few blocks afterward. (Run this test with pinned clang-11 and also gcc-10, or whatever minimum versions we decide in #1084.)

#### llvm issue background

This is a known build issue with the LLVM headers (gcc-12, -std=c++20), see [this](https://stackoverflow.com/questions/67698523/error-in-llvm-stlextras-expected-unqualified-id-before-const-with-gcc11).

Manually changing /usr/include/llvm-11/llvm/ADT/STLExtras.h to remove the unneeded `<R>` allows it to build fine.

Issue is fixed in [LLVM-13](https://github.com/llvm/llvm-project/blob/release/13.x/llvm/include/llvm/ADT/STLExtras.h#L1867)

#### Possible way forward

Investigate what part of leap depends on those llvm headers, and possibly keep building these with `-std=c++17`.

**Comment by arhag** [comment]
We also want to run a replay (even before chicken test is ready) soon after making the C++20 switch.

**Comment by greg7mdp** [comment]
> Investigate what part of leap depends on those llvm headers, and possibly keep building these with `-std=c++17`.

I tried this, setting `set_property(TARGET eosio_chain PROPERTY CXX_STANDARD 17)` in `libraries/chain/CMakeLists.txt`.
While this does fix the compilation issue for the cpp files, it creates new link issues such as:

```
usr/bin/ld: libraries/chain/libeosio_chain.a(crypto.cpp.o): in function `eosio::chain::webassembly::interface::alt_bn128_mul(eosio::vm::span<char const, 18446744073709551615ul>, eosio::vm::span<char const, 18446744073709551615ul>, eosio::vm::span<char, 18446744073709551615ul>) const':
/home/greg/github/enf/leap/libraries/chain/webassembly/crypto.cpp:130: undefined reference to `bn256::g1_scalar_mul(nonstd::span_lite::span<unsigned char const, 64ul>, nonstd::span_lite::span<unsigned char const, 32ul>, nonstd::span_lite::span<unsigned char, 64ul>)'
/usr/bin/ld: libraries/chain/libeosio_chain.a(crypto.cpp.o): in function `eosio::chain::webassembly::interface::alt_bn128_pair(eosio::vm::span<char const, 18446744073709551615ul>) const':
/home/greg/github/enf/leap/libraries/chain/webassembly/crypto.cpp:139: undefined reference to `bn256::pairing_check(nonstd::span_lite::span<unsigned char const, 18446744073709551615ul>, std::function<void ()>)'
collect2: error: ld returned 1 exit status

```

**Comment by bhazzard** [comment]
Blocked awaiting completion of Prerequisites (in description)
