### ISSUE TITLE
Proposal for Leap build requirements to support C++20

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1084]
Determine minimum versions of supported compilers and standard lib.

Currently for 4.0, minimum versions we support are:
gcc: 8
clang: not officially stated

Currently for main, minimum versions:
gcc: 9
clang: 9

We want to clarify what are the minimum versions we wish to support for 5.0 so that we get a desirable subset of C++20 features:

gcc: TBD (maybe 10?)
clang: TBD

GNU stdlibc++: TBD
LLVM libc++: TBD

(Not sure how well different standard libs play with different compilers.)

Consider CMake checks to fail early for unsupported combinations?

Subject to supported platform constraints:
Ubuntu 18 no longer supported.
Ubuntu 20 provides up to gcc 10.

**Comment by arhag** [comment]
Perhaps we want to avoid a minimum version for clang and just specify the pinned version which we have a good reason to be the latest stable one available.

**Comment by greg7mdp** [comment]
I tested on ubuntu 22.04 with the flag `--std=c++20`:

- `clang-16` builds and tests pass
- `gcc-10` builds and tests pass
- `gcc-12` - requires manual modification of llvm-11 headers to build. Some tests fail (partitioned_block_log_unit_test_eos-vm*)

**Comment by greg7mdp** [comment]
@arhag I have a fix for the g++-10 issue. I moved the definition of `WASM::check_limits` to `wasm-jit/Source/Logging` which is at the bottom or the WASM libraies dependency graph. It now builds fine with g++-10 and all tests pass. I'll submit a PR for that fix.

**Comment by greg7mdp** [comment]
By default, on ubuntu at least, both clang++ and g++ use the platform (GNU) C++ standard lbrary (`libstdc++`) .

I tried building with the clang++-16 and **clang C++ standard library (using `-stdlib=libc++`)**. There were lots of issues in boost (I was using boost 1.74). So I upgraded to boost 1.82.  This addressed the boost issues, but there were issues in our code. I fixed (and merged) the first error (`std::result_of` removed), but there were further problems which seemed non trivial to fix.

Now that I had built boost 1.82, I tried that version using our normal build process with the **(GNU) C++ standard library** (`libstdc++`).
There were no issues building and running `parallelizable tests` and `./unittests/unit_test`.
 - [x] clang++-16, `libstdc++`, boost 1.82, release build
 - [x] g++-10, `libstdc++`, boost 1.82, release build
