### ISSUE TITLE
Confusing read-only-read-window-time-us error message

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1088]
With the following config:
```
 max-transaction-time = 10000
 read-only-write-window-time-us = 200000
 read-only-read-window-time-us = 60000
 read-only-threads = 0
```
and when run node on v 4.0.0 - error is
```
plugin_config_exception: Incorrect plugin configuration
--read-only-read-window-time-us (60000) must be greater than --max-transaction-time 10000 ms plus a margin of 10000 us
    {"read":60000,"trx_time":10000,"min":10000}
```

Seems the error would be clearer if the values were all reported in microseconds. As multiple people have reported they don't understand the error. I think people miss the `ms` vs `us`. 

Maybe show the math in the error message. Something like:  
```
--read-only-read-window-time-us (60000 us) must be greater than --max-transaction-time (10000 ms) plus a margin of (10000 us), required: 60000 us < (10000000 us + 10000 us).
    {"read":60000,"trx_time":10000,"min":10000}
```

Also is it better experience to always enforce this or only when `read-only-threads > 0` ?

**Comment by linh2931** [comment]
Another thing. I thought we only validated/initialized read-only trx configuration options when read-only was enabled (even having a comment `// only initialize other read-only options when read-only thread pool is          enabled`). But we missed that. This should be fixed at the same time.
