### ISSUE TITLE
add ARM builds to CI

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#1100]
Even though we don't officially support ARM builds (mostly due to their poor performance), DUNE does use an ARM build of Leap which places ARM builds in a semi-supported state (we _do_ support DUNE on ARM, after all).

Given this semi-supported state of ARM builds the lack of CI is concerning because,
* we don't regularly test that these ARM builds work properly (it's not clear the last time anyone ran the full test suite on ARM)
* we don't have visbility in to ARM build failures until someone gets around to it manually -- potentially months after the defect has been introduced
* the ARM builds we distribute for DUNE are built entirely manually and depend on a Leap team member with a Linux ARM build environment being at the ready for each release

If we're going to even semi-support ARM builds, they need to be added to CI runs. The old [build tenets proposal](https://github.com/eosnetworkfoundation/product/blob/main/build-system/proposals/initial_tenets.md#cross-build-non-linux-non-x86-binaries) suggests that non-x86_64 builds be performed via cross-compilation mainly for two reasons:
* performance; so that CI run time is not impacted by only having a 48-core ARM build machine vs 100+ core x86_64 build machine
* an ARM machine is not required to reproduce the build in a timely manner (this will become more important when ARM is fully supported, which hopefully it will be.. one day)

I'd suggest we try that cross compilation if at all possible, but if it turns out we can compile ARM builds reasonably fast on the largest ARM box available to us in CI (48 cores), it's possible we can build natively on ARM to start with.

**Comment by bhazzard** [comment]
Breakdown into smaller issues:
- Manually verify that test pass for LEAP builds targeting ARM
- Get/Create ARM Runners (Dependent on Pinned Builds)
- Adding CI Step to Build LEAP on ARM
- Add CI Steps to Test LEAP on ARM
- Add CI Steps to Package LEAP on ARM

**Comment by spoonincode** [comment]
ARM support has been deprioritized, so closing this out. Can revisit in future.
