### ISSUE TITLE
test libtester usage as part of CI

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#1104]
Leap's libtester is used for native contract unit testing of contracts. For example, https://github.com/AntelopeIO/reference-contracts uses libtester for testing eosio.system and eosio.token.

libtester has long been a very persnickety library that inadvertently breaks causing failures downstream when contract unit tests attempt to use it. Breakage typically takes the form of something being wrong in the cmake files (very manually crafted, sometimes unknown to contributors, and easy to miss), or part of the libtester interface unexpectedly changing (some changes are inevitable, and why the contract build files have a version limiter, but sometimes it's simply not obvious a change breaks the interface for code in a separate repo).

To complicate matters further, libtester can potentially be installed four different ways,
1. Used in-place of part of leap's build tree
2. Used after a `make dev-install` which installs the files to `CMAKE_INSTALL_PREFIX`
3. Used after a `DESTDIR= make dev-install` which installs the files to `DESTDIR/CMAKE_INSTALL_PREFIX`
4. Used from a `leap-dev.deb` install, which ought be similar to 2

We do have some test coverage around 4 _in a different repo_ since the CI of reference-contracts installs `leap-dev.deb` and uses it for testing. This other repo's CI has been an indirect way of getting a libtester sniff test for a leap branch in question. It's also worth mentioning that DUNE uses `leap-dev.deb` so that's another data point of it working (and another reason to make sure it keeps working!).

So as of this moment, 4 works. 1 probably works, as at least a few ENF developers are known to use that method. 2 likely works since it's similar to 4. 3 probably has never worked due to how the cmake is structured.

We really need to do a sanity check of libtester for leap CI runs. A sanity check might be to build reference-contracts via a libtester installed via methods 1, 2, and 4, for example.

**Comment by 766C6164** [comment]
Something related to be aware of - there is an effort to add C++ 20 support that requires newer boost (1.82) that is currently brought as submodule. To make it work, dependencies on boost labs in makefiles are specified explicitly. If there is a missing dependency, there is a risk that a header from systemwide installed Boost with different version would be used leading to hard to catch issues: https://github.com/AntelopeIO/leap/pull/1142
Good way to detect missing deps is to NOT have libboost-all-dev installed in a docker image as it is suggested in comments in this PR
