### ISSUE TITLE
C++20 support - add boost 1.82 submodule and use it in leap build

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#1122]
As building in C++20 mode requires a version of boost > 1.71 (the default on ubuntu 20), we need a greater boost version for building leap when c++20 is enabled.

It seems that the best solution might be to add boost 1.82 as a submodule.

**Comment by greg7mdp** [comment]
It looks like it will not be easy to use boost as a submodule in leap. Adding the submodule is easy, but we have other submodules which use `find_package()` and do not find boost when added as a submodule.

I entered an [issue](https://github.com/boostorg/cmake/issues/38#issuecomment-1535103357) and the answer seems to confirm that it would not be easy (unless we do change the `find_package` references in the submodules using boost, which is not something I think we want to do.

**Comment by ScottBailey** [comment]
`fetchcontent` remains an option. 

Though if used, we might want it to be cache driven. Maybe something like this:

```cmake
option(FC_BOOST_SYSTEM "Use system provided boost libraries." Off)
option(FC_BOOST_DEFAULT "Use default fetch content for boost libraries." Off)


set(BOOST_INCLUDE_LIBRARIES system thread filesystem)  # Add additional libraries here, e.g. url                                                                                                       
set(BOOST_ENABLE_CMAKE ON)

if(FC_BOOST_SYSTEM)
   if(FC_BOOST_DEFAULT)
      message(FATAL_ERROR "Can't have both FC_BOOST_SYSTEM and FC_BOOST_DEFAULT True at the same time.")
   endif()
   message(STATUS "Using system provided boost libraries.")
else()

   set(FETCHCONTENT_QUIET Off)
   include(FetchContent)
   include(ExternalProject)

   if(FC_BOOST_DEFAULT)
      set(FC_BOOST_URL  https://github.com/boostorg/boost/releases/download/boost-1.82.0/boost-1.82.0.tar.xz)
      set(FC_BOOST_HASH andfd60da30be908eff945735ac7d4d9addc7f7725b1ff6fcdcaede5262d511d21e)
   endif()
   if(NOT FC_BOOST_URL OR NOT FC_BOOST_HASH)
      message(FATAL_ERROR "Either set FC_BOOST_DEFAULT or set FC_BOOST_URL and FC_BOOST_HASH.")
   endif()

   FetchContent_Declare(
      Boost
      SYSTEM
      URL https://github.com/boostorg/boost/releases/download/boost-1.81.0/boost-1.81.0.tar.xz
      #URL file:///home/bailey/recv/boost-1.81.0.tar.xz                                                                                                                                                
      URL_HASH SHA256=06bc525a392650eb6248f40a13f40112b6c485eec7103b6dcde7196f2a3570e0
   )

   FetchContent_MakeAvailable( Boost )
endif()
```

Something like this provides ease of use, transparency, and flexibility.

I would normally use it like this: `cmake -DFC_BOOST_URL=/home/bailey/recv/boost-1.82.0.tar.xz -DFC_BOOST_HASH=andfd60da30be908eff945735ac7d4d9addc7f7725b1ff6fcdcaede5262d511d21e` so that the file wasn't downloaded every time I wanted to build.

**Comment by huangminghuang** [comment]
[CPM](https://github.com/cpm-cmake/CPM.cmake) may be a better choice if you need to control how packages are cached or just use the system one.

**Comment by greg7mdp** [comment]
Thank you @ScottBailey and @huangminghuang for the suggestions. I didn't know about CPM but it seems pretty nice.
Matt suggested a way to work around the issue with `find_package()` in submodules, so I'm pursuing the submodule approach. It seems it should work after all.

**Comment by arhag** [comment]
Currently blocked waiting on https://github.com/AntelopeIO/leap/issues/1104.
