### ISSUE TITLE
leap-util should show number of blocks in blocks.log

### ISSUE THREAD

**Issue by Rossco99** [AntelopeIO/leap#1146]
Previously the ```eosio-blocklog``` tool would show the number of blocks in a blocks.log when running a ```smoke-test```.

This was useful for maintenance and visibility of a blocks.log contents.

The new ```leap-util``` does not show this detail when running a smoke-test and should be reintroduced.

**Comment by matthewdarwin** [comment]
Output in a nice easy-to-parse format is welcome.

**Comment by 766C6164** [comment]
Do you know by any chance in which version of leap eosio-blocklog showed number of blocks in smoke-test? I am looking at the older code and I can see it is being reported only when there is a disagreement between log/index

https://github.com/AntelopeIO/leap/blob/e059d8213e68b998362d19f9b7eeaa607b6230d0/programs/eosio-blocklog/main.cpp#L276

I tested leap-util and when disagreement happens it shows blocks num in error as well:
![image](https://github.com/AntelopeIO/leap/assets/79997103/1edc7468-588e-47c3-afad-5dc9779da3fa)

It is trivial to add it to successful check as well. Any suggestions on the reporting format?

**Comment by Rossco99** [comment]
It used to be in eosio 2.0.x and leap v3.1.0

```./eosio-blocklog --blocks-dir /home/eosphere/datavolume2/telosblocks1/blocks --smoke-test

Smoke test of blocks.log and blocks.index in directory "/home/eosphere/datavolume2/telosblocks1/blocks"
info  2023-05-10T01:40:49.999 eosio-blo block_log.cpp:1321            trim_data            ] block log version= 2
info  2023-05-10T01:40:50.024 eosio-blo block_log.cpp:1375            trim_data            ] first block= 1
info  2023-05-10T01:40:50.024 eosio-blo block_log.cpp:1376            trim_data            ] last block= 277456401
blocks.log and blocks.index agree on number of blocks

no problems found```

**Comment by matthewdarwin** [comment]
`--format=json` parameter to format as json is welcome, especially if generally applied to all (relevant) commands

**Comment by 766C6164** [comment]
> `--format=json` parameter to format as json is welcome, especially if generally applied to all (relevant) commands

Thank you! I'll add a separate issue to have json output available where applicable to the commands in leap-util.
