### ISSUE TITLE
Nodeos shuts down unexpectedly "Exception in http thread pool" 

### ISSUE THREAD

**Issue by Rossco99** [AntelopeIO/leap#1149]
Nodeos shuts down unexpectedly with the error "Exception in http thread pool" , the issue is intermittent and happens every few hours.

In our case it only appears to happen on our Telos Mainnet Public API/Seed nodes .. all of them. Ubuntu 18.04 is being used. I have also seen the issue report on a collapsed API/Seed/BP node on Jungle 4.

![http_thread](https://github.com/AntelopeIO/leap/assets/12730423/6f47a2be-7318-43ff-b162-026730810dc4)

**Comment by heifner** [comment]
Cat: API
