### ISSUE TITLE
block_log_retain_blocks_test failed in CICD

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#115]
First time saw `block_log_retain_blocks_test` failed in CICD: https://github.com/AntelopeIO/leap/runs/8236888891?check_suite_focus=true

```
[2022-09-07T20:41:10.109869    File "/__w/leap/leap/build/tests/block_log_retain_blocks_test.py", line 64, in <module>
    errorExit("Cluster never stabilized")]
```
[ubuntu20-np-logs.zip](https://github.com/AntelopeIO/leap/files/9513931/ubuntu20-np-logs.zip)

**Comment by heifner** [comment]
Also this one: https://github.com/AntelopeIO/leap/runs/8256599664?check_suite_focus=true

**Comment by heifner** [comment]
This appears to be a real issue triggered by one of the peer nodes not having blocks because of the `--block-log-retain-blocks 0` option. Likely will require a `net_plugin` fix.
