### ISSUE TITLE
Use single WASM interface for parallel read-only trx execution

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#1158]
This is one of work items identified in https://github.com/eosnetworkfoundation/product/issues/149 for https://github.com/eosnetworkfoundation/product/pull/161.

In current parallel EOS-VM and EOS-VM-JIT execution, each thread uses a separate WASM interface.
This causes several issues:
- It makes common module cache required for sharing the same compiled WASM module hard to implement.
- The multiple WASM interfaces and associated thread data make code complicated and hard to reason.
- It is not consistent with EOS-VM-OC where only one WASM interface is required.

Single WASM interface is to be used.

**Comment by bhazzard** [comment]
I need to simplify the related product initiatives into one.

**Comment by linh2931** [comment]
PRs:

Leap -- https://github.com/AntelopeIO/leap/pull/1549
EOS VM -- https://github.com/AntelopeIO/eos-vm/pull/20
