### ISSUE TITLE
get_table_by_scope returns the table rows count wrongly

### ISSUE THREAD

**Issue by iamveritas** [AntelopeIO/leap#1174]
repro:
run the following command:

curl --request POST \
--url https://eos.dfuse.eosnation.io/v1/chain/get_table_by_scope \
--header 'content-type: application/json' \
--data '{
"json": true,
"code": "eosio",
"table": "producers",
"lower_bound": "eosio",
"upper_bound": "",
"reverse": false,
}'

actual result:
{"rows":[{"code":"eosio","scope":"eosio","table":"producers","payer":"superoneiobp",`"count":1328`}],"more":"ericrebe.ftw"}

expected result:
{"rows":[{"code":"eosio","scope":"eosio","table":"producers","payer":"superoneiobp",`"count":614`}],"more":"ericrebe.ftw"}

note in the expected result that the count is half of the count in actual result.

details:
today the `count` is calculated by a formula which goes like this `count = (N+1) * number of rows in table`.  where N is the number of secondary indices defined for that table. this is confusing.

the count should be just the number of rows in the table. simple. straightforward. nice to have: rename count to rows_count.

**Comment by bhazzard** [comment]
Count is a misleading naming. It does not represent the number of rows.

Our current planned options are:
- Ignore
- Document the confusing naming/behavior
- Deprecate "count" for removal from the response.

@iamveritas Can you provide information about the use case in which you need to use the count of the number of rows?

**Comment by bhazzard** [comment]
@bhazzard to close this issue and open a new issue to track our intention to deprecate "count" for removal from the response.
