### ISSUE TITLE
app_base plugin initialize behavior is inconsistent

### ISSUE THREAD

**Issue by jgiszczak** [AntelopeIO/leap#1181]
In the `appbase` submodule, plugin initialization is handled in two different lists: first all explicitly requested plugins are initialized, during which their dependencies are initialized.  This happens outside of a `try {} catch {}` block.  Then any remaining autostart plugins are initialized, this time inside a `try {} catch {}` block.  Because nodeos uses exceptions for flow control, this can result in different return codes when `nodeos` encounters a startup error and throws, depending on the options passed to the program.  `nodeos` return code behavior should not change based on the order of plugin initialization.

**Comment by heifner** [comment]
Reopen for leap integration PR.
