### ISSUE TITLE
abi_serializer: Missing field exception thrown when an std::optional is used in a field of an action input parameter 

### ISSUE THREAD

**Issue by elmato** [AntelopeIO/leap#1189]
```
struct test_input {
   uint64_t a;
   std::optional<uint64_t> b;
};

[[eosio::action]] void test(const test_input& input);
```

Create a failing test case reproducing this issue. Then fix it.

**Comment by bhazzard** [comment]
This was reported by Matias. Impacts EVM. Test to confirm this doesn't also impact abieos.

**Comment by greg7mdp** [comment]
@elmato I have a fix in my branch `gh-1189-test` (based off `main`) if you want to try it.
