### ISSUE TITLE
get_block_info not working

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#1196]
From Ovi:

This get_block using block number returns valid result:

curl -X POST https://eos.greymass.com/v1/chain/get_block \
  -H "Content-Type: application/json" \
  -d '{"block_num_or_id": 292223356}'

But this get_block_info using the same block number as above is saying block doesn’t exist:

curl -X POST https://eos.greymass.com/v1/chain/get_block_info \
  -H "Content-Type: application/json" \
  -d '{"block_num": 292223356}'

result:
{"code":400,"message":"Unknown Block","error":{"code":3100002,"name":"unknown_block_exception","what":"Unknown block","details":[{"message":"Could not find block: 292223356","file":"chain_plugin.cpp","line_number":2082,"method":"get_block_info"}]}}%

**Comment by heifner** [comment]
Seeking input from greymass as I suspect it is something on their side.

**Comment by linh2931** [comment]
I tried with my local nodeos. It worked.

**Comment by bhazzard** [comment]
Appears to be an issue with greymass's customized endpoints.

**Comment by heifner** [comment]
Thanks for the update @aaroncox
