### ISSUE TITLE
pinned_build.sh cannot find -lstdc++

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#1198]
Rick Whitner, [May 16, 2023 at 1:54:48 PM]:
I ran into an error building leap v4.0.0:  /usr/bin/ld: cannot find -lstdc++: No such file or directory

This is a fresh build on a new system. I'm following the README instructions on github.com/AntelopeIO/leap for a pinned build. I ran the install_deps.sh script per instructions Then I ran scripts/pinned_build.sh deps build "$(nproc)".

I ran into an error building leap v4.0.0:  /usr/bin/ld: cannot find -lstdc++: No such file or directory

This is a fresh build on a new system. I'm following the README instructions on github.com/AntelopeIO/leap for a pinned build. I ran the install_deps.sh script per instructions Then I ran scripts/pinned_build.sh deps build "$(nproc)".

**Comment by bhazzard** [comment]
@rbw3821 Can you provide device details for the environment where you ran into this?

**Comment by bhazzard** [comment]
Workaround exists by not doing a pinned build or building in a docker image. Will close for now, and let a new issue be opened if others run into this issue.

@rbw3821 , please provide details of your ubuntu device to @oschwaldp-oci
