### ISSUE TITLE
get_info off the main thread

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1212]
Currently `/v1/chain/get_info` processing is posted to the main thread. `get_info` could be moved off the main thread by copying the current get_info data into the `get_info_results` struct on every `accept_block` signal. Then `get_info` could be handled completely off the main thread.

**Comment by matthewdarwin** [comment]
FWIW, from time to time /v1/chain/get_info is either the #1 or #2 API call made to the EOS Nation endpoints.  Usually second after get_table_rows.  Last 24 hrs:

![image](https://github.com/AntelopeIO/leap/assets/26171839/c74c552c-7f24-4739-bb4b-2f57f860e08b)

**Comment by matthewdarwin** [comment]
All chains, last 24 hrs:

![image](https://github.com/AntelopeIO/leap/assets/26171839/37961bb7-5281-4de5-9326-a8fdca6ae28f)

**Comment by heifner** [comment]
Moved to Spring https://github.com/AntelopeIO/spring/issues/527
