### ISSUE TITLE
Starting node from a snapshot fails if the node has no blocks

### ISSUE THREAD

**Issue by RalfWeinand** [AntelopeIO/leap#1228]
We just noticed an issue with Leap v4.0.1 when we created a new Telos Testnet BP node. Starting it from a snapshot (without any blocks in the blocks folder) resulted in this error. 

![telegram-cloud-photo-size-5-6329874667602556377-y](https://github.com/AntelopeIO/leap/assets/1137211/8b20a3f5-3412-41c8-aa2a-ea053139cb17)

We tried different snapshots, and different config.ini settings & start parameters (e.g. --delete-all-blocks) but nothing helped.

We then downgraded to Leap v3.2.3 and nodeos started from the same snapshot without blocks without this error.

**Comment by greg7mdp** [comment]
@RalfWeinand can you share the command and `config.ini` that you use to start nodeos?
