### ISSUE TITLE
Log all non-default config.ini and command line options on nodeos startup/shutdown

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1279]
Logging all non-default config.ini and command line options on nodeos startup would help with user reporting of issues. Also would make it clear if the expected config.ini was actually used.

Requirements
- Log non-default configs/options on startup
- Log non-default configs/options on termination (current value)
- Log nodeos version on termination
- Ensure private key data is masked
- Ensure peer list is masked
- Evaluate all other configs/options to for masking sensitive data in log output

**Comment by greg7mdp** [comment]
I think it would also be good to log these at termination, as users often provide a screen shot of what happens when `nodeos` terminates (including error messages).
