### ISSUE TITLE
Unexplained occurances of "peer sent a handshake with a timestamp skewed by at least -2ms"

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1284]
Even after installing patch for https://github.com/AntelopeIO/leap/issues/1240 on top of leap 4.0.1, we still see messages of the type:

```
Peer sent a handshake with a timestamp skewed by at least -2ms
```

The clocks are not skewed by -2ms because we can see the nodes report the similar block arrival time from the same BP, which would not be the case if they were offset by 2ms.  Now maybe something is causing messages to get delayed?

It can bee seen that node clocks are basically in sync in the image here:

![image](https://github.com/AntelopeIO/leap/assets/26171839/af7b6980-b10e-40d8-bda6-c2f65e276da9)

Let me know if you need me to collect log data on how oven this happens.

I do not recall this issue occurring in earlier versions of leap 3.1 or 3.2, but I wasn't paying attention to it either. (maybe logging level has been changed so now I see it?)

**Comment by heifner** [comment]
That log message and calculation has not changed since pre 3.1.0.

**Comment by heifner** [comment]
Should update to only log an error if skew is > block interval to reduce warning messages for skew that doesn't really matter.
