### ISSUE TITLE
Test failure: test_snapshot_scheduler

### ISSUE THREAD

**Issue by oschwaldp-oci** [AntelopeIO/leap#1286]
Noticed this test failing on branch off of `main` where only changes being made were in github workflows and shouldn't affect tests at all.

https://github.com/AntelopeIO/leap/actions/runs/5268053682/jobs/9524375481

```/__w/leap/leap/tests/test_snapshot_scheduler.cpp(100): error: in "producer_snapshot_scheduler_tests/snapshot_scheduler_test": check block_num == ps_start - deviation has failed [12 != 13]```

**Comment by heifner** [comment]
`/__w/leap/leap/tests/test_snapshot_scheduler.cpp(100): error: in "producer_snapshot_scheduler_tests/snapshot_scheduler_test": check block_num == ps_start - deviation has failed [12 != 13]`
