### ISSUE TITLE
Modify 'producer_repetitions' and 'block_interval_ms'

### ISSUE THREAD

**Issue by zhi-lu** [AntelopeIO/leap#1300]
Hello, my dear friend. I have a small issue now, which is that I want to modify the values of "producer_repetitions" and "block_interval_ms" in the "config.hpp" file through the relevant configuration items during eos startup, instead of using patches to hack the source code. Is this possible?

**Comment by bhazzard** [comment]
This would need to be built as a protocol feature, not simply a nodeos option. We have no concrete plans to make this change at this time.
