### ISSUE TITLE
Problems with ship initial block in Leap 4.0.3

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/leap#1340]
I started a ship server from a recent portable snapshot (Proton Mainnet, which is fully EOS-compatible), then after restart it prints

```
info  2023-06-25T17:24:07.549 nodeos    block_log.cpp:666             open                 ] Log has 53169 blocks
info  2023-06-25T17:24:07.554 nodeos    http_plugin.cpp:258           plugin_initialize    ] configured http to listen on 0.0.0.0:18805
info  2023-06-25T17:24:07.554 nodeos    log.hpp:713                   open_log             ] trace_history.log has blocks 200079887-200133387
info  2023-06-25T17:24:07.554 nodeos    log.hpp:713                   open_log             ] chain_state_history.log has blocks 200079886-200133387
```

Trying to start Chronicle from this ship endpoint, and getting a number of various errors:

1. If I remove all p2p peers (to save the CPU  and  storage I/O), Chronicle does not receive anything from ship.

2. With at least one  living p2p peer, starting chronicle with `--start-block=200079886` and it starts receiving table deltas immediately. It's supposed to receive the whole state first, so that it populates its ABI database. This is a breaking change.

**Comment by cc32d9** [comment]
snapshot source:  http://seed01.eosusa.news/snaps/proton/proton-2023-06-25_10-00.tar.gz

node configuration:

```
chain-state-db-size-mb = 65536
#

wasm-runtime = eos-vm-jit
eos-vm-oc-enable = false
read-mode = head

http-server-address = 0.0.0.0:18805
p2p-listen-endpoint = 0.0.0.0:19805

http-validate-host = false

access-control-allow-origin = *
access-control-allow-headers = *

#verbose-http-errors = true
contracts-console = true
validation-mode = light

max-clients = 100

plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
#plugin = eosio::db_size_api_plugin

plugin = eosio::state_history_plugin
trace-history = true
chain-state-history = true
state-history-endpoint = 0.0.0.0:18085

sync-fetch-span = 50

#p2p-peer-address = proton.cryptolions.io:9876
p2p-peer-address = proton.eu.eosamsterdam.net:9103
#p2p-peer-address = p2p-proton.eosarabia.net:9876
```

**Comment by heifner** [comment]
Testing with 3.1 I do not see deltas in the first block after a snapshot. What version of SHiP do you see expected behavior?
