### ISSUE TITLE
Chicken Dance Solution Design

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1353]
Draft a plan for implementing Chicken Dance for Leap v5.0.0

See the related [Product Initiative](https://github.com/eosnetworkfoundation/product/issues/91).

Include a list of the necessary tasks.

**Comment by matthewdarwin** [comment]
Does chicken dance include ship?

**Comment by matthewdarwin** [comment]
See https://github.com/AntelopeIO/leap/issues/1354 for why I ask about it.

**Comment by cmadh** [comment]
Any chance to include deep-mind-logging?

**Comment by ericpassmore** [comment]
> Any chance to include deep-mind-logging?

Tell me more, what are some advantages to including deep-mind logs?

**Comment by bhazzard** [comment]
Solution design and work breakdown completed.
