### ISSUE TITLE
Add idle data to nodeos 5.0 prometheus exporter

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1359]
In debugging https://github.com/AntelopeIO/leap/issues/1349, I asked Kevin if there are counters in the leap 5.0 prometheus exporter that capture the same content as these log lines:

```
Block #317926278 trx idle: 237us out of 199964us, success: 3, 578us, fail: 230, 197119us, transient: 0, 0us, other: 2030us
```

Seems no.  So this is a request to add counters.

**Comment by bhazzard** [comment]
Totally valid, and seems straightforward.
