### ISSUE TITLE
Add producer name to trx idle log message

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1360]
In debugging https://github.com/AntelopeIO/leap/issues/1349, it was observed by Kevin that it would be good to log the producer name for the following message:

```
Block #317926278 trx idle: 237us out of 199964us, success: 3, 578us, fail: 230, 197119us, transient: 0, 0us, other: 2030us
```
producer_plugin.cpp:290 in leap 4.0.3

This extra information would allow creating charts per block producer on https://blockchain.stats.eosnation.io

**Comment by bhazzard** [comment]
This seems like a simple enough change, and has obvious value.
