### ISSUE TITLE
Disable Replay Opts by default if statehist plugin enabled

### ISSUE THREAD

**Issue by eosusa** [AntelopeIO/leap#1403]
Currently, if you have the state history plugin enabled on the node, it requires the additional parameter of --disable-replay-opts to always be passed as an argument.  If you don't pass the argument, the node just errors that it should be disabled.  Can it be just added into the logic that if the statehist plugin is enabled that the "replay opts" are disabled automatically, which would help standardize not having to have the special param for statehist nodes (or forgetting to include it and having to relaunch)

**Comment by bhazzard** [comment]
Agreed.

Another problem is that --disable-replay-opts cannot be specified by config file, which makes this even worse.

The way it works today is silly, we should make these changes:
- handle disabling replay opts implicitly when state history plugin is enabled
- add disable replay opts as a config option

In the future, we should consider these sort of special cases being handled by designing around operational modes, either having special purpose executables or simple nodeos options that encapsulate the needs of the given operational mode.
