### ISSUE TITLE
Test Failure: performance_test_basic_read_only_trxs

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1416]
https://github.com/AntelopeIO/leap/actions/runs/5602344355/jobs/10247564180

Set of system contract failing: ` cmd: /__w/leap/leap/build/bin/cleos --url http://localhost:8788  --wallet-url http://localhost:9899 --no-auto-keosd -v set contract -j  eosio /__w/leap/leap/build/unittests/contracts/eosio.system eosio.system.wasm eosio.system.abi`

The `genesis.json` is using 150ms for `max_transaction_cpu_usage` even though the `tests/performance_tests/genesis.json` has the value of 475ms. The value apparently is being overwritten to 150ms somewhere.

Looks like here: `cfg.add_argument('--max-transaction-cpu-usage', type=int, help='the "max-transaction-cpu-usage" value to use in the genesis.json file', default=150000)` in `launcher.py`.

**Comment by heifner** [comment]
Note this was not enough: https://github.com/AntelopeIO/leap/pull/1401 because of the default provided by `launcher.py`.

**Comment by greg7mdp** [comment]
> Looks like here: `cfg.add_argument('--max-transaction-cpu-usage', type=int, help='the "max-transaction-cpu-usage" value to use in the genesis.json file', default=150000)` in `launcher.py`.

Hum, not sure, even if I change this value from `150,000` to `10,000` the test still succeeds when I run it locally.
