### ISSUE TITLE
Team needs AWS access for Chicken Dance

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#1420]
Greg, Lin, and Eric need AWS access to the S3 instance, and permission to spin up spot ec2 nodes.

**Comment by ericpassmore** [comment]
Greg, Lin, and myself need AWS access to the S3 instance, and permission to spin up spot ec2 nodes.

**Comment by BenjaminGormanPMP** [comment]
Per @ericpassmore target completion for @kj4ezj is 09/01/23.

**Comment by kj4ezj** [comment]
A new AWS account was created in the ENF organization named `chickens-prod`. The root user account was locked down. IAM policy documents were created granting IAM users the necessary permissions to manage their own credentials, requiring multi-factor authentication, and restricting all resources to one specific region in AWS. IAM users were created for the requested employees with randomly generated one-time passwords. These first-login credentials were shared in an encrypted message via email that will self-destruct after two days or two access attempts, and the decryption key for the email message was shared via IM.

Please reach out to Automation if you need any help gaining access to your IAM user, if your team needs IAM permissions modified, or if your team needs lower environments such as staging or a sandbox.
