### ISSUE TITLE
Invalid Base64 padding returned by APIs

### ISSUE THREAD

**Issue by aaroncox** [AntelopeIO/leap#1461]
Reference issue: https://github.com/EOSIO/eos/issues/8161

Figured I'd bring this old issue up again because I just ran into this once more. 

The padding used in the base64 implementation that nodeos uses to respond with in select API requests is invalid, which causes any library used to interpret that data to throw errors. 

An example invalid response can be seen on Jungle4 when querying the `eosio.token` contract.

```
curl https://jungle4.greymass.com/v1/chain/get_raw_abi -d '{"account_name": "eosio.token"}'
```

Note that the end of the base64 data contained in the `.abi` field is `===`, which itself is invalid padding for base64 data. 

We have also seen responses which include `=` when needing `==`, and vice versa. Whatever code is generating the base64 representations of this data for nodeos is doing so incorrectly on multiple fronts.

**Comment by bhazzard** [comment]
There is a small chance that fixing this could "break" someone who is relying on the invalid padding. We should call this out clearly in the release notes for 5.0.
