### ISSUE TITLE
Tests: fix test_resmon_plugin test failure

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1485]
https://github.com/AntelopeIO/leap/actions/runs/5834112382/job/15823238447

**Comment by spoonincode** [comment]
saw again on
https://github.com/AntelopeIO/leap/actions/runs/6180131909/job/16776270770

pretty weird looking

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/leap/actions/runs/6395708177/job/17360355859

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/leap/actions/runs/6424323959/job/17444943478?pr=1726
