### ISSUE TITLE
Update cleos for history_api_plugin

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1494]
Need to update the error message for no `history_api_plugin`.
```
Error 3110003: Missing History API Plugin
Ensure that you have eosio::history_api_plugin added to your node's configuration!
Error Details:
History API plugin is not enabled
```

Could consider removing the `cleos` commands but they are still supported by `history_api_plugin` emulators.

**Comment by heifner** [comment]
@cc32d9 comment on Antelope Developers "I'd rather remove the command. The history solutions offer a bunch of different APIs".

**Comment by bhazzard** [comment]
Closed by https://github.com/AntelopeIO/leap/pull/1733
