### ISSUE TITLE
Support C++20 for release branch

### ISSUE THREAD

**Issue by yarkinwho** [AntelopeIO/leap#1497]
Contracts such as EOS-EVM rely on testers code in leap to build the unit tests. It would cause quite a lot trouble if the leap code does not support C++20 while some other libraries used by the unit tests start to switch to C++20.

**Comment by heifner** [comment]
For 4.0.x, I believe all that is needed is the removal of these lines: https://github.com/AntelopeIO/leap/pull/1070/files#diff-d81bca537ada1ccf67b84dc409d9a71010c9dfb14006b57c45adf09717bbbc9bL40-L44

**Comment by spoonincode** [comment]
As of 5.0 libtester is C++20. A change to the EVM testing environment to use libtester 5.0 is at eosnetworkfoundation/eos-evm-contract#681 so I think we can close this issue out as complete.
