### ISSUE TITLE
Test failure: nodeos_extra_packed_data_test failed

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#1501]
https://github.com/AntelopeIO/leap/actions/runs/5871403809/job/15921525923?pr=1498

2032 - nodeos_extra_packed_data_test (Failed)

2023-08-15T21:03:57.805143              cmd: /__w/leap/leap/build/bin/cleos --url http://localhost:8788  --wallet-url http://localhost:9899 --no-auto-keosd get transaction_trace 423f9bf05fc9b864d929eda83824354fa5ca368df9aec3086ed390635412bcbe
2023-08-15T21:03:57.827271               FAILURE - Exception during "get transaction_trace". Exception message: Error 3200005: http request fail
Error Details:
Error code 404
: {"code":404,"message":"Trace API: transaction id missing in the transaction id log files","error":{"code":0,"name":"","what":"","details":[]}}

.  stdout: .  cmd Duration=0.021 sec. Context: (transaction id=423f9bf05fc9b864d929eda83824354fa5ca368df9aec3086ed390635412bcbe)
2023-08-15T21:03:57.827657               ERROR: Exception during "get transaction_trace". Exception message: Error 3200005: http request fail
Error Details:
Error code 404
: {"code":404,"message":"Trace API: transaction id missing in the transaction id log files","error":{"code":0,"name":"","what":"","details":[]}}

.  stdout: .  cmd Duration=0.021 sec. Context: (transaction id=423f9bf05fc9b864d929eda83824354fa5ca368df9aec3086ed390635412bcbe)
2023-08-15T21:03:57.827937  Test failed.

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/5883002818/job/15954954076

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/5955738860/job/16155221794

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/5977425404/job/16217668080

**Comment by oschwaldp-oci** [comment]
https://github.com/AntelopeIO/leap/actions/runs/6188449788/job/16800780894?pr=1637

**Comment by heifner** [comment]
Completed by #1728 & #1737

**Comment by heifner** [comment]
Same issue:
https://github.com/AntelopeIO/leap/actions/runs/6458105968/job/17531405244

The retry didn't work correctly because `waitForTransactionInBlock` exits with error instead of return `False` when transaction does not show up in a block.

**Comment by heifner** [comment]
The retry actually failed because it was already applied. Need to handle that corner case.
https://github.com/AntelopeIO/leap/actions/runs/6476622261
