### ISSUE TITLE
When nodeos stops, It doesn't say which file system is exceeded.

### ISSUE THREAD

**Issue by sajjadbaeidi** [AntelopeIO/leap#1504]
We experienced a shutdown because of exceeding the threshold of the file system.
![image](https://github.com/AntelopeIO/leap/assets/4597047/4c872fa7-5162-4205-bd3a-3e14f6661b2f)

But Nodeos didn't log which file system was exceeded during the shutting down process.

Although, Nodeos list them when starting up.
![image](https://github.com/AntelopeIO/leap/assets/4597047/b394eb92-2f25-487e-b17a-8b3366c0db72)

**Comment by heifner** [comment]
I believe this was fixed by: https://github.com/AntelopeIO/leap/issues/395 in 4.0.
What version of nodeos were you running?

**Comment by sajjadbaeidi** [comment]
Great, We have both `v4.0.4` and `v3.2.4`. 
But that issue was on the nodes running the `v3.2.4` version.
Thank you.
