### ISSUE TITLE
Liveliness check for ci/cd

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1505]
Create a simple exec to log every 100ms and run it along side all integration tests. This would allow us to know if/when a vm does not get cpu cycles over 100ms.

**Comment by bhazzard** [comment]
Overall this is would be a good thing to do, but low priority. One downside is this works around issues without needing to address the underlying cause of a problem.

**Comment by bhazzard** [comment]
Decision to close this issue and instead address issues as they arise.
