### ISSUE TITLE
IF: Update BLS integration to use HotStuff version from main

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1509]
The current commit of the `hotstuff_integration` branch (https://github.com/AntelopeIO/leap/commits/005d500e7b9a29325be0fd253710a5fe205f1792) uses an old version of BLS code that has since been modified as part of the effort of merging the code into the `main` branch of Leap.

The `hotstuff_integration` branch should be changed to fix the discrepancy of BLS between the branch and `main`. Also additional immediate merge conflicts should be resolved.

**Comment by heifner** [comment]
Completed by #1527
