### ISSUE TITLE
IF: Refactor integration tests to support legacy & IF consensus in parallel

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1510]
Depends on https://github.com/AntelopeIO/leap/issues/1522 and https://github.com/AntelopeIO/leap/issues/1548.

**Comment by arhag** [comment]
Changes are in place to run tests with IF but they are disabled at the moment pending fixes needed to IF (which depends on #1941).

**Comment by heifner** [comment]
Resolved by #2166 and #2124
