### ISSUE TITLE
IF: Add integration test for transition from legacy consensus to IF consensus

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1512]
Depends on https://github.com/AntelopeIO/leap/issues/1522 and https://github.com/AntelopeIO/leap/issues/1548.

Many of the tests transition from pre-IF to IF to carry out the tests (see https://github.com/AntelopeIO/leap/issues/1510). But they transition with 1 BP.

This integration test should test the transition with multiple BPs. To keep test runtime short, stick with 4 BPs.

**Comment by heifner** [comment]
Resolved by #2224
