### ISSUE TITLE
IF: Address abstraction leakage in HotStuff library

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1518]
Specifically:

* `fc::unsigned_int` usage (which we reserve only for serialization)
* On wire message struct passed throughout the code.

**Comment by heifner** [comment]
From @ericpassmore : chain_plugin.hpp is included in many places carrying hotstuff with it. When I look for the hs_* structures which also include chain_plugin.hpp I find three files net_plugin producer_plugin chain_plugin. An alternative would be having another header with the hotstuff structures and include the new header in the three files.
