### ISSUE TITLE
Issue with the subjective nature of max_nonprivileged_inline_action_size

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#152]
Currently (since EOSIO 2.0.7), max_nonprivileged_inline_action_size is a subjective parameter set by node operators, with a default value of 4096 bytes.

This is problematic for two reasons :

1) It can potentially be in conflict with the consensus global chain setting max_inline_action_size (this conflict currently exists for  EOS, Telos, Jungle4 and Kylin, where the max_inline_action_size is set to 524287 bytes)

2) It may create very difficult to diagnose problems if node operators were to use different values for this setting, where an API node could accept a tx, but that tx would fail upstream or at the block producer level

It probably would be best to either make it a consensus parameter and align its default value with the current value for max_inline_action_size, or to remove it entirely

**Comment by stephenpdeos** [comment]
Because this requires a significant amount of work to appropriately solve and align with our resource model, we will not be taking short term action on this issue.
