### ISSUE TITLE
IF: HotStuff code cleanup

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1520]
* Address style inconsistency
* Remove extraneous comments
* Easy optimization (address pass-by-value arguments)
* Change unit tests that could easily run in parallel so that they run as part of our parallelizable tests.

**Comment by heifner** [comment]
- Fix all warnings

**Comment by greg7mdp** [comment]
* Use compact namespaces: `namespace eosio::chain {`

**Comment by arhag** [comment]
Overcome by events.
