### ISSUE TITLE
IF: Safely persist HotStuff state

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1521]
Critical state should be persisted at the right time in the consensus process so that the algorithm remains safe even if the nodeos process is restarted. Ideally, it should remain safe even if the nodeos process is killed, though this may become a fast follow issue. Being safe even after machine power failure is not in scope for this issue.

The goal should be that an honest block finalizer does not send out signatures on proposals that can contribute towards a finality violation (even if not enough other block finalizers are doing the same to make an actual finality violation occur).

**Comment by heifner** [comment]
```
// writing
fc::cfile pfile;
pfile.set_file_path(file_path);
pfile.open(fc::cfile::truncate_rw_mode);
auto data = fc::raw::pack(stuff);
pfile.write(data.data(), data.size());
pfile.flush();
pfile.close(); // or let destructor do it
```

```
// reading
fc::cfile pfile;
pfile.set_file_path(file_path);
pfile.open("rb");
auto ds = pfile.create_datastream();
fc::raw::unpack(ds, stuff);
pfile.close(); // or let destructor do it
```

**Comment by heifner** [comment]
Along with the critical information stored for hotstuff. 
The hs_commitment needed by #1586.
The active finalizer set. (implicit that hotstuff is activated)
The current LIB of hotstuff.

**Comment by BenjaminGormanPMP** [comment]
Prioritized for iteration.
