### ISSUE TITLE
IF: Support transition from legacy consensus to HotStuff consensus

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1523]
Depends on https://github.com/AntelopeIO/leap/issues/1511, https://github.com/AntelopeIO/leap/issues/1532, https://github.com/AntelopeIO/leap/issues/1610, #1631, and https://github.com/AntelopeIO/reference-contracts/issues/26.

Block header extension to capture new finalizer set.

Producer plugin config allows for specifying block finalization key pairs.

Questions:

* When do new messages get sent over P2P network?
  * KH: I suggest 5.0 always send these messages. But if we are concerned about a network not ever activating hotstuff, maybe add an option to disable them?

For this issue, we are not switching existing tests over to use IF.

However, a new unit test is needed that switches to IF to test the transition.

To implement that new test, we will need to pull in https://github.com/AntelopeIO/reference-contracts/issues/26 bios contract to set the first finalizer set and transition to HotStuff.

Also add constraints to `set_finalizers` host function to meet needs of https://github.com/AntelopeIO/leap/issues/1569: ✓
* Each finalizer can have a description that does not exceed 256 bytes. ✓
* There can be a maximum of 2^16 finalizers in the finalizer set. ✓

After HotStuff transition, the parameters in `block_header_state` used by the old consensus algorithm (LIB, proposed LIB, etc.) are no longer needed and should not be used. But the fork choice rule in fork DB uses the LIB from `block_header_state` to decide on the best chain. Additionally, plugins currently expect `block_header_state` to be immutable.

We would like to keep the simple concept that the `block_header_state` is immutable and computed purely from the prior `block_header_state` and the new `block_header`. This means `block_header_state` cannot store LIB and the active finalizer set.

So we need to still store the real LIB in fork DB (fork choice rule must use this LIB once transitioned to HotStuff rather than the obsolete one in `block_header_state`).

Open questions:
* Where do we store the active finalizer set since we cannot store it in `block_header_state`? [Maybe store in qc_chain?]
* Do we need to store the active finalizer set in the portable snapshot? If so, how does this impact the determinism of the portable snapshot?
* What else do we need to store in the portable snapshot to allow for nodes to safely recover liveness?
* Do we need to include the active finalizer set as part of the integrity hash? If so, how does this impact the determinism of the integrity hash?

**Comment by heifner** [comment]
Seems like this depends on https://github.com/fcecin/leap/commit/74295f20142ef415d6e118701777f12a7937f187 which is not currently in `hotstuff_integration`

**Comment by heifner** [comment]
Block header extension
- host function sets in pending block
- multiple calls in one block overwrite value in pending block
- proposed finalizer set added to block header extension

Chainbase
- active_finalizer_set
- when block becomes LIB with a proposed finalizer set, updates active finalizer_set

**Comment by heifner** [comment]
- Any desire to update `keosd` to support BLS keys? Any desire to allow `nodeos` to use `keosd` to retrieve finalizer BLS private keys?

**Comment by arhag** [comment]
> Any desire to update keosd to support BLS keys? Any desire to allow nodeos to use keosd to retrieve finalizer BLS private keys?

It would be nice, but we don't need that for 5.0. So we can skip it if it saves time.
