### ISSUE TITLE
IF: Fix failing test bls_sig_verif_string_multi

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1531]
libraries/libfc/test/test_bls.cpp
`bls_sig_verif_string_multi`
Failing in branch `hotstuff_integration_main`

**Comment by systemzax** [comment]
This test can be safely ignored. It was intended to verify the prefix encoding, which we have now since removed.

**Comment by heifner** [comment]
The prefix encoding is still currently there. Will you be creating a PR to remove the test and prefix encoding?

**Comment by systemzax** [comment]
Apologies, I had it removed in another branch that somehow didn't make its way into this one. Created a pull request here that takes care of this. It also has bls_private_key base58 encoding and an additional unit test for this. https://github.com/AntelopeIO/leap/pull/1538

**Comment by heifner** [comment]
Completed by #1538
