### ISSUE TITLE
IF: Add new snapshot version to hold consensus hotstuff state

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1558]
Depends on #1523 and #2080.

We will store the active finalizer set in the snapshot. Note this will be a non-backwards compatible snapshot version. Leap 5.0 can import older versions of snapshots that it currently supports, but it can only export the new version of the snapshot (v7).

Remove `if not activateIF` from `ship_streamer_test.py` and uncomment `nodeos_snapshot_diff_if_test` in `tests/CMakeLists.txt`.

**Comment by linh2931** [comment]
Will get the wiring ready first.
