### ISSUE TITLE
IF: Use bls_public_keys as finalizer identifiers instead of name/description

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1568]

**Comment by systemzax** [comment]
As part of this issue, we should also rename the extended_schedule to finalizer_set, as well as add a weight associated to each bls_public_key. The weight is intended to function in a similar way to authorizations, where finalizers may have a different weight contributing towards reaching a quorum.

**Comment by greg7mdp** [comment]
Why not identify them by their index?

**Comment by arhag** [comment]
Work already capture as part of https://github.com/AntelopeIO/leap/issues/1521.
