### ISSUE TITLE
IF: Verify net messages for validity

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1569]
Depends on #1881 and #1657.

- Verify `hs_vote_message` finalizer is valid one to use. Verify public key is part of the sig. (This should be done once in qc_chain.)
- Verify `quorum_certificate_message` `active_finalizers` public keys are part of the sig. (This should be done once in qc_chain.)
- Verify length of `quorum_certificate_message` `active_finalizers` does not exceed maximum size calculated based on maximum number of allowed finalizers (2^16) and the constraint that each finalizer has a description that does not exceed 256 bytes.

**Comment by arhag** [comment]
So far only for Proposal messages (P) and still not complete. Need to expand for Vote messages (V) and QC messages (Q).

Three categories of message validation failure:

1. Immediately disconnect peer that sent the message:

- Proposal has slot/view number that violates monotonicity (or other objectively verifiable constraints). (P2)
- Proposal is for a slot/view number that is very far in the future. (P4)
- Proposal by leader not allowed to propose for that slot/view number.

2. Track by updating per-connection abuse detector (which may eventually disconnect peer):

- Unlinkable proposal. (P1)
- Proposal is for a slot/view number that is a little bit in the future. (P3)

3. Drop message and do nothing else other than maybe logging:
