### ISSUE TITLE
IF: Update net syncing after hotstuff activation

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1581]
When syncing after hotsutff activation need some indication of LIB so that blocks can be flushed to blocklog and removed from memory.
The qc's required will need to be stored at some intervals including all qc's around active finalizers change. These will need to be provided to the peer node as it syncs blocks. A store for this information will be needed. net_plugin will need to be modified to provide these qc's along with blocks during sync.

**Comment by arhag** [comment]
Closed in favor of https://github.com/AntelopeIO/leap/issues/1586.
