### ISSUE TITLE
IF: Switch encoding for BLS keys and signatures to base64

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#1584]
https://github.com/AntelopeIO/leap/issues/1532 implemented the text encoding for the keys and signatures with base58 (following the bad precedent we have established for the other key types). On further thought, we think it is best to switch to a base64 encoding to simplify the implementation for the encoder/decoder that needs to compile to WebAssembly.

**Comment by heifner** [comment]
Completed by #1587
