### ISSUE TITLE
IF: Redefine view number and add generation number to the finalizer set

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#1589]
The view number on a proposal should be redefined to be a monotonically-increasing number, decoupled from the block height and QC-chain phase.

The maximum valid view number increment between proposals must be constrained in a time-bound manner relatively to the head_block's previous block timestamp.

Add a generation number to the finalizer set, indicating the ordinal version of the finalizer set since HS activation. The generation number is also added to the definiton of a proposal, and must be added to the digest to sign by finalizers when casting a vote on the proposal.

See gist : https://gist.github.com/arhag/3071922a6cecf563ad6cca183b8a76d0

**Comment by arhag** [comment]
Replaced by unification work.
