### ISSUE TITLE
Regarding whether the 2.x and 3.x RPC interfaces are fully compatible.

### ISSUE THREAD

**Issue by zhi-lu** [AntelopeIO/leap#1590]
My Leap bros, I have a question about whether the RPC interfaces we currently use for 2.x (eosio) and 3.x (leap) are fully compatible. I am trying to test them through Postman,
such as https://developers.eos.io/manuals/eos/latest/nodeos/plugins/chain_api_plugin/api-reference/index Interface in. It was found that there were some differences in return. No other issues were found. I would like to confirm this with you. Thank you. 🙏

**Comment by heifner** [comment]
If I remember correctly the only difference is additional information returned for some endpoints and better error codes on failure.

**Comment by zhi-lu** [comment]
Thank you.
