### ISSUE TITLE
Tool to repair blocks in State History logs

### ISSUE THREAD

**Issue by eosusa** [AntelopeIO/leap#1593]
I have an EOS 4.0.4 state history node I've synced from genesis.  Along the way, ran into a few bugs and crashes which got fixed, but apparently during the process there is bad data in the massive state history logs from block 112mil, so trimming and replay would take 2 months to resync.  When the particular bad block is being read, the following error is thrown in the nodeos logs:
```
error 2023-09-05T13:15:03.408 ship-0    session.hpp:579               callback             ] zlib error: unspecified iostream_category error
```

The node has a full blocklog (since it was synced from genesis), so someone suggested we need a state history repair tool to where a selected block/range of the chain can be specified and the statehist logs repaired/replayed for those specific damaged/unreadable blocks.  Otherwise, I have 8.1TB of state history files, most of which is data AFTER block 112mil, that is unusable but seems easily repairable since the blocklog is available.

**Comment by eosusa** [comment]
Sad update:  so apparently even if you trim the blocklog to an earlier block, when the node resyncs forward it still detects the state history logs have the blocks and does not overwrite them.

Soooooo, basically im stuck with a 14tb statehist server that has a bad statehist block i cant fix.  plz help ser :)

**Comment by heifner** [comment]
Workaround for forcing a write by loading from a snapshot and syncing or replaying. This could possibly be added as a `--ship-force-write` option.

```
diff --git a/libraries/state_history/include/eosio/state_history/log.hpp b/libraries/state_history/include/eosio/state_history/log.hpp
index 828284e21..fda9635fb 100644
--- a/libraries/state_history/include/eosio/state_history/log.hpp
+++ b/libraries/state_history/include/eosio/state_history/log.hpp
@@ -512,13 +512,7 @@ class state_history_log {
          EOS_ASSERT( block_num > 2, chain::plugin_exception, "Existing ship log with ${eb} blocks when starting from genesis block ${b}",
                      ("eb", _end_block)("b", block_num) );
          // block_num < _begin_block = pruned log, need to call truncate() to reset
-         if ( block_num < _begin_block ) {
-            truncate(block_num); //truncate is expected to always leave file pointer at the end
-         } else {
-            if (start_block_num == block_num || block_num % 1000 == 0 )
-               ilog("log ${name}.log already contains block ${b}, end block ${eb}", ("name", name)("b", block_num)("eb", _end_block));
-            return;
-         }
+         truncate(block_num); //truncate is expected to always leave file pointer at the end
       } else if (!prune_config) {
          log.seek_end(0);
       } else if (prune_config && _begin_block != _end_block) {
```

**Comment by bhazzard** [comment]
Some options to address:
- do nothing
- prevent corrupted blocklogs... somehow
- add `--ship-force-write` to nodeos as @heifner says above.
- add a `leaputils` tool to split a block log
- add a `leaputils` tool to repair a block log (example: repair block ranges 500-1000)

**Comment by bhazzard** [comment]
Closing this, since it has a workaround and we opened a different issue to track work on a longer term fix.
