### ISSUE TITLE
IF: P2P request of needed hs messages received too early or joining network

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#1597]
- `hs_vote_message` may be received before the corresponding `hs_proposal_message`
  - If determined invalid, then need a way to re-receive the message to process after the `hs_proposal_message` is received.
- When restarting a node, it will receive `hs_vote_message` that are not appropriate from its view.
  - Should node request recent/relevant hs messages on startup or on re-connect to a peer.

**Comment by bhazzard** [comment]
Depends on decisions in #1548. Should discuss after those decisions are resolved.

**Comment by arhag** [comment]
Unification of proposals with blocks means that we can take advantage of the existing re-request protocol and no new messages are needed.
