### ISSUE TITLE
Allow non privileged inline actions larger then 4KiB

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#1614]
Remove `max-non-privileged-inline-action-size` option and the associated checks in the code. Add a test.

There is a 4 KiB limit on inline action size if the sender is not a privileged account. There isn't a business need for this constraint, and it makes our EOS-EVM integration more difficult. We cannot easily change the limit because it is subjectively enforced and we need to convince the whole network to change that config option. Instead we should update the code to no longer enforce this option. 

```[tasklist]
### Tasks
```

**Comment by matthewdarwin** [comment]
Please don't have non-working configuration options.  Remove the configuration option entirely.

**Comment by arhag** [comment]
I agree. We should just remove the option.

The change should also have a test that, while respecting the max inline action depth, creates many inline actions each with a size of 512 KiB just to confirm the Leap software handles it as expected even with the `max-non-privileged-inline-action-size` constraint removed.
