### ISSUE TITLE
Revert cleos error output (display help text by default)

### ISSUE THREAD

**Issue by michaeljyeates** [AntelopeIO/leap#162]
In the early days cleos would display an error followed by the help text, now it doesnt show help and you have to type --help.  The old functionality was much better when you need to quickly show help or have to check the meaning of a missing parameter

**Comment by heifner** [comment]
@766C6164 I agree the old way was nicer.

**Comment by 766C6164** [comment]
I am working on new leap-util utility and will be revisiting cleos as well, which will get:
- "--help-all" option to display all subcommands / options / flags
- bash autocomplete, tab will autocomplete string or display possible subcommands / options / flags

I believe when user missed required subcommand or option/flag on any level and app produces error it will be very helpful indeed to show help snippet for particular subcommand. 

@michaeljyeates, @heifner  - please if you have any suggestions on best expected cli app behavior, I would really appreciate it!

**Comment by heifner** [comment]
> I believe when user missed required subcommand or option/flag on any level and app produces error it will be very helpful indeed to show help snippet for particular subcommand.

I agree showing the help for a sub-command when required args not provided would be a good thing.

**Comment by stephenpdeos** [comment]
Resolved by https://github.com/AntelopeIO/leap/pull/407
