### ISSUE TITLE
Investigate and fix throughput issues related to read only transactions and  HTTP

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#1662]
## Summary 
Initial performance testing of read only transactions indicated read-only transactions are not reaching peak throughput. This issues focuses on the C/C++ code for leap and enabling peak throughput. 

## Related Issues 
Performance testing code and the performance testing harness are covered by #1634

**Comment by heifner** [comment]
Completed by #1702, #1699, #1692, but mostly by #1685
