### ISSUE TITLE
IF : Current bls_public_key and bls_signature wire message format uses uncompressed (Jacobian) bytes

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#1678]
Considering that the cost of converting from compressed to uncompressed format is negligible compared to the bottleneck imposed by the pairing function, using the compressed format instead of Jacobian format for wire messages would provide a good trade-off, resulting in a substantial reduction of bls_public_key and bls_signature data size (3x smaller) for network messages and storage in block extensions / history solutions etc.

**Comment by heifner** [comment]
Current wire format is affine non-montgomery base64.
