### ISSUE TITLE
Prometheus exporter not working in 5.0 test build

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1681]
Set `prometheus-exporter-address = 0.0.0.0:9101`, but nodeos is not listening

![image](https://github.com/AntelopeIO/leap/assets/26171839/1afbe58f-d919-443c-8c40-57fcdf19b0b4)

Kevin says:
I see we completely ignore the prometheus-exporter-address option. It is configured via the new api category now

So question from me is, are we getting rid of this option and using some new way of doing things?

**Comment by heifner** [comment]
See https://github.com/AntelopeIO/leap/pull/1137 on how it is configured now.

**Comment by matthewdarwin** [comment]
Using the new way of doing things is working.  Suggest to remove this config option entirely.
