### ISSUE TITLE
Prometheus metrics for nodeos_p2p_connections don't use stable identifier in 5.0

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1683]
Prometheus metrics for nodeos_p2p_connections don't use stable identifier. "59" will change here:

```
nodeos_p2p_connections{connid_59="bytes_sent"} 41
nodeos_p2p_connections{connid_55="last_available_block"} 100127462
nodeos_p2p_connections{connid_55="accepting_blocks"} 1
nodeos_p2p_connections{connid_54="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid_59="last_bytes_received"} 1.695820203477813e+18
```

Better to use something like:

```
nodeos_p2p_connections{connid="8c5a970", type="bytes_sent"} 41
nodeos_p2p_connections{connid="8c5a970", type="last_available_block"} 100127462
nodeos_p2p_connections{connid="8c5a970", type="accepting_blocks"} 1
nodeos_p2p_connections{connid="8c5a970", type="name", name="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_connections{connid="8c5a970", type="last_bytes_received"} 1.695820203477813e+18
```

**Comment by matthewdarwin** [comment]
Probably a better way to structure this is to create a unique counter for each metric instead of overloading labels

```
nodeos_p2p_bytes_sent{connid="8c5a970"} 41
nodeos_p2p_last_available_block{connid="8c5a970",} 100127462
nodeos_p2p_accepting_blocks{connid="8c5a970"} 1
nodeos_p2p_name{connid="8c5a970", name="eosn-jungle4-trxrly28:9876 - 8c5a970"} 0
nodeos_p2p_last_bytes_received{connid="8c5a970"} 1.695820203477813e+18
```

Presumably last_available_block is NOT a counter since block number can decrease? (after a fork?)

**Comment by bhazzard** [comment]
> Presumably last_available_block is NOT a counter since block number can decrease? (after a fork?)

Good point @matthewdarwin. @heifner Given this, does it make sense to change last_available_block to a gauge?

**Comment by heifner** [comment]
> > Presumably last_available_block is NOT a counter since block number can decrease? (after a fork?)
> 
> Good point @matthewdarwin. @heifner Given this, does it make sense to change last_available_block to a gauge?

yes.
