### ISSUE TITLE
Disable max_action_return_value_size for read-only transactions

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#170]
`/v1/chain/compute_transaction` currently will not fail for invalid or missing signatures.
Modify processing of read-only transactions to also ignore the `max_action_return_value_size` to enable creating query like actions that can return more than the consensus limit of `max_action_return_value_size` which defaults to 256 bytes. 

The consensus level limit is to prevent abuse of transaction run time and history storage. History storage does not apply to read-only transactions as they are not stored in history. Run time limits are still important for API nodes that provide `/v1/chain/compute_transaction` endpoints but the transaction is still subject to checktime limits restricting what is possible both objectively and subjectively.

**Comment by stephenpdeos** [comment]
Blocked by #364

**Comment by stephenpdeos** [comment]
#364 is closed, so flipping this back to from more-info to discussion to review as a team

**Comment by stephenpdeos** [comment]
No changes to compute_transaction, but we won't enforce this for read-only transactions
