### ISSUE TITLE
build error: include could not find requested file:BoostRoot

### ISSUE THREAD

**Issue by astralmoonhalo** [AntelopeIO/leap#1735]
Operating system: ubuntu 22.04
Leap branch: v5.0.0-rc1 or main
Problem description: When building from source code, the following error message is prompted:
CMake Error at libraries/boost/CMakeLists.txt:20 (include):
   include could not find requested file:

     BoostRoot

**Comment by heifner** [comment]
Did you try `git submodule update --init --recursive`

**Comment by spoonincode** [comment]
If you continue to have problems let us know.
