### ISSUE TITLE
Abi serialisation seems to add an empty byte at the end of the binary

### ISSUE THREAD

**Issue by fschoell** [AntelopeIO/leap#176]
I'm currently working on adapting the eos-go library to the action results feature [here](https://github.com/eoscanada/eos-go/pull/186), but having some issues when it comes to encoding ABI files into binary. It seems like leap is appending an empty `0x00` byte at the end of the binary and I'm not sure where this comes from. See:

* [Example abi](https://gist.github.com/fschoell/955ee730a0463672ea3b3442b4280bc4#file-example-abi) I've deployed to a contract on Kylin in [this transaction](https://kylin.eosq.eosnation.io/tx/e4b315eea86bf055b8f7546cc86fca129b7bffc7a0d61a9990f1f0b51f444b71).
* The setabi transaction will report the ABI as [this](https://gist.github.com/fschoell/955ee730a0463672ea3b3442b4280bc4#file-setabi).
* Binary I'm getting from encoding the ABI into binary using eos-go is [this](https://gist.github.com/fschoell/955ee730a0463672ea3b3442b4280bc4#file-eos-go_encoded).

Note the trailing `0x00` on the setabi transaction. Decoding the binary into the readable ABI file works fine in eos-go whether the `0x00` is appended or not, so it doesn't seem to hold any data relevant for the current decoder of eos-go. 

I assume that 0x00 usually indicates an empty vector? However as the last vector in this ABI is the action_results (which is not empty), this doesn't seem like required. Is there any flag or feature we are missing in the abi serialisation here?

**Comment by heifner** [comment]
@fschoell Can you provide more information?

**Comment by fschoell** [comment]
Sorry for the delay. I think I've just found the issue, was using cleos 2.1 to deploy the contract. Looks good using 3.1

**Comment by matthewdarwin** [comment]
I'm curious as to why 2.1 cleos is weird here...

**Comment by heifner** [comment]
2.1 ABI includes `kv_tables` https://github.com/EOSIO/eos/blob/v2.1.0/libraries/chain/include/eosio/chain/abi_def.hpp#L198
