### ISSUE TITLE
Stage 6 of pinned builds takes a long time

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1760]
Stage 6 of pinned builds takes a long time.... Is it possible to cache the results of previous builds so this doesn't need to take so long on subsequent builds?

![image](https://github.com/AntelopeIO/leap/assets/26171839/ab933023-9760-46c6-8ac4-8231886f4988)

**Comment by bhazzard** [comment]
@spoonincode can you take a look and determine if you think caching is something we can & should add to 5.0.0, or if there is another approach we should look into?

**Comment by spoonincode** [comment]
fwiw this step (when completely fresh) takes sub 10 seconds on my box with the latest version of docker.

For me, with the latest version of docker, this step is properly cached. If you run the exact same docker build command a second time, you see it send the entire 2.7GB context again?

**Comment by bhazzard** [comment]
Closing as the docker does support caching.
