### ISSUE TITLE
5.0.0-rc2 release notes needs more documentaton on deferred transaction removal

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1762]
Matthew Darwin, [10/12/23 10:53 A.M.]
max-scheduled-transaction-time-per-block-ms is no longer supported?  I don't see that in release notes?

Kevin Heifner, [10/12/23 10:54 A.M.]
correct, no longer supported. scheduled trxs are not allowed in 5.0

Matthew Darwin, [10/12/23 10:56 A.M.]
So the fact the option is removed just needs to be added to the release notes. @bhazzard

Matthew Darwin, [10/12/23 10:58 A.M.]
So basically the default is 0 without having to specify it?  Upgrading to 5.0 automatically has the node stop processing deferred transactions?

Matthew Darwin, [10/12/23 10:58 A.M.]
Seems maybe a bit more docs on this would be good

Kevin Heifner, [10/12/23 10:59 A.M.]
Correct. 5.0 will expire scheduled trxs so their ram is released, but will not execute them.

Kevin Heifner, [10/12/23 11:00 A.M.]
4.0 does neither if max-scheduled-transaction-time-per-block-ms is set to 0.

Kevin Heifner, [10/12/23 11:00 A.M.]
So RAM is not released in 4.0 if all BPs have max-scheduled-transaction-time-per-block-ms set to 0 unless the contracts explicitly cancel the scheduled trx.

Kevin Heifner, [10/12/23 11:02 A.M.]
The protocol features when enabled means that blocks will no longer be valid with deferred trxs. Until the protocol features are activated a 5.0 node will still validate a block with deferred trxs in it.

**Comment by bhazzard** [comment]
Thank you for the issue report.

Updated documentation on the release notes: https://github.com/AntelopeIO/leap/releases/tag/v5.0.0-rc2

and on the upgrade guide: https://github.com/AntelopeIO/leap/wiki/Leap-5.0-Upgrade-Guide
