### ISSUE TITLE
Chainbase performance improvement

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#1771]
This change should lower disk io for the state db in `mapped` mode (and also in new `mapped_private` mode in low memory conditions).

Change is trivial and carries no risk.

**Comment by greg7mdp** [comment]
Hi @bhazzard , can you tag with `lgtm` and target to 5.0 please. 
It is a trivial, no risk change and the PR is already approved to merge.

**Comment by BenjaminGormanPMP** [comment]
Moved to iteration per approval discussion with @ericpassmore and @greg7mdp.
