### ISSUE TITLE
5.0: lots of "not producing block" messages on the backup BP

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1837]
With 5.0 (latest), we get a lot of "not producing block" messages on the backup BP.  The backup BP has the wrong key on purpose.

In previous version we just get 1 of these per block.

```
$ grep 'Block #105321099 eosnationftw' /var/log/syslog | wc -l
763
```

![image](https://github.com/AntelopeIO/leap/assets/26171839/b3b80a4e-27b4-4237-bf06-de536e6f54d2)

**Comment by heifner** [comment]
Related #1481

**Comment by heifner** [comment]
@matthewdarwin reported still seeing this issue with the associated PR.
