### ISSUE TITLE
3.1 many http log entries for STD exception for get_account

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#186]
Lots of log errors like `http_plugin.cpp:950 handle_exception  ] STD Exception encountered while processing chain.get_account`. 

```
debug 2022-09-19T13:22:50.826 nodeos    http_plugin.cpp:951           handle_exception     ] Exception Details: unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 )
```

**Comment by gituser** [comment]
if node isn't synced and you try to query/send tx from non-existent account cleos will hang for a moment and then raise an error:

```
eos@eos:~$ ./cleos get account accountxxx

error 2022-09-20T13:08:04.702 cleos     main.cpp:4121                 operator()           ] Failed with error: unspecified (0)
unknown key (boost::tuples::tuple<bool, eosio::chain::name, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type, boost::tuples::null_type>): (0 accountxxx)
```

**Comment by heifner** [comment]
Options for `http_plugin` logging:
1. Catch `std::out_of_range` and handle with debug logging. Leave `std::exception` logging the same. This is the exception type thrown by chainbase `get` not finding the account.
2. Change `std::exception` logging to be `debug` instead of `error` level.
3. Add `if` for `chain/get_account` and use `debug` log for it instead of `error`.

**Comment by stephenpdeos** [comment]
🏆 2
