### ISSUE TITLE
log non-default options one per line

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#1861]
When nodeos starts it logs all the non-default options on a long line.
If you have changed a lot of options or added a lot of p2p-peer-address then the log line is very long.

Better to log one option per line.
Better to NOT log any `p2p-addrses` or `peer-key`?  The default is empty, so adding anything always generates a log entry.

Example:
```
Non-default options: config-dir = /etc/nodeos, data-dir = /var/lib/nodeos, snapshot = /var/lib/nodeos/snapshots/snapshot.bin, wasm-runtime = eos-vm-jit, chain-state-db-size-mb = 36864, http-max-response-time-ms = 300, p2p-dedup-cache-expire-time-sec = 20, subjective-account-max-failures = 3, subjective-account-max-failures-window-size = 2, disable-subjective-p2p-billing = false, disable-subjective-api-billing = false, ....
```

**Comment by bhazzard** [comment]
Notes from discussion on November 15, 2023 Antelope Node Operator's Roundtable:
- Rationale for line delimited: more easily grepable
- Rationale for all on one line: this is helpful debug info, and it is more likely to be included in a paste of log lines if it is all on one line.
