### ISSUE TITLE
`cleos set code`/`cleos set abi` don't appear to work

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#1868]
`cleos set code` and `cleos set abi` don't seem to work on main, and I'm suspicious they haven't worked in a long time.

The problem is `contractPath` is empty here when doing `set code` or `set abi` and, at least on main, this causes `std::filesystem::canonical()` to throw
https://github.com/AntelopeIO/leap/blob/161265052b10265da3ad3455606053b3e238268a/programs/cleos/main.cpp#L3474

This looks to be a straightforward fix; adding a test will take longer than the fix itself.

**Comment by bhazzard** [comment]
We need to verify that this was broken prior to 5.0.

**Comment by linh2931** [comment]
I am able to reproduce this problem in `3.2`. Will fix  it `in 3.2` and merge the fix to `4.0`, `5.0`, and `main`.

Will create an integration test in `5.0` and `main`.
