### ISSUE TITLE
5.0 cleos cannot handle reponses from pre-5.0 nodes containing base64 (and vice versa I believe)

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#1883]
There appears to be an incompatibility introduced with #1482 where a 5.0 cleos is unable to decode base64 responses from a pre-5.0 nodeos containing the invalid `=` postfix. I believe this might also might be broken in the other direction too (a pre-5.0 cleos being unable to decode a 5.0 response).

The easiest way to reproduce the problem is via `cleos get code eosio.token` on EOS mainnet; it currently exhibits the problem.

**Comment by bhazzard** [comment]
Create backport patches applying #1482 to 3.2, and 4.0.

Ensure this underlying code doesn't impact consensus (we believe its caused by an issue with line 493 of fc::variant)
