### ISSUE TITLE
Prevent requesting blocks while SHIP starts from snapshot

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/leap#191]
If a node on a large blockchain starts from a snapshot, it takes a while for `state_history_plugin` to create and write the first frame of history. During that time, the `net_plugin` tries to request a block range, but it can't apply it, so it keeps requesting the same block range until state history is fully initialized.

**Comment by stephenpdeos** [comment]
Verify if still an issue in 3.2

**Comment by heifner** [comment]
Still an issue in 3.2 & main.
