### ISSUE TITLE
Ship v4.0.4wax01/02 only syncs at 2 blocks per second (Chronicle + Atomic API)

### ISSUE THREAD

**Issue by hiveben** [AntelopeIO/leap#1914]
Hi, I recently updated my Ship Node from v3.2.4 to v4.0.4(wax02), and noticed that syncing slowed down significantly afterwards. I'm using chronicle and noticed that the reader slowed down to ~ 2 blocks per second:

![Screenshot from 2023-11-17 08-38-02](https://github.com/AntelopeIO/leap/assets/86235955/c930392b-c154-4a90-b44e-75a15cfe0f45)

Another user is syncing an Atomic API with a ship v4.0.4wax01, and is experiencing a similar issue:
![photo_2023-11-17_07-10-55](https://github.com/AntelopeIO/leap/assets/86235955/0eb0cee0-3fca-4817-8d4b-5232b94cc718)

This leads me to think that it's a version issue. Is there any known setting that might be causing this or could this be a bug?

Thank you

**Comment by heifner** [comment]
There have been some SHiP fixes in `release/4.0` unreleased `4.0.5` that may address this issue.

**Comment by bhazzard** [comment]
@hiveben We expect to release 4.0.5 next week. Once we do can you give it a try to see if it resolves your issue?

**Comment by hiveben** [comment]
> @hiveben We expect to release 4.0.5 next week. Once we do can you give it a try to see if it resolves your issue?

It was just ported to WAX and it seems to have solved the issue. thank you!

**Comment by hiveben** [comment]
> @hiveben We expect to release 4.0.5 next week. Once we do can you give it a try to see if it resolves your issue?

It was just ported to WAX and it seems to have solved the issue. thank you!
