### ISSUE TITLE
CI/CD: Update compiler used for libtester tests in CI/CD (or use Ubuntu 22.04) so that C++20 support is consistent with Leap's

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#1936]
In Leap's readme, we state:

On Ubuntu 20.04, install gcc-10 which has C++20 support:

`sudo apt-get install -y g++-10`

Leap does not build with the default g++ compiler on Ubuntu 20.04.

**Comment by bhazzard** [comment]
@spoonincode This seems like a straightforward change to include in 6.0.0. Do you agree?

**Comment by bhazzard** [comment]
Note to self: The change will be made to the CICD workflow on 5+
