### ISSUE TITLE
`larger_lib_test` test failure

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#1970]
Don't recall ever seeing an issue with this test before so a bit surprising.

https://github.com/AntelopeIO/leap/actions/runs/7132387412/job/19423267255

**Comment by bhazzard** [comment]
Let's do a quick look on this to determine if there is a more serious issue at play that needs to be fixed prior to 5.0.0 stable.

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/leap/actions/runs/7213305978/job/19653335121

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/leap/actions/runs/7477546239/job/20350978144?pr=2067#step:4:592

**Comment by arhag** [comment]
This test should just be removed. That is covered by https://github.com/AntelopeIO/leap/issues/2232.
