### ISSUE TITLE
leap-4.0.5: non-informative "Connection refused" message for p2p connections

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/leap#1974]
4.0.5 and earlier Leap versions.

If a p2p neighbor host exists, but refuses a connection, nodeos logs an error that is difficult to troubleshoot:

```
error 2023-12-10T20:18:48.407 net-1     net_plugin.cpp:2360           operator()           ] connection failed to 0.0.0.0:0 Connection refused
```

The error message needs to provide the host and port information.

**Comment by bhazzard** [comment]
@heifner this looks like it would be a simple enhancement to include in 6.0.0. Do you agree it doesn't need backporting?
