### ISSUE TITLE
When setting block-log-retain-blocks = 0 get lots of unlinkable blocks errors

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#2006]
In 5.0.0-rc3, when setting `block-log-retain-blocks = 0` get lots of unlinkable blocks errors.  This worked fine in 3.2.  Not tested in 4.0

Easy to reproduce on a heavy blockchain like wax, when starting from a snapshot. Seen on other lighter chains as well, even when starting from up-to-date.

**Comment by heifner** [comment]
Reproduced on eos mainnet by starting from a June snapshot.

**Comment by heifner** [comment]
Not reproducible on 4.0 during my testing.
