### ISSUE TITLE
When taking a snapshot RAM usage increases significantly on 5.0.0-rc3 WAX

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#2021]
When taking a snapshot RAM usage increases significantly on 5.0.0-rc3.  Screenshot is from WAX, starting at ~23:10.  snapshot is started from producer plugin when the blockchain is up-to-date.  Previous snapshots (earlier in the screenshot) were taken while the chain was not up-to-date and we didn't see the same problem.

![image](https://github.com/AntelopeIO/leap/assets/26171839/a9d40712-979f-45e6-9b0e-7ec21fdc60cd)

Seems 5.0.0 behaviour is different than earlier versions: https://github.com/AntelopeIO/leap/issues/1128

Note also high CPU usage.

**Comment by matthewdarwin** [comment]
Going back to nodeos 4.0.x, the problem doesn't happen.  (switch happened at 14:00 in below chart)

![image](https://github.com/AntelopeIO/leap/assets/26171839/dc0aa3dd-142d-4027-a6c0-bd8f52e1a6a8)

**Comment by heifner** [comment]
@matthewdarwin can you provide the 5.0 logs for high ram usage indicated in the graph.

**Comment by matthewdarwin** [comment]
Yes, I will send privately.
