### ISSUE TITLE
Faster snapshots fix performance regression 

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#2027]
Feedback from node producers, and internal benchmarks showed snapshots with pinned builds ran several times slower. 5x slower. This was not the case in Leap 4.x. Investigate and address the amount of time to take a snapshot in Leap 5.0.0.

**Comment by ericpassmore** [comment]
closing resolved by PR #2026

**Comment by greg7mdp** [comment]
I think the issue was likely present in 4.0 as well when building with libc++ (and maybe even prior).

**Comment by ericpassmore** [comment]
> I think the issue was likely present in 4.0 as well when building with libc++ (and maybe even prior).

Good point, let me keep the issue open. We can close it later after we decide all the release branches we want to update.
