### ISSUE TITLE
IF: use the same way to determine if instant finality is active

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#2028]
https://github.com/AntelopeIO/leap/pull/2024/files#r1440617405

The presence of `instant_finality_extension` should be used as an indication of instant finality activated. But doing that fails unit test producer_schedule_hs_tests/verify_producer_schedule_after_hotstuff_activation with

```
3030000 block_validate_exception: Block exception
invalid block transaction merkle root 0cb3d1d90b7b4d61b7db5cb3730bee81f98d339cc1ac5fb0c1b50ddc12e9e108 != b26dc703930e4f88b4dffa3a24af3a580009ffaa83a8d50e4bdbc397db729d8f
    {"b":"0cb3d1d90b7b4d61b7db5cb3730bee81f98d339cc1ac5fb0c1b50ddc12e9e108","c":"b26dc703930e4f88b4dffa3a24af3a580009ffaa83a8d50e4bdbc397db729d8f"}
    chain-1  controller.cpp:2226 create_block_state_i
rethrow
```

Additional work is required for the transition from DPOS to Instant Finality.

**Comment by ericpassmore** [comment]
Note:start
group: IF
category: INTERNALS
summary: Unified implementation to detect activation of new faster finality. 
Note:end
