### ISSUE TITLE
near double memory usage when starting from a snapshot with state history plugin enabled

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#203]
When starting a node from a snapshot with state history plugin enabled nodeos memory usage peaks at nearly 2x the size of the state. e.g. if the snapshot has 100GB worth of state, nodeos memory usage peaks at nearly 200GB during loading of the snapshot once state history plugin begins to write the initial block's deltas.

I suspect, but have not confirmed, that high memory usage will also occur any time a ship client requests that first block because I believe the culprit here is state history plugin buffering entire ship log contents in memory during read/write & de/compression.

This is an absolute brutal usability killer for something like WAX where it balloons the memory requirement from ~100GB to ~200GB (you can of course suffer through it with a lot of swap or something). I've seen a number of users ensnared by this even for EOS since it required them to move from a 32GB configuration to a 64GB configuration.

Looking at the code, a cursory look suggests it may not be too hard to modify it to stream the data to/from disk without buffering everything in memory first. Care must be taken around block log pruning to "pin" blocks that are in the middle of being streamed out.

**Comment by 1921Aaron** [comment]
> When starting a node from a snapshot with state history plugin enabled nodeos memory usage peaks at nearly 2x the size of the state. e.g. if the snapshot has 100GB worth of state, nodeos memory usage peaks at nearly 200GB during loading of the snapshot once state history plugin begins to write the initial block's deltas.
> 
> I suspect, but have not confirmed, that high memory usage will also occur any time a ship client requests that first block because I believe the culprit here is state history plugin buffering entire ship log contents in memory during read/write & de/compression.
> 
> This is an absolute brutal usability killer for something like WAX where it balloons the memory requirement from ~100GB to ~200GB (you can of course suffer through it with a lot of swap or something). I've seen a number of users ensnared by this even for EOS since it required them to move from a 32GB configuration to a 64GB configuration.
> 
> Looking at the code, a cursory look suggests it may not be too hard to modify it to stream the data to/from disk without buffering everything in memory first. Care must be taken around block log pruning to "pin" blocks that are in the middle of being streamed out.

How do you start the historical status node from a snapshot?

**Comment by spoonincode** [comment]
fixed via #628
