### ISSUE TITLE
IF: Unification: Changes in controller to complete unification

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#2034]
Finish data structures in `building_block` and the `block_header_state_input` needed to transition to `assembled_block`. Prioritize this first as the first PR.

Then complete changes to the following in controller to work post-IF transition, including (but not necessarily limited to):
* building_block, assembled_block, completed_block structures
* apply_block function
* push_block function

**Comment by greg7mdp** [comment]
Resolved with #2077
