### ISSUE TITLE
investigate if there is any way to speed up snapshot loading

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#2051]
Investigate if there is any way to speed up snapshot loading.  On wax 5.0.0 pinned build it takes less than 3 minutes to create a snapshot but takes more than 10 minutes to load it back.

**Comment by bhazzard** [comment]
Closing, I don't think we need an issue to track the desire to speed up snapshot loading. Performance is always top of mind. If a specific improvement opportunity presents itself, we'll track that issue instead.
