### ISSUE TITLE
eosio_assert_message assertion failure

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2059]
when I'm trying to create an account using wharfkit/antelope library, I get the following response from the transaction broadcast.

```
{
  transaction_id: '41e2edec3278acba808ee6d9b761786be3862af336dc17f6732319ec893d2a01',
  processed: {
    id: '41e2edec3278acba808ee6d9b761786be3862af336dc17f6732319ec893d2a01',
    block_num: 351244143,
    block_time: '2024-01-09T15:44:49.000',
    producer_block_id: null,
    receipt: null,
    elapsed: 403,
    net_usage: 165,
    scheduled: false,
    action_traces: [ [Object], [Object] ],
    account_ram_delta: null,
    except: {
      code: 3050003,
      name: 'eosio_assert_message_exception',
      message: 'eosio_assert_message assertion failure',
      stack: [Array]
    },
    error_code: '10000000000000000000'
  }
}
```

I can't figure out what's the problem. I'm using an account with R1 public/private key.

I can send money transactions successfully, but account creation fails like this.

following shows how I create new account action:

```
contract.action(
    "newaccount",
    {
      creator: creatorUsername,
      name: newAccountName,
      owner: {
        threshold: 1,
        keys: [
          {
            key: publicKey,
            weight: 1,
          },
        ],
        accounts: [],
        waits: [],
      },
      active: {
        threshold: 1,
        keys: [
          {
            key: publicKey,
            weight: 1,
          },
        ],
        accounts: [],
        waits: [],
      },
    },
    {
      authorization: [
        {
          actor: creatorUsername,
          permission: "owner",
        },
      ],
    },
  );
```

and the following shows how I create buy ram action

```
contract.action(
    "buyrambytes",
    {
      payer: payerUsername,
      receiver: receiverUsername,
      bytes: ramBytes,
    },
    {
      authorization: [
        {
          actor: payerUsername,
          permission: "owner",
        },
      ],
    },
  );
```

the contract here is coming from `import { Contract } from '@wharfkit/contract';`

**Comment by bhazzard** [comment]
Is it possible to reproduce but get the expanded output including the stack for that eosio_assert_message_exception?

**Comment by dev-dantealighieri** [comment]
I have enough ram, my account name, and destination is correct. I am trying to send some money actually, I have enough cpu and net resources, I have rented them. but still got this error, and can't figure out how to solve it.

**Comment by matthewdarwin** [comment]
Better to ask questions in telegram channels rather than here. https://t.me/antelopedevs

**Comment by heifner** [comment]
@dev-dantealighieri I believe your issue was resolved on telegram.

**Comment by dev-dantealighieri** [comment]
First of all, I couldn't find a resolved answer to my problem in your telegram, if i'm missing something, can you please show me?

if i switch to an account with `K1` private keys, without changing any part of the transaction (only creator username and private key changes), i can create both r1 and k1 accounts(new accounts) (still sometimes i get errors but i dont mind that now, sending transaction again usually works.)

What is the problem here? how can i solve it, can i create new accounts using r1 key as creator? i appreciate your time and answers,

have a good day

**Comment by heifner** [comment]
Sorry, someone asked a similar question on telegram, I assumed it was you.

**Comment by spoonincode** [comment]
@dev-dantealighieri is this still an issue for you?

**Comment by dev-dantealighieri** [comment]
no thanks, suddenly it started working, i dunno why!
