### ISSUE TITLE
What is the alternative API  for this  /v1/chain/abi_json_to_bin api ？

### ISSUE THREAD

**Issue by saf111r** [AntelopeIO/leap#2065]
Because this API has been deleted, but we need to use this API when transferring. What API can be used to replace this  now?
<img width="877" alt="image" src="https://github.com/AntelopeIO/leap/assets/26398705/95158c73-17eb-4517-af33-6b518f1dda6b">
Or how can implement the api with java in my local client？

**Comment by bhazzard** [comment]
The most actively maintained option is WharfKit, javascript libraries by the Greymass team: https://wharfkit.com. If all you are doing is sending transfers, you can probably just use their "session kit" and you're good to go. If you  need to work with the ABIs, you might want to take a look at "Retrieving an ABI Using an APIClient" https://wharfkit.com/docs/antelope/abi. I leave it to you to determine the best way to interface with javascript libraries from your local java client.

There are other options with less certain support:
- Our own swift library, which has no recent updates: https://github.com/eosnetworkfoundation/mandel-swift
- A third-party java sdk from a community member: https://github.com/mcicu/antelope-java-sdk
