### ISSUE TITLE
IF: Guarantee net_plugin processes votes after it has has processed the block the vote was for

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#2102]
The net_plugin will be responsible for respecting this order per connection. It can leverage the existing cache of block IDs received and sent per connection to know when it is the appropriate time to process the votes per each connection.

We also need to make sure we process the block (add to fork database) before we process the votes for that block, otherwise they will be dropped.

**Comment by heifner** [comment]
- Already guaranteed for produced blocks.
  - `accepted_block_header` emitted before `voted_block` is emitted. `net_plugin` posts both of those to dispatcher strand which enforces order.

**Comment by heifner** [comment]
- 3000 `vote_message` (size 32+1+96+192) is less than 1MB.
  - Limit to 3000 votes per connection, drop incoming votes if > 3000
  - Maintain count per connection for quick check
- Purge votes on LIB (index by block_num)
- Active thread pool for processing
  - We know we don't want to use net threads
  - Chain threads would compete with trx signature verification. Don't want trx sig verification slowing down votes.
  - New thread pool (vote processing)
    - `--vote-threads` default to 2
  - `vote_processor` in chain library

```c++
   atomic<uint32_t> latest_block_num;
   atomic<uint32_t> lib;
   set_lib(lib) { lib = lib; notify_one(); }
   add_vote( v ) { append(v); latest_block_num = std::max(latest_block_num, v.block_num); notify_one(); }

   each thread:
      while (true) {
         _cond.wait([]() {
            if (stopped || !empty) return true;
         }
         if (stopped) break;
         remove_votes_before_lib();
         uint32_t block_num = latest_block_num;
         block_state_ptr bsp = forkdb.get(block_num);
         for each connection by latency {
            if( block_num != latest_block_num) {
               block_num = latest_block_num;
               bsp = forkdb.get(block_num);
            }
            process_votes_for_block(conn_id, bsp);
            block_num = idx.get_latest_block_num();
         }
      }

   process_votes_for_block(conn_id, bsp) {
      for bsp->finalizer_size():
         process_vote(conn_id, bsp);
   }
```

**Comment by greg7mdp** [comment]
Are two threads enough? If each verify takes 2ms, this means that processing the 20 votes received would take a minimum of 20ms. Maybe that's OK, but I think 4 threads might be better.

**Comment by linh2931** [comment]
What's `idx` in `block_num = idx.get_latest_block_num();`?

You would always process latest block's votes first? Where do you remove the vote after it is processed?

**Comment by heifner** [comment]
> What's `idx` in `block_num = idx.get_latest_block_num();`?

The multi-index where one of the indexes is on block_num.

> You would always process latest block's votes first? Where do you remove the vote after it is processed?

In process_vote.
```c++
   void process_vote(conn_id, bsp) {
      auto itr = idx.find(conn_id, bsp->block_num())
      if (itr != idx.end(); auto vote = *itr) {
         vote_status s = bsp->aggregate_vote(vote);
         idx.remove(itr);
         --c->vote_count;
         return s;
      }
   }
```

**Comment by greg7mdp** [comment]
- accesses to the multi-index need to be protected by a mutex
- that mutex should be released in `process_vote` around `bsp->aggregate_vote(vote);`
- maybe we should track of when `lib` changes  so that we don't do any work in `remove_votes_before_lib();` if lib didn't change - could be a `thread_local` variable.
- should we use `block_id` instead of `block_num`?
- why is `if( block_num != latest_block_num) { ... }` in the `for each connection` loop?
- when we do `bsp = forkdb.get(block_num);` what do we do if the block is not found? Probably should process votes for older blocks if these are in fork_db.

**Comment by heifner** [comment]
> * why is `if( block_num != latest_block_num) { ... }` in the `for each connection` loop?

Because it could change at any time, so check it periodically to see if we need to move to a different block.
