### ISSUE TITLE
Default read-only-threads could be clearer in the help

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#2103]
The default number of read-only-threads could be clearer in the help

```
# Number of worker threads in read-only execution thread pool. Max 8. (eosio::producer_plugin)
# read-only-threads =
```

https://github.com/AntelopeIO/leap/blob/4531e9751a8d6d712801ffab1e2b24fe37dc9ca8/plugins/chain_plugin/chain_plugin.cpp#L2544

**Comment by bhazzard** [comment]
Need to document in the help that the default value of `read-only-threads` is 3.
