### ISSUE TITLE
what happens if transaction fails before block gets irreversable

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2108]
what i wonder is, when I transferred money, or staked ram/cpu/net, or bought powerup model for cpu and net, and the transaction fails before its irreversable, but i spend some of the cpu, or eos before cancellation of the transaction, what happens?

**Comment by heifner** [comment]
When a micro-fork happens transactions are gathered out of the forked chain and re-applied on top of the new chain. As those transactions are re-applied on the new chain they will fail or succeed according to the current state as they are re-applied.
