### ISSUE TITLE
IF: Remove chain_pacemaker and qc_chain related files and code

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#2123]
`chain_pacemaker.(hpp/cpp)` and `qc_chain.(hpp/cpp)` are no longer needed. Remove them to save maintenance.

~~Ensure tests using `qc_chain` and `chain_pacemaker` have been ported to work with the new implementation.~~

As it is a significant work to port the large number of the tests, https://github.com/AntelopeIO/leap/issues/2147 is created to track the work.

**Comment by arhag** [comment]
Also avoid using `hotstuff` in the code. And prefer using just `finality` rather than `instant_finality` if possible.
