### ISSUE TITLE
testnet installation

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2130]
hi,

how can i create a testnet node? i couldn't find any information in your repository, and jungle testnet seems old to me, do you have any suggestions?

thanks, dante

**Comment by heifner** [comment]
If you are interested in running a Jungle testnet node, ask them on telegram: https://t.me/jungletestnet
The Jungle testnet is actively maintained. You can find out more here: https://jungletestnet.io/
There is also the Kylin testnet: https://t.me/cryptokylin1en
The Kylin testnet is also actively maintained. You can find our more here: https://www.cryptokylin.io/
