### ISSUE TITLE
staking in eos

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2150]
i couldnt find a solid information about staking in eos on the internet, some people say you dont earn anything, some says you get when you stake and vote for block producers, can you explain staking in eos, can we earn money buy doing this?

**Comment by matthewdarwin** [comment]
Asking questions about how various blockchains work is out of scope for leap software development.  Suggest take your question to https://t.me/EOSproject

**Comment by spoonincode** [comment]
Agree with @matthewdarwin, for this type of question I'd suggest either
* **ENF Discord** - https://discord.gg/eos-network
* **ENF Telegram** - https://t.me/EOS_Global
* **EOS Community Telegram** - https://t.me/EOSproject
