### ISSUE TITLE
IF: Modify the action_receipt digest to be computed by concatenating and hashing a pair constructed from act_digest and the rest of the values of the action_receipt

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#2161]
Depends on https://github.com/AntelopeIO/leap/issues/2162.

This allows for a smaller proof footprint, and faster verification by smart contracts and light clients.

https://github.com/AntelopeIO/leap/blob/hotstuff_integration/libraries/chain/include/eosio/chain/action_receipt.hpp#L19

**Comment by arhag** [comment]
Should this be a concatenation of three digests:
1. A 32-byte digest that simply captures the `recv_sequence`. (Done this way to maximize compatibility with serialization support in other blockchain contract scripts?)
2. The `act_digest`.
3. A 32-byte digest committing to the rest of the information in the `action_receipt` that wasn't already committed to by the above two fields.

**Comment by greg7mdp** [comment]
Should the digest change unconditionally, or be triggered when something happens?
