### ISSUE TITLE
IF: Add the activation of WTMSIG_BLOCK_SIGNATURES  and ACTION_RETURN_VALUE features as prerequisite for the activation of the instant_finality feature

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#2162]
`INSTANT_FINALITY` should have prerequisite:
- `ACTION_RETURN_VALUE` is desired so that the IBC contract can use it. Also it changes the algorithm for digest computation and don't want IBC to have to handle both ways.
- `WTMSIG_BLOCK_SIGNATURES` Changes the algorithm for digest computation and don't want the IBC to handle both ways. Also we do not need to check if `WTMSIG_BLOCK_SIGNATURES` is activated in `block_header_state::next`.
- `DISALLOW_EMPTY_PRODUCER_SCHEDULE` Using the same `set_proposed_producers` which checks this protocol feature. We do not want empty proposer schedules.

**Comment by heifner** [comment]
I wonder if it is useful to draw a line in the sand and make `INSTANT_FINALITY` depend on all previous protocol features. Going forward all new protocol features could depend on `INSTANT_FINALITY`. If we ever mint a new genesis we could clean up all the existing protocol feature differences.

**Comment by greg7mdp** [comment]
Should we also make `INSTANT_FINALITY` depend on `BLS_PRIMITIVES2` and `WEBAUTHN_KEY` which I believe are required for the BIOS contract?
