### ISSUE TITLE
eosio.token

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2181]
hello,

can any other token except than `EOS` be transferred through `eosio.token` contract, as far as I can see it's used only and only for `EOS` transfer but I want to be sure.

thanks, Dante

**Comment by spoonincode** [comment]
@dev-dantealighieri if that doesn't answer your question feel free to follow up

**Comment by dev-dantealighieri** [comment]
no i got my answer, thanks
