### ISSUE TITLE
IF: add more flexibility for IF transition to Boost libtester

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#2193]
Currently `set_finalizers` of libtester takes only a vector of producer names for IF transision. `set_finalizer` hardcodes the threshold and weights for each producer and sets up all producers to vote in the node.

To facilitate more complex tests, `set_finalizer`  or another function like `transition_to_if` should take threshold, weights, and voting producers as parameters to set up IF testing.

Tests using the new function will be added in the same PR resolving the issue.

**Comment by arhag** [comment]
Libtester should have functionality to allow for tests with explicit control of votes: who votes, how they vote (strong/weak), where the votes arrive (which nodes or instances of libtester), and when the votes arrive.

**Comment by linh2931** [comment]
Manipulating finalizer safety info is now in https://github.com/AntelopeIO/leap/issues/2233.

**Comment by greg7mdp** [comment]
weak vote tests are not passing and were disabled. Reopening until these tests can be re-enabled.
