### ISSUE TITLE
how to get actions instead of whole trace

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2195]
i want to get only the actions created by the creator of the transaction but history api returns whole transaction to me, 

im using the following code snippet to get the transaction
```typescript
const transaction = await this.indexerRequest(
      EOS_INDEXER_API.V2.GET_TRANSACTION,
      {
        params: {
          id: transactionHash,
        },
        method: GET_METHOD,
      },
    );
```

[example transaction](https://bloks.io/transaction/3eae5fe9d49302fcc60957e1164510d1e47c4ed2922f5d859f71ca5607c7fd02)

for example in here, i want to only filter the following actions, not traces, which are
<img width="859" alt="image" src="https://github.com/eosrio/hyperion-history-api/assets/156019107/e537d4b3-99f8-4e9a-a9e5-592c9e87d811">

how to filter correctly? i tried to use creator_action_ordinal but thats not what i was looking for

thanks, Dante

**Comment by spoonincode** [comment]
Is this a Hyperion query? I'd suggest asking the Hyperion team instead

**Comment by dev-dantealighieri** [comment]
i asked them but couldn't get an answer.
