### ISSUE TITLE
Snapshot Scheduling Broken in 5.0.x

### ISSUE THREAD

**Issue by CryptoBloks** [AntelopeIO/leap#2261]
Recently upgraded from 4.0.5 to 5.0.2.  After upgrade, the snapshot schedule is cleared (snapshot-schedule.json is cleared) on startup.

When attempting to schedule a snapshot from the API, a response is received indicating a schedule was set, but the snapshot-schedule.json is not updated, and attempts to retrieve the schedule via the API fail to return a scheduled snapshot.

Attempts to restore the snapshot-schedule.json manual result in the file being overwritten on startup.

@spoonincode indicated he was able to reproduce in Antelope Node Operators Round Table chat.

**Comment by spoonincode** [comment]
Thanks for reporting this; it'll be fixed in Leap 5.0.3 (and Spring 1.0.0)
