### ISSUE TITLE
IF: Test failure: api_unit_test_eos-vm-jit/votes_greater_than_threshold_test

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#2267]
https://github.com/AntelopeIO/leap/actions/runs/8067228594/job/22037649219#step:5:4242

`/__w/leap/leap/unittests/api_tests.cpp(3958): error: in "api_tests/votes_greater_than_threshold_test": check lib > lib_after_transition has failed [6 <= 6]`

**Comment by arhag** [comment]
Closing in favor of https://github.com/AntelopeIO/leap/issues/2289.
