### ISSUE TITLE
Cannot build with Docker

### ISSUE THREAD

**Issue by kolkre** [AntelopeIO/leap#2268]
Hello, I wanted to build Leap with Docker on a Windows machine, but I encountered this error:

`
reproducible.Dockerfile:52
ERROR: failed to solve: process "/bin/sh -c ls *.sig *.asc | xargs -n 1 gpg --verify &&     sha256sum -c --ignore-missing cmake-*-SHA-256.txt" did not complete successfully: exit code: 123
`

Is it even possible to build it on Windows through Docker?

**Comment by spoonincode** [comment]
Can you provide more of the log output? You may need to run with `--progress=plain`  (`docker build --progress=plain ...`)

**Comment by kolkre** [comment]
> Can you provide more of the log output? You may need to run with `--progress=plain` (`docker build --progress=plain ...`)

Hey! Here's the error log from GPG verify command:
`0.336 gpg: assuming signed data in 'cmake-3.27.6-SHA-256.txt'
0.338 gpg: Signature made Wed Sep 20 15:04:39 2023 UTC
0.338 gpg:                using RSA key C6C265324BBEBDC350B513D02D2CEF1034921684
0.343 gpg: Good signature from "Brad King" [unknown]
0.343 gpg:                 aka "Brad King <brad.king@kitware.com>" [unknown]
0.343 gpg:                 aka "[jpeg image of size 4005]" [unknown]
0.344 gpg: WARNING: This key is not certified with a trusted signature!
0.344 gpg:          There is no indication that the signature belongs to the owner.
0.344 Primary key fingerprint: CBA2 3971 357C 2E65 90D9  EFD3 EC8F EF3A 7BFB 4EDA
0.344      Subkey fingerprint: C6C2 6532 4BBE BDC3 50B5  13D0 2D2C EF10 3492 1684
0.345 gpg: assuming signed data in 'llvm-project-11.1.0.src.tar.xz'
0.631 gpg: Signature made Wed Feb 17 05:17:58 2021 UTC
0.631 gpg:                using RSA key 474E22316ABF4785A88C6E8EA2C794A986419D8A
0.632 gpg: BAD signature from "Tom Stellard <tstellar@redhat.com>" [unknown]
0.633 gpg: assuming signed data in 'llvm-project-17.0.2.src.tar.xz'
1.067 gpg: Signature made Tue Oct  3 06:47:20 2023 UTC
1.067 gpg:                using RSA key D574BD5D1D0E98895E3BF90044F2485E45D59042
1.067 gpg: BAD signature from "Tobias Hieta <tobias@hieta.se>" [unknown]`

**Comment by spoonincode** [comment]
```
gpg: assuming signed data in 'llvm-project-11.1.0.src.tar.xz'
gpg: Signature made Wed Feb 17 05:17:58 2021 UTC
gpg:                using RSA key 474E22316ABF4785A88C6E8EA2C794A986419D8A
gpg: BAD signature from "Tom Stellard <tstellar@redhat.com>" [unknown]

gpg: assuming signed data in 'llvm-project-17.0.2.src.tar.xz'
gpg: Signature made Tue Oct  3 06:47:20 2023 UTC
gpg:                using RSA key D574BD5D1D0E98895E3BF90044F2485E45D59042
gpg: BAD signature from "Tobias Hieta <tobias@hieta.se>" [unknown]
```

Those errors suggest some sort of failure or corruption when downloading,
https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/llvm-project-17.0.2.src.tar.xz
and
https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-project-11.1.0.src.tar.xz

I just tried downloading these files manually and verifying the signature and everything worked correctly. fwiw,
```
$ sha256sum llvm-project-17.0.2.src.tar.xz llvm-project-11.1.0.src.tar.xz
351562b14d42fcefcbf00cc1f327680a1062bbbf67a1e1ca6acb64c473b06394  llvm-project-17.0.2.src.tar.xz
74d2529159fd118c3eac6f90107b5611bccc6f647fdea104024183e8d5e25831  llvm-project-11.1.0.src.tar.xz
```

You could try using `--no-cache` (`docker build --no-cache ...`) to see if maybe something corrupted got wedged in your docker build cache.

**Comment by kolkre** [comment]
> ```
> gpg: assuming signed data in 'llvm-project-11.1.0.src.tar.xz'
> gpg: Signature made Wed Feb 17 05:17:58 2021 UTC
> gpg:                using RSA key 474E22316ABF4785A88C6E8EA2C794A986419D8A
> gpg: BAD signature from "Tom Stellard <tstellar@redhat.com>" [unknown]
> 
> gpg: assuming signed data in 'llvm-project-17.0.2.src.tar.xz'
> gpg: Signature made Tue Oct  3 06:47:20 2023 UTC
> gpg:                using RSA key D574BD5D1D0E98895E3BF90044F2485E45D59042
> gpg: BAD signature from "Tobias Hieta <tobias@hieta.se>" [unknown]
> ```
> 
> Those errors suggest some sort of failure or corruption when downloading, https://github.com/llvm/llvm-project/releases/download/llvmorg-17.0.2/llvm-project-17.0.2.src.tar.xz and https://github.com/llvm/llvm-project/releases/download/llvmorg-11.1.0/llvm-project-11.1.0.src.tar.xz
> 
> I just tried downloading these files manually and verifying the signature and everything worked correctly. fwiw,
> 
> ```
> $ sha256sum llvm-project-17.0.2.src.tar.xz llvm-project-11.1.0.src.tar.xz
> 351562b14d42fcefcbf00cc1f327680a1062bbbf67a1e1ca6acb64c473b06394  llvm-project-17.0.2.src.tar.xz
> 74d2529159fd118c3eac6f90107b5611bccc6f647fdea104024183e8d5e25831  llvm-project-11.1.0.src.tar.xz
> ```
> 
> You could try using `--no-cache` (`docker build --no-cache ...`) to see if maybe something corrupted got wedged in your docker build cache.

Hey, I had to use `docker system prune` to clear cache and then it worked properly. Thank you very much for help.
