### ISSUE TITLE
account resource details

### ISSUE THREAD

**Issue by dev-dantealighieri** [AntelopeIO/leap#2271]
when i check my account resources, used cpu amount is decreasing and i cant understand why? i bought some resources using powerup model, im spending them. after sometime, my used cpu resource amount is decreasing, quite interesting and can't figure it out, could you please provide more information what might cause this or why this is happening?

thanks, dante

```ts
const result = await client.apiClient.v1.chain.get_account(address);
result.cpu_limit.used // this value is decreasing ???
```

**Comment by nsjames** [comment]
The CPU you use is within a 24-hour window. 
As time goes on, your usage slowly resets back to 0. 
But, as you use CPU, it adds more, so you're constantly using and replenishing CPU.

**Comment by dev-dantealighieri** [comment]
so even i powerup, those fields updated, am i understanding correctly?

**Comment by nsjames** [comment]
Yes, any action you do that either adds or reduces CPU will update those fields.

**Comment by dev-dantealighieri** [comment]
sometimes i see my used used and usedall cpu is 15ms, but max is 5ms, how is that possible, and why is that happening? im using powerup model, is this happening because i rent resources couple of times in a day? even though, this is strange behaviour, why is that happening?

**Comment by dev-dantealighieri** [comment]
should i use available variable returning from node, for my available resources? or should i use max - used expression to check if i have enough cpu resources?

**Comment by dev-dantealighieri** [comment]
@nsjames
