### ISSUE TITLE
IF: Update libtester framework to guarantee deterministic vote processing

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#2289]
Options:
1. Provide a way to wait on votes (which happen on another thread normally).
2. Or, provide a flag for the voting to occur on the main thread for tests.

This should resolve test instability in our Boost IF tests such as https://github.com/AntelopeIO/leap/issues/2267.

**Comment by heifner** [comment]
Example of recent failure that needs this change.
https://github.com/AntelopeIO/leap/actions/runs/8217721857/job/22473866034

**Comment by linh2931** [comment]
Haven't seen this for a while, but it happened today:
https://github.com/AntelopeIO/leap/actions/runs/8459917557/job/23177381955?pr=2349#step:5:4043
