### ISSUE TITLE
reevaluate disablement of strict aliasing warning in chain_plugin

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#229]
https://github.com/AntelopeIO/leap/blob/e401c23f0ee3a52f0f5362ced0bd0a394b10186f/plugins/chain_plugin/chain_plugin.cpp#L1709-L1710

A warning about strict aliasing is probably something that should be tended to, not silenced away.

**Comment by larryk85** [comment]
This does have the potential of being very bad, so I would say this is one the higher priority tasks and we might want to port any changes needed for this fix to 3.1.x.

In addition to the one place that was found, we should search for more such places in the code that is ignoring warnings.  Compiler warnings are usually there for a reason and ignoring them is almost never the valid answer to the problem.

**Comment by ericpassmore** [comment]
find . -type f ! -name '*test*' | xargs egrep "#pragma.*ignored"                        
./libraries/wasm-jit/Source/WAST/ParseNumbers.cpp:	#pragma GCC diagnostic ignored "-Wsign-compare"
./libraries/wasm-jit/Source/WAST/ParseNumbers.cpp:	#pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
./libraries/wasm-jit/Source/WAST/ParseNumbers.cpp:	#pragma GCC diagnostic ignored "-Wsign-compare"
./programs/eosio-launcher/main.cpp:#pragma GCC diagnostic ignored "-Wunused-result"
./programs/cleos/CLI11.hpp:#pragma GCC diagnostic ignored "-Wnarrowing"
