### ISSUE TITLE
Test Failure: ship_streamer_if_test 

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#2323]
https://github.com/AntelopeIO/leap/actions/runs/8330931085/job/22797356430

Fork switch caused some SHiP clients to get incorrect information from SHiP.

A quick look, it appears there is a race on the data in the logs when sending out the data. It can find different blocks by number in the logs according to when the request is sent out.

https://github.com/AntelopeIO/leap/blob/main/plugins/state_history_plugin/include/eosio/state_history_plugin/session.hpp#L527-L527

This failed on an IF run, but it appears to me that this is possible pre-IF.

**Comment by heifner** [comment]
Same issue: https://github.com/AntelopeIO/leap/actions/runs/8360654032/job/22887462153

**Comment by linh2931** [comment]
Was deep into the SHiP support for IBC. Just notice this issue. I stumbled into the same problem when adding more tests for the IBC work. There is a global variable used in the test file. That caused the problem. I have fixed it in my upcoming commit in https://github.com/AntelopeIO/leap/pull/2321.

**Comment by linh2931** [comment]
Updated: The problem I fixed was for fork tests in `plugins/state_history_plugin/tests/session_test.cpp`, not `ship_streamer_if_test`. This requires further digging.
