### ISSUE TITLE
Test: nodeos_forked_chain_lr_test failure

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#2331]
https://github.com/AntelopeIO/leap/actions/runs/8392922204/job/22987149552

may or may not be related to #2243

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/8485923201/job/23251803054

**Comment by greg7mdp** [comment]
Most likely will be fixed by when the ci/cd instances the workflows run on are beefed up.

see https://github.com/AntelopeIO/leap/issues/2369 to track this task.

**Comment by greg7mdp** [comment]
still fails with new beefier instance:
https://github.com/AntelopeIO/leap/actions/runs/8544411611/job/23410864785

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/leap/actions/runs/8548132004/job/23421654687?pr=2362#step:4:4953

**Comment by heifner** [comment]
> https://github.com/AntelopeIO/leap/actions/runs/8548132004/job/23421654687?pr=2362#step:4:4953

Before increase in disk performance.
