### ISSUE TITLE
print resmon shutdown messages at error priority

### ISSUE THREAD

**Issue by cc32d9** [AntelopeIO/leap#235]
These messages are not printed when logging is set to "level": "error"

info  2022-09-26T19:04:58.808 nodeos    file_space_handler.hpp:112    add_file_system      ] /srv/eos01/data/blocks's file system monitored. shutdown_available: 93814404300, capacity: 938144043008, threshold: 90
info  2022-09-26T19:04:58.808 nodeos    file_space_handler.hpp:112    add_file_system      ] /srv/eos01/data/state's file system monitored. shutdown_available: 6979321850, capacity: 69793218560, threshold: 90
warn  2022-09-26T19:04:58.808 resmon    file_space_handler.hpp:62     is_threshold_exceede ] Space usage warning: /srv/eos01/data/blocks's file system exceeded threshold 90%, available: 93741191168, Capacity: 938144043008, shutdown_available: 93814404300                                                                                                                    
warn  2022-09-26T19:04:58.808 resmon    file_space_handler.hpp:117    space_monitor_loop   ] Shutting down

**Comment by stephenpdeos** [comment]
Request to update warning to error instead in these scenarios

**Comment by heifner** [comment]
Cat: Logging
