### ISSUE TITLE
Feature Request: Snapshot reservation for specified block num that is not produced yet.

### ISSUE THREAD

**Issue by teotodev** [AntelopeIO/leap#239]
When anyone wants to create a snapshot for specified block that is not produced yet, needs to calculate block time of the block num and try to create a snapshot at that time. but it doesn't guarantee that it can create a snapshot of the block num for various reasons. So it would be better if there was a feature for snapshot reservation.

**Comment by stephenpdeos** [comment]
Recommended to resolve this via new API call, to be researched in separate spike

**Comment by bhazzard** [comment]
Closing. Resolved in https://github.com/AntelopeIO/leap/pull/759
