### ISSUE TITLE
 unlinkable_block_exception: Unlinkable block

### ISSUE THREAD

**Issue by luoxiandong** [AntelopeIO/leap#2407]
Node sync error occurred:

`unlinkable block 179be40708ca158e28a3fc2262c095be4aa1d53bc7ec78dd6f126e7d703f4b58

error 2024-09-25T14:30:14.350 nodeos    producer_plugin.cpp:707       operator()           ] Exception on block 396092424: 3030001 unlinkable_block_exception: Unlinkable block
unlinkable block 179be4087fefb001b6e69d0e4eb3f0d7da17b3e79a79b3d906002377595ea7ac
    {"id":"179be4087fefb001b6e69d0e4eb3f0d7da17b3e79a79b3d906002377595ea7ac","previous":"179be40708ca158e28a3fc2262c095be4aa1d53bc7ec78dd6f126e7d703f4b58"}
    chain-1  controller.cpp:2223 operator()

info  2024-09-25T14:30:14.350 nodeos    net_plugin.cpp:3786           process_signed_block ] unlinkable_block_exception connection 1: #396092424 7fefb001b6e69d0e...: Unlinkable block (3030001)
unlinkable block 179be4087fefb001b6e69d0e4eb3f0d7da17b3e79a79b3d906002377595ea7ac

info  2024-09-25T14:30:14.351 nodeos    resource_monitor_plugi:117    plugin_shutdown      ] entered shutdown...
info  2024-09-25T14:30:14.351 nodeos    resource_monitor_plugi:119    plugin_shutdown      ] exiting shutdown
info  2024-09-25T14:30:14.352 nodeos    producer_plugin.cpp:1411      plugin_shutdown      ] exit shutdown
info  2024-09-25T14:30:14.355 nodeos    net_plugin.cpp:4382           plugin_shutdown      ] shutdown..
info  2024-09-25T14:30:14.355 nodeos    net_plugin.cpp:4570           close_all            ] close all 32 connections
info  2024-09-25T14:30:14.355 net-0     net_plugin.cpp:1461`

How to solve this problem?

nodeos version:v5.0.2
run command:  nodeos --snapshot /mnt/eosio/snapshot-2024-09-25-10-eos-v6-0396068749.bin  -e -p eosio --data-dir /mnt/eosio/data --config-dir /mnt/eosio/config --enable-account-queries 1 --disable-replay-opts

**Comment by heifner** [comment]
The EOS Mainnet hard fork happened this morning. You need to upgrade to Spring 1.0.1.

**Comment by heifner** [comment]
https://github.com/AntelopeIO/spring/releases/tag/v1.0.1

**Comment by luoxiandong** [comment]
> https://github.com/AntelopeIO/spring/releases/tag/v1.0.1

Thanks,I try it.
