### ISSUE TITLE
How to fast start without previous history?

### ISSUE THREAD

**Issue by 1921Aaron** [AntelopeIO/leap#247]
How to start fast without history, and have historical state data？

**Comment by matthewdarwin** [comment]
If you start from a snapshot, you will get the current state of the blockchain as of the time of the snapshot.  Then going forward the state will be updated as new blocks are produced.

Starting from a snapshot does not have the historical blocks.

If you want historical state at different points in the blockchain you need to use state history plugin. The historical data start from the point of the snapshot and is generated forward.

Please join https://t.me/antelopedevs if you need more information. Gihub is not the place for discussions.
