### ISSUE TITLE
Test failure: api_tests

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#252]
https://github.com/AntelopeIO/leap/actions/runs/3138941007/jobs/5098917313#step:5:4196

Likely due to slow cicd machine. The tolerance for the test is only 2ms, so we should likely just increase the tolerance.

**Comment by spoonincode** [comment]
fwiw the parallel tests run on pretty high end hardware (Zen 2 or Zen 3 CPUs), everything is done in RAM (no disk I/O), and we run `ctest -j $(nproc)` which -- as long as tests don't use more than 1 thread -- doesn't oversubscribe the tests beyond the aspect that we're running on HT CPUs. Obviously there can always be unexpected minor burps and deviations and 2ms is pretty aggressive here.

But we are starting to see more tests that _do_ use more than 1 CPU thread (like test_trx_full) that may cause us to be oversubscribing. Not sure the best strategy long term here is. We could near term just start sprinkling in `PROCESSORS` properties on those tests.
