### ISSUE TITLE
Use github issue instead of #warning directives in api_tests.cpp

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#260]
`api_tests.cpp` has 3 `#warning` directives https://github.com/AntelopeIO/leap/blob/24b23ab3b98b0a616bf1f6baba2cf2fb89de4158/unittests/api_tests.cpp#L1261
`#warning TODO validate that the contract was successfully cached`

Those directives have been there since 06/07/2018. 

Remove the directives and create this issue so it can be triaged

**Comment by heifner** [comment]
Could add a getter for cache size to `wasm_interface`, `controller` already has a `get_wasm_interface()`. The test could then check size of the cache before and after.
