### ISSUE TITLE
CICD: Output xUnit Test Metrics

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#276]
There is a desire to collect metrics & statistics on the number of regression tests run in the CI workflows. This is not easy to collect currently: a `Tests`/`NP Tests`/`LR Tests` job in a workflow will contain any number of tests (currently 11 through 2000+) and the only way to resolve the exact number is to look at the log output (which I wouldn't consider a stable interface).

It appears that a list of test names and those that failed as well as timing information for each test is the minimum reporting requirement.

I propose we output some sort of machine readable (i.e. stable format) file with test statistics as part of the workflow run that external tooling can more easily access and ingest. ctest's `--output-junit` seems like it might be a good start as it provides the needed information.

A couple problems that need to be considered:
* Only Ubuntu 22's ctest is new enough for `--output-junit`. My hunch is it's okay to just collect these statistics on ubuntu22; the tests are the same across distros anyways. But, I was hoping to avoid things like `if(ubuntu22) ctest --output-junit; else ctest` sort of stuff in the workflows as that quickly ends up spaghetti.
* We will end up with dozens of .xml files, and we really need to somehow coalesce these to a single file. That single file doesn't need to be the original XML format: just something in a stable machine readable format. Could be XML, JSON, or whatever. How and when to do this in the workflow though? Do we need a separate "collect and produce test stats" job? Will there be leftover intermediate XML artifacts between jobs if doing that? Since it's only a list of test names & timing maybe we could post process the XML in each pertinent job and just store the information as an output to be coalesced in a file "collect and produce test stats" job.

**Comment by kj4ezj** [comment]
We [used](https://github.com/EOSIO/eos/pull/6963/files#diff-f8476af4f429d1141f864eb5220de02e6caaaa95f980d8e50f5f8f1765a74141R17) the `-T Test` arguments in EOSIO repos to generate xUnit XML artifacts from `ctest`.
```bash
ctest -j "$(nproc)" --output-on-failure -T Test
```
This left a `Test.xml` file in a subfolder of `Testing` in the build dir named with the date and/or time. We pulled this file out and [parsed it](https://github.com/EOSIO/eos/blob/28ec0df6ed3a2317a793a0e6d11f332dadbe34d0/.cicd/metrics/test-metrics.js#L189) using [xml2js](https://www.npmjs.com/package/xml2js) in JavaScript. We packed the data we wanted from this into a JSON blob and attached it to the build as `test-metrics.json`.

I think we can copy/pasta much of that code and follow a similar pattern.

Our implementation should be far simpler. We do not need to interact with the Buildkite API, or to try to diagnose failures, or any of that fanciness. We can leave an xUnit XML file on the disk at the end of each test step, then have a subsequent job step that runs a simple JavaScript program to parse the file directly from the disk, then a third job step can upload it as an artifact. Simple.

**Comment by kj4ezj** [comment]
Note that xUnit is the language-agnostic name for jUnit test output. This confuses some people. It is the exact same syntax and stuff, just the 'j' stands for "Java" so the language-agnostic term for this is xUnit.

**Comment by bhazzard** [comment]
This was PMO driven. @BenjaminGormanPMP to determine priority of this issue going forward.

**Comment by kj4ezj** [comment]
@BenjaminGormanPMP, does your team value test metrics?

I am not sure this ticket should have been closed.
