### ISSUE TITLE
Optimization: Move trx de-dup list to heap memory

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#279]
This could be done either by just using a non-chainbase multi-index container and writing the trxs out at nodeos stop. Or it could be done via a separate chainbase instance using HEAP mode. Either approach would require explicitly adding the trxs to snapshots.

The non-chainbase approach would need a simple undo/commit mechanism similar to chainbase. As no modifications are needed this could be a simplified algorithm.
The chainbase approach would require additional configuration for size.

This is similar to the idea presented here, but this is limited to what is most likely the most active memory region which is the trx de-dup list. https://github.com/eosnetworkfoundation/product/pull/70

Recent WAX snapshot had 182K trxs in the trx de-dup list.

- [x] #298

**Comment by spoonincode** [comment]
chainbase supporting hashed lookups (which it desperately needs for other indices) would likely make this fast enough. That would be the main performance improvement from moving it out of chainbase; not so much chainbase vs heap memory but that you can use hashed lookups outside chainbase.

**Comment by stephenpdeos** [comment]
We've agreed as a team that whatever the solution, there it is desired to keep the consensus state inside of chainsbase.
