### ISSUE TITLE
dfuseeos issue with accepting trxs

### ISSUE THREAD

**Issue by NatPDeveloper** [AntelopeIO/leap#286]
I keep getting this when trying on 3.1.1 or 3.1.0.

This happens only when I set `api-accept-transactions = true`. When it's false it works as expected.

```
info  2022-10-05T03:13:58.065 nodeos    producer_plugin.cpp:504       on_incoming_block    ] Received block 6baa9329efacae6d... #252803482 @ 2022-10-05T03:13:58.000 signed by eosiosg11111 [trxs: 0, lib: 252803151, conf: 0, latency: 65 ms]
reading from console logs (mindreader/mindreader.go:230) {"error": "START_BLOCK: abi decoder: start block for block #252803474 received while already processing block #252803474 (line \"START_BLOCK 252803474\")"}

################################################################
Fatal error in app mindreader-stdin:

START_BLOCK: abi decoder: start block for block #252803474 received while already processing block #252803474 (line "START_BLOCK 252803474")
################################################################
 (launcher/launcher.go:174) 
Application mindreader-stdin shutdown unexpectedly, quitting 
Error: unable to launch: START_BLOCK: abi decoder: start block for block #252803474 received while already processing block #252803474 (line "START_BLOCK 252803474")
dfuse (derr/cli.go:25) {"error": "unable to launch: START_BLOCK: abi decoder: start block for block #252803474 received while already processing block #252803474 (line \"START_BLOCK 252803474\")"}
DMLOG FPRINTF_FAILED failed written=0 remaining=28 1 Broken pipe
DMLOG FPRINTF_FAILURE_TERMINATED
```

Command:

`dfuseeos purge -f; nodeos --disable-replay-opts | dfuseeos start -c ./mindreader.yaml`

Steps to reproduce: https://medium.com/@NatPDeveloper/antelopes-magic-api-firehose-14dec52b5670 using leap 3.1.1 and using `api-accept-transactions = true`.

Regarding priority, this requires us to run a second nodeos instance in production for DSPs to handle transactions with the retry handler enabled.

---

Also I am running the mindreader node locally with zeus with no issues so on a single node local network this works fine.

**Comment by heifner** [comment]
The START_BLOCK is logged on all `start_block()` calls including speculative blocks for trx processing. When `api-accept-transactions = false` & `p2p-accept-transactions=false`, `producer_plugin_impl::start_block()` does not create a speculative block. A speculative block is also not created when running in `irreversible` or `read_only` modes.

**Comment by shaqk** [comment]
Its always been the case that mindreader, or a node with deep mind enabled requires:

read-mode = head
p2p-accept-transactions = false
api-accept-transactions = false

From documentation:
https://docs.dfuse.eosnation.io/eosio/admin-guide/full-deployment/
<img width="783" alt="mindreader" src="https://user-images.githubusercontent.com/10350791/194128707-d6c1173e-738e-488a-8af1-48d8d4d382c6.png">

**Comment by stephenpdeos** [comment]
We want to enforce that when deepmind is enabled that accept-transaction is disabled

p2p-accept-transactions = false
api-accept-transactions = false
