### ISSUE TITLE
Don't apply label and project assignment automation to issues already belonging to a project

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#294]
For issues that are already inside of a project, we have a agreed as a team that we don't want automation of adding to different projects or assigning labels to take place for now. We should make this update to the workflows in leap before copying pattern into other repos.

**Comment by kj4ezj** [comment]
I started looking into this issue but priorities changed and I had to put it down.

What I found so far is that there is no [native filter](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow) for project association of issues, nor is there a `project` field or project information in the [event (webhook)](https://docs.github.com/en/rest/issues/issues#get-an-issue) that kicks off these workflows which is natively available to all keys in a workflow. This means that project association is not [available](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#accessing-and-using-event-properties) to keys like `on` or `if`, so there is no "easy" way to do this.

Ultimately, we will need to add a new step to the workflow which queries the project association for the issue from GitHub, then sets an output. The existing steps would use the `needs` key to create a dependency on this new step, then use an `if` key or similar to conditionally run based on this output value.

GitHub Actions provides a [native ephemeral token](https://docs.github.com/en/actions/security-guides/automatic-token-authentication) that can be [used](https://docs.github.com/en/rest/guides/getting-started-with-the-rest-api#authentication-example-for-github-actions) for the query called `GITHUB_TOKEN`. The step can use either the GitHub CLI (`gh`) tool or [Octokit Request](https://github.com/marketplace/actions/github-api-request) to get project information from GitHub. We could also [use cURL to query GitHub](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#example-2-calling-the-rest-api) but this is nasty looking and error-prone, and offers no advantage over the other two options.

This new step can either be added to the beginning of the [Label New Issue](https://github.com/AntelopeIO/leap/blob/main/.github/workflows/label_new_issues.yaml) workflow in Leap, or the [Issue Project Labeler Workflow](https://github.com/AntelopeIO/issue-project-labeler-workflow) it invokes. The difference being, adding it to Leap would apply only to Leap whereas adding it to the labeler workflow would apply to any repo calling or consuming that workflow.

**Comment by kj4ezj** [comment]
See also: https://github.com/AntelopeIO/issue-project-labeler-workflow/pull/2
