### ISSUE TITLE
Measure replay performance difference between current state and replay optimization disabled

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#297]

**Comment by heifner** [comment]
Setup block log with 2500 TPS for 2500 seconds with 30 sec trx expiration

Runs with skip_recording head block time optimization

* replayed 5594 blocks in 35 seconds, 6.31745682102628248 ms/block
* replayed 5594 blocks in 34 seconds, 6.24119774718398013 ms/block
* replayed 5594 blocks in 35 seconds, 6.27537511174682727 ms/block
* replayed 5594 blocks in 35 seconds, 6.27880922581798639 ms/block

Runs with `skip_recording = false`

* replayed 5594 blocks in 44 seconds, 7.97567173252279638 ms/block
* replayed 5594 blocks in 42 seconds, 7.60711210441623464 ms/block
* replayed 5594 blocks in 42 seconds, 7.56795512247452073 ms/block
* replayed 5594 blocks in 42 seconds, 7.55550885034865072 ms/block

(7.56+7.56+7.61)/3 - (6.24+6.28+6.28)/3 / (7.56+7.56+7.61)/3 = 
(7.58 - 6.27) / 7.58 = .17 = `17%` increase in time

**Comment by heifner** [comment]
Test with EOS mainnet section to see how it compares to this.

**Comment by heifner** [comment]
Runs with skip_recording head block time optimization (db mapped mode) - eos mainnet 161598568 to 161609500.
* replayed 10934 blocks in 420 seconds, 38.42357504801975665 ms/block
* replayed 10934 blocks in 411 seconds, 37.64449108204518524 ms/block
* replayed 10934 blocks in 417 seconds, 38.20364666605689052 ms/block

Runs with skip_recording = false (db mapped mode) - eos mainnet 161598568 to 161609500.
* replayed 10934 blocks in 418 seconds, 38.26522573858959220 ms/block
* replayed 10934 blocks in 417 seconds, 38.19811222903137349 ms/block
* replayed 10934 blocks in 420 seconds, 38.45242568370986902 ms/block
