### ISSUE TITLE
Alternative 3-strike implementation

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#315]
3-strike rule (which is configurable via `subjective-account-max-failures` from the default of 3)
* Applying the 3-strike rule to blocks means that an account (first authorizer) is only allowed 3 failures per speculative or production block, approximately 3 failures every 500ms. 
   * It is not exactly over 500ms as speculative blocks can be shorter or longer than 500ms as new speculative blocks are only started when a BP signed block is received or a block CPU/NET limit is exhausted. Also `cpu-effort-percent` limits block production time.
* Any transaction processed into a speculative or production block after the first 3 failures is immediately failed with a transaction exceeded CPU usage exception without any attempt to execute it.
* The 3-strike rule is enabled by `disable-subjective-billing=false` and configured by `subjective-account-max-failures`. It is not applied to `disable-subjective-account-billing` accounts.

Alternative approach to replace 3-strike rule.
* Track failed execution time per block and fail every transaction from an account (first authorizer) after a configurable `subjective-account-max-failure-time-us` instead of `subjective-account-max-failures`. This allows potentially more failures per account without using more of the block production time. For example a `subjective-account-max-failure-time-us` of `20000` would allow 20 1ms failed transactions but only one 25ms failed transaction. This provides protection of block time while more closely targeting the actual issue of time vs number of failures. This would also be enabled by `disable-subjective-billing=false` and not applied to `disable-subjective-account-billing` accounts.

**Comment by matthewdarwin** [comment]
Sounds better way of doing things.

**Comment by stephenpdeos** [comment]
Is there value in combining both strategies?

**Comment by cmadh** [comment]
In a Chat between WAX Producers the Idea of an additional Strike-Rule came up.

The current 3-strike-rule is applied per Block, resulting in allowing attackers to at least run 3 trx per Account, per Block. On Chains with low account-creation-costs and without power-up this is still a attack-vector.

It seems like an additional strike-rule for a greater timeframe could be a useful addition to the 3-strike-rule. As an example, a 50-strike rule for a 6 hours timeframe could reduce the effect attackers can cause while the 3-strike rule is applied.

**Comment by bhazzard** [comment]
Assigning @stephenpdeos for discussion in release planning. Probably need to back port this change as well.

**Comment by stephenpdeos** [comment]
Closing via https://github.com/AntelopeIO/leap/pull/785
