### ISSUE TITLE
${remaining} blocks remaining message is not clear

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#346]
In leap-3.2-rc1+ (latest build after rc1), I see the following messages in the log:

```
 info  2022-10-18T16:50:05.448 nodeos    log.hpp:442                   open_index           ] ${remaining} blocks remaining, log pos = 139253310075
```

I'm not sure what exactly it is trying to say, and `$remaining` is not filled in.

**Comment by heifner** [comment]
Also needs fixed in `release/3.1`
