### ISSUE TITLE
Remove references to mongodb_plugin in leap

### ISSUE THREAD

**Issue by iamveritas** [AntelopeIO/leap#353]
In http://docs.eosnetwork.com/docs/latest/protocol/network_peer_protocol, there are six references to mongodb_plugin. mongodb_plugin was removed in Leap 3.1. The references in the documents should be removed too.

**Comment by bhazzard** [comment]
@bhazzard to validate task, and then add task to developer relations

**Comment by nsjames** [comment]
Completed here: https://github.com/eosnetworkfoundation/docs/commit/673a8753570e920f450803be7a78cfcc4a3827ed
