### ISSUE TITLE
Read-only vs dry run flag for compute_transaction

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#364]

**Comment by heifner** [comment]
@heifner update #170 with different modes desired for compute_transaction or potentially other api endpoint.

**Comment by heifner** [comment]
**Existing**:

`/v1/chain/compute_transaction`
```
   struct compute_transaction_params {
      fc::variant transaction;
   };
```
- Allows signed or not-signed transactions. Signature verification is performed if provided to time calculation, but failures are ignored.
- All other consensus restrictions are enforced.
- Always returns trace even on failure. (`return_failure_trace` hard-coded to true).

`/v1/chain/send_transaction2`
```
   struct send_transaction2_params {
      bool return_failure_trace = true;
      bool retry_trx = false; ///< request transaction retry on validated transaction
      std::optional<uint16_t> retry_trx_num_blocks{}; ///< if retry_trx, report trace at specified blocks from executed or lib if not specified
      fc::variant transaction;
   };
```

**Proposal**:

read-only transaction public API support, limits enforced, fails on any non-readonly activity e.g. `db_store_i64`
- Future - once read-only transactions supported
- could be run in parallel easily when chainbase in read-only mode
- possible benefit for making a separate api endpoint for easy disablement on api nodes
  - `/v1/chain/read_only_transaction`
  - Hardcoded `return_failure_trace=true`

read-only transaction local API, unlimited transaction
- Future - once read-only transactions supported
- no checktime, no `max_action_return_value_size`, etc
- possible benefit for making a separate api endpoint for easy disablement on api nodes
  - `/v1/chain/unlimited_read_only_transaction`
  - Hardcoded `return_failure_trace=true`
  - Only enabled on api node if `config.ini` option `enable_unlimited_read_only=true`

dry-run for resource calculation or trace retrieval (current `/v1/chain/compute_transaction`)

Question: Benefit to providing an unlimited compute_transaction when read-only available? Benefit to providing unlimited compute_transaction until read-only available?

**Comment by stephenpdeos** [comment]
All of this feedback has been incorporated, so we will close this out.
