### ISSUE TITLE
Configurable CPU multiplier

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#367]
Add option to set a CPU multiplier to compensate for faster or slower than normal block production nodes. Currently billed CPU and consensus value `max_block_cpu_usage` use wall clock time on BP. This can vary depending on BP hardware. It is in the best interest of chains to keep BP performance similar so blocks generated on faster BPs do not overwhelm slower BPs. Allowing BPs to tune their CPU multiplier would allow for a more normalized block creation among BPs. 

Alternatively to a configured multiplier would be to use something like eos mechanics https://www.alohaeos.com/tools/benchmarks to set an expected run time for a particular regular on-chain action. Nodeos could then auto-tune the CPU multiplier to normalize to the expected run time for a particular action. BPs could opt-in to this auto-tune allowing for easier configuration.

**Comment by stephenpdeos** [comment]
Not prioritizing this opportunity for now, discarding.
