### ISSUE TITLE
Why ‘The resource '/' was not found’？

### ISSUE THREAD

**Issue by zhaoxiangjunupi** [AntelopeIO/leap#377]
Why do I still get 404 when I use v3.2.0-rc1?

The command I am requesting is：
curl -i -X POST http://127.0.0.1:8888/v1/chain/get_info

**Comment by heifner** [comment]
Related to #344

**Comment by zhaoxiangjunupi** [comment]
> Related to #344

So what is the reason?

**Comment by heifner** [comment]
> So what is the reason?

No idea. I have not been able to reproduce this.

**Comment by zhaoxiangjunupi** [comment]
> > So what is the reason?
> 
> No idea. I have not been able to reproduce this.

Isn't this what the C++ you wrote prints out?

**Comment by heifner** [comment]
> Isn't this what the C++ you wrote prints out?

Yes, that is from the `http_plugin`.

**Comment by zhaoxiangjunupi** [comment]
> Yes, that is from the `http_plugin`.

So why does it return such an error bro?

**Comment by spoonincode** [comment]
When you see the 404 on get_info, try instead
```
curl -i http://127.0.0.1:8888/v1/node/get_supported_apis
```
and report back the response.

**Comment by zhaoxiangjunupi** [comment]
> When you see the 404 on get_info, try instead
> 
> ```
> curl -i http://127.0.0.1:8888/v1/node/get_supported_apis
> ```
> 
> and report back the response.

HTTP/1.1 200 OK
Content-Type: application/json
Server: Boost.Beast/248
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
Content-Length: 855

{"apis":["/v1/chain/abi_bin_to_json","/v1/chain/abi_json_to_bin","/v1/chain/compute_transaction","/v1/chain/get_abi","/v1/chain/get_account","/v1/chain/get_activated_protocol_features","/v1/chain/get_block","/v1/chain/get_block_header_state","/v1/chain/get_block_info","/v1/chain/get_code","/v1/chain/get_code_hash","/v1/chain/get_consensus_parameters","/v1/chain/get_currency_balance","/v1/chain/get_currency_stats","/v1/chain/get_info","/v1/chain/get_producer_schedule","/v1/chain/get_producers","/v1/chain/get_raw_abi","/v1/chain/get_raw_code_and_abi","/v1/chain/get_required_keys","/v1/chain/get_scheduled_transactions","/v1/chain/get_table_by_scope","/v1/chain/get_table_rows","/v1/chain/get_transaction_id","/v1/chain/push_block","/v1/chain/push_transaction","/v1/chain/push_transactions","/v1/chain/send_transaction","/v1/chain/send_transaction2"]}

**Comment by zhaoxiangjunupi** [comment]
> When you see the 404 on get_info, try instead
> 
> ```
> curl -i http://127.0.0.1:8888/v1/node/get_supported_apis
> ```
> 
> and report back the response.

HTTP/1.1 404 Not Found
Content-Type: application/json
Content-Length: 31
Connection: keep-alive
Server: Boost.Beast/248
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers: Origin, X-Requested-With, Content-Type, Accept
X-Kong-Upstream-Latency: 1
X-Kong-Proxy-Latency: 1
Via: kong/2.7.2

The resource '/' was not found

**Comment by spoonincode** [comment]
What is the kong proxy?

**Comment by stephenpdeos** [comment]
Closing this and related issue, see #344
