### ISSUE TITLE
missing authority of "xxx"

### ISSUE THREAD

**Issue by oliviera9** [AntelopeIO/leap#392]
In contract code, authority is required as:
require_auth(N(xxx));

But I want other accounts (e.g. aaaa, bbbb) also can authorize the transation.
So I updated the xxx account permission as:
xxx:
    active 1:    1 EOS....... 1 aaaa@active 1 bbbb@active

When:
cleos push action mycontract myaction 'action contents' -p aaaa
missing authority error occured.

__Originally posted by @Simbafa in https://github.com/EOSIO/eos/issues/5947__

**Comment by oliviera9** [comment]
I am facing the same issue and I don't understand why multisig should be required in that case.
Why pushing action with -p aaaa@active shouldn't be sufficient?

**Comment by heifner** [comment]
https://github.com/EOSIO/eos/issues/5947#issuecomment-428462780

**Comment by oliviera9** [comment]
> https://github.com/EOSIO/eos/issues/5947#issuecomment-428462780

But why is this? Why `-o aaaa@active` isn't working although it is in `xxx@active` and its weight equals the threshold?

**Comment by stephenpdeos** [comment]
@randomnobody is there an opportunity to explain this in our documentation? Please let me know if you have any questions!

**Comment by nsjames** [comment]
Documented here: https://docs.eosnetwork.com/docs/latest/smart-contracts/getting-started/smart_contract_basics#authorization

Will have its own section in the future
