### ISSUE TITLE
Resource monitoring incorrectly determining size of resource lift

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#394]
The amount of resources being used is being incorrectly calculated and leading to a stop in operations unnecessarily. @larryk85 to populate replication steps.

**Comment by stephenpdeos** [comment]
@larryk85 any details you can log here?

**Comment by larryk85** [comment]
Appears to just be an issue with Docker.

**Comment by heifner** [comment]
Cat: Not-Valid
