### ISSUE TITLE
Reconsider the default value for shutdown threshold for resource monitoring plugin

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#395]
Add an option to set an absolute value limit. This specified the value limit will override the percentage limit set.

**Comment by eosusa** [comment]
Just had a 3.1 SHiP server shut down with 100GB free space because my 1TB drive was 90% full.

I'm voting for absolute value.  The point is not to let it hit absolute 0 and corrupt the logs.  With drives as large as they are these days, % seems like a tough metric to apply to such broad ranges.

**Comment by igorls** [comment]
Absolute value for sure

If it manages to stop gracefully without any corrupt state, then even very small thresholds are fine to use, I would set it to 10gb in most cases.. As said before, if it were 10%, it could mean 4TB in some of our servers, not very helpful ;)

**Comment by matthewdarwin** [comment]
Only challenge is that some file systems (ext4) by default have a reserved % of blocks for 'root'.  If nodoes is running as non-root, then a small amount of bytes threshold might help on a big disk.

**Comment by heifner** [comment]
@stephenpdeos should we just consider this actionable and add an option to set an absolute value limit. If specified the absolute value limit would override the percentage limit.

**Comment by lukasatwax** [comment]
Absolute value plus a friendly messaging in the logs. I am thinking of exchanges running into this and scratching their head as to what happened. "Gracefully shutting down due to disk space having only NNN capacity remaining. Please increase disk space..."
