### ISSUE TITLE
Test failure: nodeos_forked_chain_test

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#430]
https://github.com/AntelopeIO/leap/actions/runs/3370975954/jobs/5592651523

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3517702639/jobs/5895866713

**Comment by linh2931** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3543870709/jobs/5950730642

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3584435465/jobs/6031212137
