### ISSUE TITLE
Addition of a `state-dir` configuration option.

### ISSUE THREAD

**Issue by aaroncox** [AntelopeIO/leap#433]
Currently all data output from nodeos uses the `data-dir`. This includes state, blocks, snapshots, state history, etc. Most of these also have specific parameters you can specify to split them out into their own locations, like `blocks-dir` or `state-history-dir `. 

If your goal is to create an isolated area for state (e.g. loading into tmpfs), you currently need to specify locations for each other data type (blocks, etc) to turn the `data-dir` into a state-exclusive folder. 

This request is for the creation of a `state-dir` parameter, that when specified, allows you to specify the file location of where the `state` folder is placed on the system.

**Comment by stephenpdeos** [comment]
Make sure to update resource monitor as part of the scope of this work.
