### ISSUE TITLE
The http plugin should handle 'Expect: 100-Continue' header correctly

### ISSUE THREAD

**Issue by huangminghuang** [AntelopeIO/leap#451]
An HTTP client could send a header with `'Expect: 100-Continue' when the request body is large and then wait the server to response '100-Continue` response before it starts to send the HTTP request body. However, our http plugin does not handle this at all which causes the http client to wait for a long time before it send the HTTP request body. This [blog post](https://www.bram.us/2020/04/14/about-the-http-expect-100-continue-header/) has more detailed information about this issue.

**Comment by spoonincode** [comment]
Since the current behavior seems a violation of the HTTP 1.1 RFC I'm classifying this as a defect.
