### ISSUE TITLE
Update `http-max-bytes-in-flight-mb` description

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#47]
`http-max-bytes-in-flight-mb`

The comment in the default config is wrong, it returns 429, not 503 when exceeding the limit.

```
# Maximum size in megabytes http_plugin should use for processing http requests. 503 error response when exceeded. (eosio::http_plugin)
```

_Originally posted by @matthewdarwin in https://github.com/AntelopeIO/leap/issues/46#issuecomment-1226700903_

**Comment by heifner** [comment]
`websocketpp::http::status_code::too_many_requests` == `429`. The description is wrong.

**Comment by linh2931** [comment]
This problem was fixed on `main` branch by https://github.com/eosnetworkfoundation/mandel/pull/561.

**Comment by linh2931** [comment]
On` release 3.1` branch, the problem was fixed by https://github.com/AntelopeIO/leap/pull/63.
