### ISSUE TITLE
http_plugin needs cleaner behavior when `accept()` fails with `too_many_files_open`

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#471]
When http_plugin's `accept()` fails with `too_many_files_open` the http threads enter an event storm consuming 100% CPU until the condition clears (i.e. the `accept()` completes or the "overflowing" pending connection is terminated). This behavior needs to be improved so these threads don't run away in this condition. I would recommend using some sort of backoff for retrying the `async_accept()` when it completes with `too_many_files_open`. I would also consider modifying the code to not call `async_accept()` again unless the prior call completed with either no error or `too_many_files_open` (there may be other ways the acceptor can enter a failed state).

Since the main thread appears unaffected, and the event storm is cleared properly when the condition is no longer present, I'm not classifying this a security defect. But due to its ugliness I'm initially classifying it as a defect.

**Comment by heifner** [comment]
Related to #470 A common solution should be explored along with all uses of `accept()` and `async_accept()`.
