### ISSUE TITLE
Unused file (/libfc/src/network/ntp.cpp)

### ISSUE THREAD

**Issue by systemzax** [AntelopeIO/leap#472]
Seems like this file might be an artefact from an older version, and is no longer part of the build system.

**Comment by heifner** [comment]
Thanks, there are a number of files in `libfc` that are not used that could be removed.

**Comment by spoonincode** [comment]
Any files that aren't part of the `CMakeLists.txt` currently as well as any files that are but are unused in leap (such as smaz, for example), can be removed.

**Comment by systemzax** [comment]
Since this one has been marked as a good first issue, I hereby lay claim to it and shall purge the codebase from these useless files.

You can assign it to me and I'll tackle it over the weekend.
