### ISSUE TITLE
http-max-bytes-in-flight-mb = 4096 fails, should generate config error on nodeos startup

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#48]
Followup from: https://github.com/AntelopeIO/leap/issues/46

`http-max-bytes-in-flight-mb = 4096` is too big, but `http-max-bytes-in-flight-mb = 4095` works fine.

If there is a maximum limit, there should be a hard fail.  Realistically setting it this big is a bit crazy.

```
$ cleos get info
error 2022-08-25T13:45:41.077 cleos     main.cpp:4121                 operator()           ] Failed with error: Too many bytes in flight: 897 (429)
```

**Comment by stephenpdeos** [comment]
The team believes there are valid use cases for high values like this, so we'll seek to continue support and get to the root cause of this failure.

**Comment by heifner** [comment]
Note any changes also need to be folded into https://github.com/AntelopeIO/leap/pull/22 if needed.
