### ISSUE TITLE
http_plugin track bytes in flight decrements before http processing complete

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#488]
Currently a RAII object `in_flight` is created to track bytes in flight in the http_plugin. This object is destroyed and it decrements the bytes in flight when the `send_response` is called. However, `send_response` does an `async_write`, so the decrement is likely before the data is actually sent and the http session is complete. 
The corresponding `requests_in_flight` is tracked in the construction/destruction of the `beast_http_session`.
Seems like we could move the tracking of the bytes to the lifetime of the `beast_http_session` OR modify `send_response` so it can be given a lambda to call when the actual `async_write` is complete and destroy the `in_flight` at that time.

**Comment by greg7mdp** [comment]
@heifner `send_response` is defined as a virtual function in [http_plugin/common.hpp](https://github.com/AntelopeIO/leap/blob/2640009e79bb7eca2195e5ff187f19c514edd219/plugins/http_plugin/include/eosio/http_plugin/common.hpp#L57-L64). 

Would it be OK if I defined another virtual function:

`virtual void send_response(std::shared_ptr<in_flight<std::string>> json_body, unsigned int code) = 0;`

which would allow to maintain the lifetime to the `in_flight` object until the lambda callback in [async_write](https://github.com/AntelopeIO/leap/blob/2640009e79bb7eca2195e5ff187f19c514edd219/plugins/http_plugin/include/eosio/http_plugin/beast_http_session.hpp#L370-L376) is destroyed.

**Comment by heifner** [comment]
I don't think `send_response` should be aware of `in_flight`. Instead I would either make `send_response` a template that takes a lambda or a non-template that takes a `std::function`. Then the lambda/`std::function` could be called by the `async_write` completion handler.

**Comment by greg7mdp** [comment]
> I don't think send_response should be aware of in_flight. 

I can certainly do that, but I'm wondering why you don't think `send_response` should be aware of `in_flight`? The in_flight concept is actually part of `abstract_conn` and the template itself is defined a few lines further in the same detail namespace. I think using `in_flight` directly would be less convoluted, and ensure that all calls to `send_response` actually take into account the `in_flight` bytes.

**Comment by heifner** [comment]
> The in_flight concept is actually part of `abstract_conn`

Good point. I'm ok, with your initial approach.
