### ISSUE TITLE
compute_transaction without permissions while ONLY_BILL_FIRST_AUTHORIZER enabled does not work

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#526]
`compute_transaction` RPC allows no permissions. I found out when protocol feature `ONLY_BILL_FIRST_AUTHORIZER` is activated, push a transaction without permissions to `compute_transation` will fail with non-descriptive error (see below).

The sequence leading to the failure is:

1. `transaction_context::init` inserts an empty string of first_authorizer  into `bill_to_accounts`
      ```
if( control.is_builtin_activated(builtin_protocol_feature_t::only_bill_first_authorizer) ) {
         bill_to_accounts.insert( trx.first_authorizer() );
```

2. `transaction_context::max_bandwidth_billed_accounts_can_pay` calls `resource_limits_manager::get_account_net_limit`

3. `resource_limits_manager::get_account_net_limit` uses the empty account name to query resource_usage_object by
    `const auto& usage  = _db.get<resource_usage_object, by_owner>(name);`
and leads to a throw.

Two problems here. The empty account string should not be inserted to `bill_to_accounts`. `get_account_net_limit` could use do a find first and then get. But that will have a small performance hit.

```
./cleos push transaction getage.json --dry-run
{
  "transaction_id": "067271a596834ff3323aa5654542608e637e8fca100e2dae0d16bc66540e1888",
  "processed": {
    "id": "067271a596834ff3323aa5654542608e637e8fca100e2dae0d16bc66540e1888",
    "block_num": 564,
    "block_time": "2022-11-30T20:42:33.500",
    "producer_block_id": null,
    "receipt": null,
    "elapsed": 9758,
    "net_usage": 0,
    "scheduled": false,
    "action_traces": [],
    "account_ram_delta": null,
    "except": {
      "code": 13,
      "name": "N5boost10wrapexceptISt12out_of_rangeEE",
      "message": "unknown key (eosio::chain::name): ",
      "stack": [{
          "context": {
            "level": "warn",
            "file": "exception.cpp",
            "line": 337,
            "method": "from_current_exception",
            "hostname": "",
            "thread_name": "nodeos",
            "timestamp": "2022-11-30T20:42:33.158"
          },
          "format": "rethrow ${what}: ",
          "data": {
            "what": "unknown key (eosio::chain::name): "
          }
        }
      ]
    },
    "error_code": null
  }
}
```

**Comment by stephenpdeos** [comment]
Targeted to backport into 3.1 and 3.2
