### ISSUE TITLE
Test Contracts Source Files

### ISSUE THREAD

**Issue by oschwaldp-oci** [AntelopeIO/leap#54]
There are a handful of test contracts in [unittests/contracts](https://github.com/AntelopeIO/leap/tree/main/unittests/contracts) that are not accompanied by source files for easy indication of versioning or reproduction. Especially with `eos-system-contracts` living outside the AntelopIO organization, would it be helpful to bring the source across for reference?

They should be clearly marked as example contracts for testing and not for production use and should live in the `unittests/*` directory.

They can be pulled from: https://github.com/EOSIO/eos/tree/develop/contracts/contracts

Once example contracts' source files are included, they should be compiled when `EOSIO_COMPILE_TEST_CONTRACTS` is indicated.

**Comment by stephenpdeos** [comment]
Agreed shared goal - all binary WASMs should be compile-able when the EOSIO_COMPILE_TEST_CONTRACTS is true. There should not be any dependency in leap to eos-system-contracts or any future reference contracts.

**Comment by stephenpdeos** [comment]
Continue requirement that building with EOSIO_COMPILE_TEST_CONTRACTS is false does not create a dependency on CDT
