### ISSUE TITLE
Documentation has wrong url for /v1/producer/get_unapplied_transactions

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#547]
It has "producer/producer/" in the URL.

https://docs.eosnetwork.com/leap-plugins/latest/producer.api/

![image](https://user-images.githubusercontent.com/26171839/206157033-3c15a8f2-0f4b-49f6-889c-f9c4aa1f212b.png)

**Comment by ericpassmore** [comment]
quick check on release/3.1 branch shows set_whitelist_blacklist updates were applied. Commits fc9643125c5cdc7a6e9ab8c57f514ce05ae806ac and 37845160864a859d7d0fb65a8041cabf0febc04f 

Need to update release/3.1 producer plugin docs to match those commits.

**Comment by ericpassmore** [comment]
final validation by rebuilding the docs

**Comment by ericpassmore** [comment]
fixed with PR https://github.com/eosnetworkfoundation/docsgen/pull/80
