### ISSUE TITLE
Alternative too many trx in progress limit

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#549]
Currently nodeos measures trx in progress via trx size and limits trxs in progress to 100MB worth of transactions. When this limit is exceeded it begins dropping trxs that come into the node without processing them. This is done so that the node is not overwhelmed and runs out of RAM. You can also set `incoming-transaction-queue-size-mb` to limit the transaction queue size according to trx size.

With this limit in place, BP nodes can still queue up 100s of thousands of transactions.

Alternative limits:
- Limit the number of transactions allowed in the unapplied transaction queue via # instead of trx size.
- Limit the number of transactions allowed in the unapplied transaction queue according to speculative execution time since CPU limit is always the limiting factor and not NET.

**Comment by stephenpdeos** [comment]
Closing for now since the team can't establish a reason that this would be better than current incoming transaction queue size in place.
