### ISSUE TITLE
Improve classification of idle time

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#555]
You can get logging like this from leap 3.2:

```
producer_plugin.cpp:187       report               ] Block trx idle: 267894us out of 465590us, success: 100, 64431us, fail: 51, 93193us, other: 40072us
```

During a period of high load on the WAX chain, the "other" time dominated.  It would be good to understand where this time is going.  Also there is a quite a difference to the unapplied queue at the same time.

![image](https://user-images.githubusercontent.com/26171839/206462733-d2c50f31-d821-49d6-a06c-68ba49976d69.png)

![image](https://user-images.githubusercontent.com/26171839/206462518-308897eb-d377-4e13-bbf7-739662583dcc.png)

Note: The nodes with the high "other time" and the high "unapplied queue" are different.

**Comment by heifner** [comment]
The other is time spent replying to user (API node), or logging transaction success/failure. In your particular case looks like time spent in GELF logging.

**Comment by matthewdarwin** [comment]
Hm, lots of CPU for gelf logs. If it happens again, I'll disable gelf logging and see the result.

**Comment by heifner** [comment]
@matthewdarwin can we close this issue, anything more you need here?

**Comment by matthewdarwin** [comment]
Oops, I thought I closed.
