### ISSUE TITLE
Add command line option to leap-util to indicate if the last shutdown was clean or not

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#564]
Add command line option to nodeos to indicate if the last shutdown was clean or not. This would allow someone to better control logic about perhaps automatically starting from snapshot if the state database was crashed.

**Comment by heifner** [comment]
Is there any particular reason this should be part of `nodeos` instead of `leap-util`?

**Comment by matthewdarwin** [comment]
leap-util is fine too.
