### ISSUE TITLE
nodeos should check disk space immediately on startup instead of first loading all the blockchain data

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#58]
Nodeos stops with following error:

```
 nodeos    file_space_handler.hpp:112    add_file_system      ] /var/lib/nodeos/blocks's file system monitored. shutdown_available: 5259198460, capacity: 52591984640, threshold: 90
resmon    file_space_handler.hpp:62     is_threshold_exceede ] Space usage warning: /var/lib/nodeos/blocks's file system exceeded threshold 90%, available: 5215444992, Capacity: 52591984640, shutdown_available: 5259198460
[etc...]
info  2022-08-26T17:02:35.539 nodeos    main.cpp:181                  main                 ] nodeos successfully exiting
```

Then if you start nodeos again, it goes all through the process of loading all the blockchain state (which takes a while with `database-map-mode = heap`).  Once that it is done, then it again exits.

When you have nodeos running under some sort of thing that just restarts it when it exits (eg systemd), then this just burns CPU and Disk I/O.

Two improvements if not sufficient disk space: 
- hard fail (exit code non-zero)
   - possibly exit 0 on initial shutdown, and then exit non-zero if starting with not sufficient disk space
- exit as quickly as possible on startup (without loading all the blockchain data)

**Comment by stephenpdeos** [comment]
To be re-evaluated after https://github.com/AntelopeIO/leap/issues/97

**Comment by bhazzard** [comment]
Closing this request. I've turned it into a product initiative and will create new issues when and if we prioritize specific tasks.

https://github.com/eosnetworkfoundation/product/issues/154
