### ISSUE TITLE
Reorganize tests for plugins

### ISSUE THREAD

**Issue by arhag** [AntelopeIO/leap#586]
Currently we have different types of tests stored under a `test` folder for some plugins, e.g. chain_plugin and producer_plugin. 

Some of these are proper unit tests of the plugin code in isolation. Those can remain in the folder but we should group them all together in a single executable rather than using different executable for each.

Some of these are bringing in other libraries and/or plugins and really should be considered integration tests (not to be confused with the Python end-to-end tests). These belong somewhere outside of the directories for the plugins. I suggest putting them in a sub-directory within the `tests` folder. It would also seem appropriate to bundle these tests together into one executable rather than linking separate executable for each test suite. (~~Regarding any such tests that use appbase, note that there is currently a limitation that prevents multiple testcases using appbase to exist in the same executable. That limitation should first be fixed; see https://github.com/AntelopeIO/leap/issues/585. - fixed [here](https://github.com/AntelopeIO/leap/pull/636)~~)

**Comment by spoonincode** [comment]
>  It would also seem appropriate to bundle these tests together into one executable rather than linking separate executable for each test suite

fwiw, one benefit to separate executables is that it becomes trivially parallelizeable with `ctest -j`

**Comment by heifner** [comment]
`unittests/plugin_tests.cpp` should be moved from `unittests/` to `tests/` and `unittests/CMakeLists.txt` should not include target include of `${CMAKE_SOURCE_DIR}/plugins/http_plugin/include` or `${CMAKE_SOURCE_DIR}/plugins/chain_interface/include`
