### ISSUE TITLE
Revisit names of eos.doxygen.in and eosio.version.in after 3.1.0 stable

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#6]
`eos.doxygen.in` and `eosio.version.in` are left unchanged during the transition to `Leap` to minimize potential breaking changes. After 3.1.0 stable, we need to investigate any impacts of removing `eos` and `eosio` from `eos.doxygen` and `eosio.version.hpp`. Nathan's team should be consulted about `eos.doxygen`.

**Comment by stephenpdeos** [comment]
Will be captured as part of the next phase of planning around rename work via Adam's WBS

**Comment by bhazzard** [comment]
Closing in the name of keeping the issues clean, given that this hasn't been touched in 8 months.
