### ISSUE TITLE
consider making cleos easier/clearer to set wildcard linkauth

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#613]
cleos' `set action permission` (which performs `linkauth`) states
```
Set paramaters dealing with account permissions
Usage: cleos set action permission [OPTIONS] account code type requirement

Positionals:
  account TEXT REQUIRED  The account to set/delete a permission authority for
  code TEXT REQUIRED     The account that owns the code for the action
  type TEXT REQUIRED     The type of the action
  requirement TEXT REQUIRED
                         [delete] NULL, [set/update] The permission name require for executing the given action
```
And [docs](https://github.com/eosnetworkfoundation/eos-system-contracts/blob/7cec470b17bd53b8c78465d4cbd889dbaf1baffb/contracts/eosio.system/include/eosio.system/native.hpp#L206) also state that "Link authorization action assigns _a specific action_ from a contract to a permission you have created" (emphasis mine).

Antelope also allows a wildcard linkauth as well though. But, despite `cleos get account` showing these wildcard linkauths clearly, there doesn't seem an easy or documented way to convey that to `set action permission`? The only way to convey this wildcard is through an empty `type` string. that is
```
cleos set action permission account contract '' eosio.any
```
then you can see in `cleos get account`
```
permission links:
     eosio.any:
          contract::*
```
(which is actually quite nicely displayed!)

Maybe `type` can accept '*'? But that has shell expansion grief. Maybe just update cleos' help text to state an empty string is a wildcard? Is there precedent somewhere else we can pull from? Passing an empty string like this on the command line is a little wonky.

**Comment by heifner** [comment]
We use `NULL` for the requirement text. Seems like we could use uppercase `ALL` as it has to be a valid `eosio::name` and so `ALL` could be used.

**Comment by spoonincode** [comment]
Yeah, that's not a bad simple change that is similar to existing behavior. To be clear though
https://github.com/AntelopeIO/leap/blob/61b2f98a6fc8e34214847d12cf05c36aa622bb56/programs/cleos/main.cpp#L1066
so "null" is allowed which means you can't linkauth to a permission named "null" today. Likewise for an action named "all" if making this change; so technically breaking, but probably fine.

**Comment by heifner** [comment]
I think we only allow `ALL` and not `all`. Null should have only allowed `NULL` and not `null` in my opinion because of that.
