### ISSUE TITLE
Test failure: nodeos_forked_chain_lr_test

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#631]
https://github.com/AntelopeIO/leap/actions/runs/3883806727/jobs/6625633500

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3884144651/jobs/6626425854

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3903304514/jobs/6667591159

**Comment by heifner** [comment]
https://github.com/AntelopeIO/leap/actions/runs/3914498862/jobs/6691720252

**Comment by spoonincode** [comment]
https://github.com/AntelopeIO/leap/actions/runs/4010821208/jobs/6887803416
