### ISSUE TITLE
clean function for escaping control characters in a string and truncating it

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#641]
When we log an exception from a contract, we want to remove any new lines put in by the contract writer and limit the size of the message. As suggested in the review of eosnetworkfoundation/mandel#733, use of `fc::format_string` is inefficient; a general purpose `clean` method that optionally escapes control characters (specifically newline) and truncates can be created for such a purpose.

This is a transfer of eosnetworkfoundation/mandel#803 originally entered by @linh2931, it is being moved to `leap` for easier visibility.

**Comment by heifner** [comment]
Specific suggestion: https://github.com/eosnetworkfoundation/mandel/pull/733#discussion_r939331290
