### ISSUE TITLE
Creation of v1/chain/get_raw_block chain API endpoint

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#642]
This is a transfer of eosnetworkfoundation/mandel#811 originally entered by @aaroncox, it is being moved to `leap` for easier visibility.

This is a feature request which will eliminate a bottleneck that our history solution (Roborovski) starts running into under high load. We imagine it'll be useful for other advanced applications as well, ones specifically that access raw block data.

We propose the addition of a new API endpoint:

`v2/chain/get_block` or `v1/chain/get_raw_block` (or some named variant of get_block)

This API endpoint will operate nearly identical to the `/v1/chain/get_block` API endpoint, except it will:

- Not decode any of the transactions using their ABIs, and instead just return the raw hex data.
- Run in a non-blocking thread, or be threaded as much as possible. (Note: we assume here the blocking nature of the current `get_block` API call is due to the abi decoding). 
- Maintain a similar API response structure to the `get_block` call.

These changes should offer a much more lightweight solution to retrieving a block and its data vs the current get_block implementation.

---

Side note:

As a more radical approach to solving this problem, we could also suggest making these modifications to the get_block call and deprecating the current behavior of decoding transactions. This makes sense since any historical block retrieved is going to be decoded with the current ABI, and not the ABI that was set historically at that point in time. The current get_block call results can often be invalid because of this. It's best to leave decoding historical blocks to some form of history solution which can reference the appropriate ABI.

However, since this would be a breaking change for many applications, the creation of a new API endpoint as suggested above is likely the safest path. Perhaps in the future the v1/chain/get_block call can be deprecated in favor of this new endpoint.

**Comment by stephenpdeos** [comment]
@heifner to pull together a proposal that we will carry the discussion forward with. @bhazzard will then run with from there.

**Comment by aaroncox** [comment]
Please let me know if there's any clarity required from my original issue.

**Comment by heifner** [comment]
Proposal:

* Deprecate current `/v1/chain/get_block` since ABI decoded block data can be incorrect because the encoded data does not match current on-chain ABI.
* Add `/v1/chain/get_raw_block` which provides `signed_block` as binary data.
  * Same interface as `/v1/chain/get_block` `string block_num_or_id`
  * Returns: `fc::variant` (just  `fc::variant result = signed_block`)
* Add `/v1/chain/get_raw_block_header` which provides `signed_block_header` as binary data.
  * Input: 
   ```
   struct get_raw_block_header_params {
      string block_num_or_id;
      bool include_trx_ids = false; // if true, will also include block_extensions
   }; 
   ```
   * Returns:
   ```
   struct get_raw_block_header_results {
      chain::block_id_type  id;
      fc::variant           signed_block_header;
      std::optional<std::vector<chain::transaction_id_type>> trx_ids;
      std::optional<chain::extensions_type> block_extensions;
   };
   ```

**Comment by matthewdarwin** [comment]
Can this proposed /v1/chain/get_raw_block_header be easily served by a process that has no state? (ie remove this function out of nodeos and put it in another binary).  Is there any other function in /v1/chain/* that requires the blocks.log?  If no, then we can optionally have API endpoints with no blocks.log and have serving get_raw_block as a dedicated tool.

**Comment by stephenpdeos** [comment]
- Agreed to rename get_raw_block_header to get_block_header
- Agreed to return the binary data from get_raw_block

**Comment by heifner** [comment]
- Add cleos support to convert to json (without abi serialization)
- The agreement of binary data is maybe not where we want to land on this.

**Comment by stephenpdeos** [comment]
Return type JSON + hex
