### ISSUE TITLE
Remove HTTPS support from nodeos & keosd

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#643]
As documented in [Leap's deprecation notices](https://github.com/AntelopeIO/leap/wiki/Deprecations-and-Proposed-Deprecations-In-Leap-Software), HTTPS support in nodeos & keosd is to move removed.

This should be fairly simple, notable tasks are to
* Remove HTTPS support from http_plugin
* Remove HTTPS support from http_client_plugin

At the conclusion of this work there should no longer be the need for linking `OpenSSL::SSL` anywhere in Leap.

**Comment by greg7mdp** [comment]
@spoonincode should I remove the https code from `libraries/libfc/src/network/http/` as well? This is what `http_client_plugin` uses.
