### ISSUE TITLE
make it difficult to accidentally perform a large rollback of state history logs

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#659]
Consider a nodeos set up with state history,
```
plugin = eosio::state_history_plugin
trace-history = true
chain-state-history = true
```
and this nodeos has been operational for months -- years -- simply by just stopping nodeos with ^C and then restarting the same as always
```
nodeos --disable-replay-opts
```
Then, say there is a need to remove nodeos' state. That sounds pretty extreme, why would anyone need to do that?! Somehow we've become so complacent in the fact that Leap requires users to _manually_ remove their state files at certain upgrade inflection points, that I don't even see it mentioned in release notes that upgrading to 3.1/3.2 from 2.x requires this step. At this point it is important to restart nodeos via something like
```
nodeos --disable-replay-opts --snapshot recent_snapshot.bin
```
but what if instead.. oops.. nodeos is just restarted like it always is,
```
nodeos --disable-replay-opts
```

:boom: just erased entire state history logs. Months -- years -- instantly gone.

This is really quite hostile behavior. The hope is that automatic database migration (Coming Soon) will help stop the need for manually removing state, but this is so hostile maybe something additional needs to be considered outside of that feature. It would be curious to understand what trace_api does too.

**Comment by heifner** [comment]
Just tried that, wow that is terrible! I think this is the same issue: https://github.com/AntelopeIO/leap/issues/596 or at least related.

**Comment by matthewdarwin** [comment]
Ok, good not just me hallucinating.  nodeos did not auto-delete the history in version 2.0.

**Comment by stephenpdeos** [comment]
Compare snapshot block id to block id of appropriate entry within SHiP logs to determine whether nodeos should automatically truncate the SHiP logs

**Comment by heifner** [comment]
Cat: History
