### ISSUE TITLE
add PKCS#11 keosd wallet provider

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#67]
A PKCS#11 wallet provider would allow keosd to operate with many hardware HSMs. Not just the YubiHSM that was removed via #66, but also Yubikey 5, TPM, Amazon CloudHSM, Nitro Key, ultra low cost generic Javacards and many more (it's a wide industry standard). eosnetworkfoundation/mandel#110 goes in to some details as originally this work was planned in to occur in tandem with #66 but it is being pushed out until later.

**Comment by bhazzard** [comment]
Great idea. Closing until it becomes a priority or we have more resources.
