### ISSUE TITLE
'scripts/pinned_build.sh' throws '301 Moved Permanently' when trying to download 'https://github.com/llvm/llvm-project/releases/download/llvmorg-7.1.0/llvm-7.1.0.src.tar.xz'

### ISSUE THREAD

**Issue by mschoenebeck** [AntelopeIO/leap#680]
When following the [build instructions](https://github.com/llvm/llvm-project/releases/download/llvmorg-7.1.0/llvm-7.1.0.src.tar.xz) executing `pinned_build.sh` throws the error.

**Comment by heifner** [comment]
Seems to work now. Can you try again.

**Comment by mschoenebeck** [comment]
Yes, works again! Thanks.
