### ISSUE TITLE
Add send_transaction2 to the documentation

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#689]
send_transaction2 is not listed here:

https://docs.eosnetwork.com/leap-plugins/latest/chain.api/

**Comment by greg7mdp** [comment]
meanwhile there is some docs in the [3.1 Release Notes](https://github.com/AntelopeIO/leap/releases/tag/v3.1.0).

**Comment by bhazzard** [comment]
Closing as duplicate. This is being tracked in our Developer Relations project here: https://github.com/eosnetworkfoundation/devrel/issues/205
