### ISSUE TITLE
Build Documentation: Include Python Modules

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#711]
Running `ctest -L "nonparallelizable_tests" ` failed because `numpy` was not found. 

Should we include instructions for python modules?

Running `python3 -m pip install -U numpy` resolved issue for me.

**Comment by spoonincode** [comment]
It's in the README, but maybe harder to find than I'd personally like
https://github.com/AntelopeIO/leap/blob/424a0a7fe2565c04bb0d3b49fc604bc984ed112b/README.md?plain=1#L129-L142

**Comment by oschwaldp-oci** [comment]
Looks like we may have missed adding this dependency in the `install_deps.sh` for those using the `pinned_build.sh` script

**Comment by spoonincode** [comment]
Good call, should be added there
