### ISSUE TITLE
Nodeos option to auto-peer based on BP schedule

### ISSUE THREAD

**Issue by bhazzard** [AntelopeIO/leap#716]
**User Story:** As a Block Producer, I want a nodeos option to auto-peer based on the BP schedule, so that I can minimize latency with the node before me in the schedule and avoid late starts.

**Context:** A Block Producer may get a late start in building blocks for a round, due to latency in receiving blocks from the BP that falls prior to them in the BP schedule. When a BP gets a late start, they risk being forced to miss a block or broadcast an empty block.

To optimize latency and minimize late starts, BPs want a reliable way to:
- receive the last block of the previous round as soon as possible
- send their last block to the next Block Producer as soon as possible

So, in addition to the manual peer configuration, there should be a configuration option to automatically peer based on the BP schedule to minimize late starts.

**Requirements:**
- "BP P2P Config" an out-of-band configuration correlating BP accounts to P2P connection info (a list of endpoints)
- Establish a separate bp-schedule-max-peer limit of 2
- Should be an option "BP Schedule Auto Peering" (on/off)
- If BP Schedule Auto Peering is on:
  - Allow connections from nodes in BP P2P Config, up to the bp-schedule-max-peer limit, giving priority based on schedule   - proximity
  - When Block Producer Schedule changes attempt to connect to the next 2 BPs in schedule.
  - When schedule changes, if BP that is no longer in schedule proximity is in your manual peer list, do not disrupt the connection.
  - When schedule changes, if BP becomes in schedule proximity, but is already connected, leave the connection alone... and when they are no longer in proximity, do not disconnect.
  - BP Schedule Auto Peering should not conflict with manual Peer configuration settings
  - BP Schedule Auto Peering should not consider or apply to max peers, unless the BP is in your manual peer configuration

**Comment by bhazzard** [comment]
@heifner and @huangminghuang here is the Antelope issue for the auto-peering feature we discussed last week.

**Comment by greg7mdp** [comment]
If all the block producers use this option, does it mean that when a block producer is added to the schedule, it will receive a volley of connection requests from all the other bp nodes? Is there a guarantee that it will even accept these peering requests (what if it has alreadt reached its own max-peer number)?

**Comment by huangminghuang** [comment]
> If all the block producers use this option, does it mean that when a block producer is added to the schedule, it will receive a volley of connection requests from all the other bp nodes? Is there a guarantee that it will even accept these peering requests (what if it has already reached its own max-peer number)?

No, only the immediate two upstream block producers in the schedule will try to make connections to a producer node in the scheduling list. All the BP peer connections are **not** subject to the max_client_count limit.

**Comment by greg7mdp** [comment]
Thanks @huangminghuang , this makes perfect sense.
