### ISSUE TITLE
Versioned HTTP APIs

### ISSUE THREAD

**Issue by kj4ezj** [AntelopeIO/leap#730]
Leap or `nodeos` HTTP APIs have always been a second-class citizen. We put time and money into them, indicating we believe they meet a customer need and are important. However, we do not create reliability and stability by treating the HTTP API as a _product_ with stakeholders, a release schedule, and versioning.

For example, we recently commissioned work to change the type of compression used for one API call, and another piece of work to change the HTTP status code in the response from another API call. These were changed in-place, potentially breaking the applications of downstream consumers.

Compare this to the strategy of a normal public-facing product API such as the AWS API, Ethereum JSON RPC APIs, or really everyone else. These service providers plan their API interfaces ahead of time, develop them according to this strategy, freeze them, and release them. Changes such as the HTTP response code or data types used to deliver responses or fields of responses are not allowed. They must be planned ahead of time and changes such as this require a new API version that is released.

Eventually, older API versions are deprecated, customers are encouraged to upgrade their clients, and the old version is removed according to a schedule. Some API providers do allow _new_ API "routes" to be added to an existing version because this does not break backwards-compatibility with clients. Most allow bug-fixes that are backwards-compatible. However, changes to existing routes are essentially non-existent.

We should follow a strategy like this to improve reliability, stability, documentation, and enable downstream consumers of our API to plan ahead.

## See Also
- eosnetworkfoundation/engineering [issue 25](https://github.com/eosnetworkfoundation/engineering/issues/25)

**Comment by ericpassmore** [comment]
Closing as duplicate https://github.com/eosnetworkfoundation/engineering/issues/25
