### ISSUE TITLE
Create reference-contracts repo

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#76]
Duplicate eos-system-contracts as vanilla reference-contracts version in Antelope org

**Comment by stephenpdeos** [comment]
Put in leap as a placeholder for now

**Comment by stephenpdeos** [comment]
To be addressed once we wrap the final release of eos system contracts

**Comment by arhag** [comment]
Resolved by https://github.com/AntelopeIO/reference-contracts/pull/1.
