### ISSUE TITLE
transaction_success_tracing and transaction_failure_tracing debug has messages not relevent to tracing

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#768]
When setting` transaction_success_tracing` and `transaction_failure_tracing` to the `debug` log level, we see messages like

```
Failed 3050003 trx, auth: accountname, prev billed: Nus, ran: Nus, id: trx_id
Time since last trx: Nus
Subjective bill for success accountname: N elapsed Nus, time Nus
```

These are not entirely related to transaction tracing and might be better moved to `producer_plugin`.  Further these messages should probably appear at the `trace` log level instead of `debug`.

The reason this matters is that the transaction tracing user interface provided by EOS Nation uses the ` transaction_success_tracing` and `transaction_failure_tracing` log level `debug` to get TRX_TRACE messages.  These are sent to the gelf logger, which takes quite a bit of CPU.  It is impossible to separate the wanted messages from the unwanted messages leading to higher CPU load and network bandwidth.

**Comment by stephenpdeos** [comment]
Proposed that we move these into the producer_plugin
