### ISSUE TITLE
Add time summary logging for read-only trx processing

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#782]
https://github.com/AntelopeIO/leap/pull/776 Added multi-threaded read-only transaction execution.
https://github.com/AntelopeIO/leap/pull/145 Added logging of block trx summary for speculative and BP blocks.
When multi-threaded read-only transaction is enabled it would be nice to provide a log summary report of time spent on the read-only threads executing read-only transactions.

Something like:
```
debug 2022-09-12T18:47:37.241 test_trx_ producer_plugin.cpp:187       report               ] Read-only all threads idle: 131428us out of 150000us, success: 1128, 6622us, fail: 174, 2321us, other: 1054us
```

**Comment by arhag** [comment]
Is this redundant with https://github.com/AntelopeIO/leap/issues/828?

**Comment by heifner** [comment]
> Is this redundant with #828?

Oops. Yep. Forgot I had already created that.
