### ISSUE TITLE
`--logconf` can silently be ignored

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#792]
Currently if `--logconf` is provided to nodeos, it does not verify the file exists. The `logconf` is relative to `config-dir` unless an absolute path is provided.

This means something like: `nodeos --config-dir c --logconf c/logging.json` will attempt to open `c/c/logging.json` silent fail to open the file and use the default log config instead.

Also the help txt for `--logconf` should indicate it is relative to the `config-dir`.

**Comment by bhazzard** [comment]
Should generate an error instead of silently ignoring.
