### ISSUE TITLE
Update OpenAPI docs for Nodeos API changes

### ISSUE THREAD

**Issue by ericpassmore** [AntelopeIO/leap#80]
Update *.swagger.yaml under plugins directory to reflect api changes . Doc change not a functional change.

get_transaction_status
compute_transaction
send_transaction2
get_info

Example
https://github.com/AntelopeIO/leap/blob/main/plugins/chain_api_plugin/chain.swagger.yaml

**Comment by bhazzard** [comment]
Closing as duplicate. Related to Developer Relations task: https://github.com/eosnetworkfoundation/devrel/issues/205
