### ISSUE TITLE
Avoid compiling the same contract on each thread in parallel read-only transaction execution in eos-vm and eos-vm-jit

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#800]
In current implementation of parallel read-only transaction execution, each thread maintains a thread local `wasmif`, which can result in compile the same contract on each thread. The performance can be improved if the compiled contract is shared among the threads.

**Comment by linh2931** [comment]
It is decided to revisit all memory usage issues related to read-only transactions after 4.0 RC.

**Comment by arhag** [comment]
Replaced by https://github.com/AntelopeIO/leap/issues/1158.

**Comment by BenjaminGormanPMP** [comment]
@linh2931 can you provide a brief description (1 or 2 sentences) for discard of issue #800.  This will help for historical reference, lessons learned, and retrospective? Thanks.
