### ISSUE TITLE
Update documentation for parallelize read-only transactions

### ISSUE THREAD

**Issue by stephenpdeos** [AntelopeIO/leap#813]
Update https://github.com/eosnetworkfoundation/product/blob/main/transactions/read-only/parallel.md to reflect the following:

- [x] Update document to reflect changes that were implemented as of https://github.com/AntelopeIO/leap/pull/776 (specifically: window switching rules and diagram, and how some of the producer RPCs are considered not read-only safe).
- [x] Update table of operations analysis to add additional column indicating if the operation is safe to execute in parallel in multiple threads during the read window.

**Comment by arhag** [comment]
Completed by https://github.com/eosnetworkfoundation/product/pull/141.
