### ISSUE TITLE
Unexpectedly slow performance of python based tests and reverse correlation with cpu speed

### ISSUE THREAD

**Issue by 766C6164** [AntelopeIO/leap#816]
Working on tests/nodeos_snapshot_diff_tests.py I noticed following pattern:

System: Debian 11 and Ubuntu 22 (similar results):

PC 1: i9-10980xe -> test takes 170 sec
PC 2: Xeon E5-2673v4 (10 yrs old, way slower per-core performance) -> 150 sec
Overclocked PC#1 to 5 Ghz (confirmed with cpu-z and stellar benchmarks): -> ~200 sec.

It may sound strange, but dependency from CPU speed is opposite to what I would expect. There must be reason behind that that will potentially help to improve performance of python based tests.

**Comment by heifner** [comment]
Could you capture the `TestLogs/*` for each of those runs. Hopefully that would help point out what is going on.

**Comment by 766C6164** [comment]
Looks like it's no longer an issue, I cannot reproduce it anymore. For mentioned above test (nodeos_snapshot_diff_test) it takes roughly same amount of time ~146 sec on average on 10980xe and pretty similar time on 2970WX, so I am closing this now.

**Comment by 766C6164** [comment]
Closing as not reproducible
