### ISSUE TITLE
Update `WalletMgr.py` logging directories

### ISSUE THREAD

**Issue by oschwaldp-oci** [AntelopeIO/leap#840]
Currently in `main`:

```
class WalletMgr(object):
    __walletLogOutFile="var/test_keosd_out.log"
    __walletLogErrFile="var/test_keosd_err.log"
    __walletDataDir="var/test_wallet_0"
 ```

Has been updated to:

```
class WalletMgr(object):
    __walletLogOutFile=f"{Utils.TestLogRoot}/test_keosd_out.log"
    __walletLogErrFile=f"{Utils.TestLogRoot}/test_keosd_err.log"
    __walletDataDir=f"{Utils.TestLogRoot}/test_wallet_0"
```

but should be:

```
class WalletMgr(object):
    __walletLogOutFile=f"{Utils.DataPath}/test_keosd_out.log"
    __walletLogErrFile=f"{Utils.DataPath}/test_keosd_err.log"
    __walletDataDir=f"{Utils.DataPath}/test_wallet_0"
 ```

**Comment by oschwaldp-oci** [comment]
Initial investigation shows that it won't be quite that simple.  Moving that down a directory structure into the proper place, the `DataPath` unearthed the issue that using the DataPath can cause `keosd` to choke on the socket name due to being over the 100 char limit for unix sockets.

**Comment by bhazzard** [comment]
If the obvious solutions don't work, pause work and bring back for further discussion.

**Comment by heifner** [comment]
This is part of the Test Regression proposal work already in progress.
