### ISSUE TITLE
Test Instability - distributed-transactions-test

### ISSUE THREAD

**Issue by kj4ezj** [AntelopeIO/leap#850]
While working on [pull request 849](https://github.com/AntelopeIO/leap/pull/849) for [issue 735](https://github.com/AntelopeIO/leap/issues/735), I found the `distributed-transactions-test` in the NP group [failed](https://github.com/AntelopeIO/leap/actions/runs/4482030632/jobs/7879639481#step:4:457) despite me only making changes to the `README.md` in this particular pull request. This test has passed on at least the last ten [merges to `main`]().

![2023-03-21 14-05-31 - distributed-transactions-test](https://user-images.githubusercontent.com/34947245/226701551-c9c9e11a-c910-4319-8e42-e17049c04f0f.png)

It [passed](https://github.com/AntelopeIO/leap/actions/runs/4482030632/jobs/7880187962) on a retry. This suggests instability.

**Comment by heifner** [comment]
Fixed by https://github.com/AntelopeIO/leap/pull/880
