### ISSUE TITLE
Insufficient input validation on set_whitelist_blacklist, add_greylist_accounts, remove_greylist_accounts

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#86]
There is nothing "ok" about this request:

```
curl -d '{"foo":["bar"]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
{"result":"ok"}
```

Input validation is required to ensure what is being submitted actually changes configuration.

**Comment by stephenpdeos** [comment]
Short-term solution to address this issue requires that at least one of the optionals must be provided.
