### ISSUE TITLE
"params" object is not required for set_whitelist_blacklist, add_greylist_accounts, remove_greylist_accounts

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#87]
https://github.com/AntelopeIO/leap/blob/main/plugins/producer_api_plugin/producer.swagger.yaml#L330

This is correct:

```
curl -d '{"actor_whitelist":[],"actor_blacklist":[],"contract_whitelist":[],"contract_blacklist":[],"action_blacklist":[],"key_blacklist":[]}' http://127.0.0.1:8888/v1/producer/set_whitelist_blacklist
```

There is no "params".

**Comment by matthewdarwin** [comment]
https://developers.eos.io/manuals/eos/v2.0/nodeos/plugins/producer_api_plugin/api-reference/index/?query=set_whitelist_blacklist&page=1#operation/set_whitelist_blacklist

![image](https://user-images.githubusercontent.com/26171839/187928913-b4f47b10-464d-48d6-ae36-204187b01161.png)

**Comment by ericpassmore** [comment]
Getting Started
- editing by hand
- using [Online Editor](https://editor-next.swagger.io/) 
- reference https://swagger.io/specification/
