### ISSUE TITLE
CI/CD: It happens that some tests fails to complete (no failure listed). When that happens, display the list of these in the log.

### ISSUE THREAD

**Issue by greg7mdp** [AntelopeIO/leap#879]
It would be nice to also display the command line that is used to launch the failed tests.

**Comment by heifner** [comment]
I couldn't find a way to make ctest output the command line being executed without `--verbose` which is way too much information.

**Comment by greg7mdp** [comment]
> I couldn't find a way to make ctest output the command line being executed without `--verbose` which is way too much information.

`ctest -N -R <test_name> -V `

**Comment by heifner** [comment]
> `ctest -N -R <test_name> -V `

If you remove the `-N` which means disable actual execution of tests, then you get full --verbose output which is way too much info.

**Comment by greg7mdp** [comment]
> but I'm not sure it's something that should be done.

For example look at [this test failure](https://github.com/AntelopeIO/leap/actions/runs/4511778245/jobs/7944449744?pr=844):

1. how do you know which test failed?
2. how do you know how to run the test locally?

**Comment by spoonincode** [comment]
That's somewhat a different case: it didn't fail, it's just going to never complete. I'm not sure what a good solution to that problem is. Every test should have a `TIMEOUT` defined?

**Comment by greg7mdp** [comment]
OK, my bad, the ask of this issue is to clearly list the tests that failed to complete, instead of forcing the user into a search by elimination.
