### ISSUE TITLE
Allow producer API to run on different port than the standard API port used for user-queries

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#88]
node operators need to run the producer API to make runtime changes to nodeos when dealing with networks under stress.  However, the producer API does not have a dedicated port to listen on.

API node operators are required to do proxy configuration to separate the publicly available APIs from the private APIs.  A dedicated port would be much less error prone.

**Comment by stephenpdeos** [comment]
@matthewdarwin could you elaborate on the use case for this request?

**Comment by stephenpdeos** [comment]
Specifically, what producer API RPCs do you use on nodes that are exposed to the public?

**Comment by matthewdarwin** [comment]
producer api:
- get/set_whitelist_blacklist (when debugging problems)
- get_supported_protocol_features (used on the splash screen of eos.api.eosnation.io)

connection api:
- add/remove (add or remove peers)
- connection (used for internal connection monitoring status)

**Comment by stephenpdeos** [comment]
Question: if we did decide to make a change like this in nodeos, how granular should it be? Private vs Public? An instance of any given connection type and assign the endpoints of a plugin manually?

**Comment by matthewdarwin** [comment]
By plugin?

**Comment by stephenpdeos** [comment]
@stephenpdeos to create initiative backlog item for this

**Comment by stephenpdeos** [comment]
An initiative item with a proposal is ready for review [here](https://github.com/eosnetworkfoundation/product/issues/108). There will be further issue breakdown in leap, but the initiative will belong in product repo

**Comment by stephenpdeos** [comment]
As a result, closing this issue
