### ISSUE TITLE
Test failure: nodeos_run_check_test

### ISSUE THREAD

**Issue by linh2931** [AntelopeIO/leap#886]
https://github.com/AntelopeIO/leap/actions/runs/4504041641/jobs/7928114109#step:4:332

**Comment by heifner** [comment]
This failed because `Node_00` was receiving blocks with huge latency. When it received the block that told it to produce the block had a latency of `latency: 9550 ms`. Since we do not run with `enable-state-production` and the block is over 5 seconds old, it never woke up to produce.

**Comment by heifner** [comment]
@spoonincode just now increased NP test from: 16 "vCPU" to 24c/32GB.
