### ISSUE TITLE
GELF logging even when no gelf listener

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#887]
Currently if GELF logging is configured we are always creating the gelf message, compressing it, and attempting to send it. Our example `logging.json` in `programs/nodeos` has the following configuration:

```
{
      "name": "net",
      "type": "gelf",
      "args": {
        "endpoint": "10.10.10.10:12201",
        "host": "host_name",
        "_network": "jungle"
      },
      "enabled": true
    }
```

Anyone that uses that without removing the entry will waste a lot of cpu time creating and compressing GELF messages.

**Comment by jgiszczak** [comment]
Detecting the presence of a listener is not possible to do reliably.  The logging protocol itself does not specify any form of ACK.  In the absence of such a message, there is no way to tell if a message will be or can be received at a UDP endpoint on another host.  GELF receivers aren't guaranteed to open a corresponding TCP socket to their UDP listen socket as an indication that they're online, so the presence of a listener can't reliably be probed that way either.

The only supported way to avoid the CPU burden of GELF logging is to not configure a GELF appender in `logging.json`.
