### ISSUE TITLE
Test Failure: nodeos_snapshot_forked_test

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#906]
https://github.com/AntelopeIO/leap/actions/runs/4532943866/jobs/7985236645

**Comment by 766C6164** [comment]
Looks like Node.py's waitForLibToAdvance with default 30 sec not sufficient to robust enough on slow workers.

**Comment by 766C6164** [comment]
Also I believe trx_finality_status_forked_test.py needs to be adjusted as well since it uses same cluster config/timeout so it has similar odds to fail

**Comment by heifner** [comment]
Agree. 
```
info  2023-03-27T14:26:31.568 nodeos    producer_plugin.cpp:699       on_incoming_block    ] Received block 293b27e787428104... #216 @ 2023-03-27T14:25:54.000 signed by defproducerb [trxs: 0, lib: 179, confirmed: 24, net: 0, cpu: 100, elapsed: 64, time: 281, latency: 37568 ms]
```
The python test gave up at `14:26:29`, if it had waited a couple more seconds it would have seen the lib move.
