### ISSUE TITLE
Backport enhanced debug logging from main to 3.1.1

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#93]
Recently on WAX blockchain there nodes were running with very high CPU utilization and generating blocks with low numbers of transactions.

Additional logging has already been added to the main branch that would have been helpful in debugging the situation. Rather than waiting for the next release, this request is to backport that loggging into the next patch release of 3.1.x

It a new feature, but the logging is off by default. The benefits of this larger change might outweigh the risks.

Nation team is starting to test the new logging features by running the main branch on non-producing, non-critical nodes, but we have not fully tested the changes yet.

**Comment by heifner** [comment]
The new logging in `main` branch is incorporated via a refactor of `producer_plugin` to remove duplicate code and make it easier to enhance in the future. This refactor would not be appropriate for a patch release. If this debug logging is backported it should be done by duplicating the log statements in the existing duplicated code of the `producer_plugin`. So this would not be a clean cherry-pick back from `main`, but rather a bit of re-implementation mainly via copy-paste from the `main` branch.

**Comment by stephenpdeos** [comment]
This will be part of 3.2 within the next month or so, so discarding for now
