### ISSUE TITLE
Add basic documentation on logging.json 

### ISSUE THREAD

**Issue by matthewdarwin** [AntelopeIO/leap#94]
Add basic documentation on logging.json
- purpose
- how to configure
- HUP to nodeos reloads
- list of different config blocks and when you might want to use them
- GELF logging

Recently, `transaction_trace_failure: debug` was used for debugging WAX issues.

**Comment by heifner** [comment]
Some docs here: https://developers.eos.io/manuals/eos/v2.2/nodeos/logging/native_logging/index
And changes to GELF logging documented in GELF section of: https://github.com/AntelopeIO/leap/releases/tag/v3.1.0

**Comment by matthewdarwin** [comment]
Ah, not bad.

**Comment by heifner** [comment]
https://docs.eosnetwork.com/leap/3.2-rc1/nodeos/logging/

There is no info ^^ on using SIGHUP to reload the `logging.json` file.

Also the list of loggers needs updated.
* Remove `transaction_tracing `
* Add `transaction_success_tracing`
* Add `transaction_trace_success` & `transaction_trace_failure`
* Add `transaction`
* Add `state_history`
