### ISSUE TITLE
investigate "this assumes only one [wasm] can possibly run at a time" comment in context of ROtrx

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#956]
A `wasm_runtime_interface` exposes
https://github.com/AntelopeIO/leap/blob/d382d71c7e1b9ec9e8e14fae5d0b80e1f2dfee81/libraries/chain/include/eosio/chain/webassembly/runtime_interface.hpp#L26-L27
This is pretty interesting as it suggests this function only has defined behavior if a single wasm is executing, which of course is not the case now with ROtrx.

This is called via `eosio_exit` host function.
https://github.com/AntelopeIO/leap/blob/d382d71c7e1b9ec9e8e14fae5d0b80e1f2dfee81/libraries/chain/webassembly/cf_system.cpp#L48-L50
via
https://github.com/AntelopeIO/leap/blob/d382d71c7e1b9ec9e8e14fae5d0b80e1f2dfee81/libraries/chain/wasm_interface.cpp#L115-L117

So it can absolutely be called via multiple ROtrx at a time.

But... Most likely this is a relic of the way WAVM and/or wabt runtimes were integrated. OC stubs this out as a do-nothing, and EOS VM looks like it throws an exception that likely has proper semantics. I think this "singleton" `immediately_exit_currently_running_module()` should be completely removed.

**Comment by linh2931** [comment]
Thanks Matt @spoonincode. Should we just take it out?

**Comment by spoonincode** [comment]
We'll still need to, I guess, throw an exception for EOS VM in `eosio_exit` impl. Otherwise yeah I _think_ it can all be ripped out.
