### ISSUE TITLE
Test memory usage of many threads with ro trxs

### ISSUE THREAD

**Issue by heifner** [AntelopeIO/leap#966]

**Comment by heifner** [comment]
Summary:
Approximate memory use per read-only thread is ~2.5 GB. 
On my machine with 100GB ram I could safely run 33 threads.

We could limit the number of read-only threads according to available free memory or update help text with this recommendation. 

Exceeding available RAM/swap on a machine will cause `nodeos` to crash with a dirty-db.

**Comment by greg7mdp** [comment]
> Exceeding available RAM/swap on a machine will cause nodeos to crash with a dirty-db.

Why? I was thinking that if we crash while executing readonly transactions, the db should not be modified, so we should be able to exit cleanly.

**Comment by heifner** [comment]
> > Exceeding available RAM/swap on a machine will cause nodeos to crash with a dirty-db.
> 
> Why? I was thinking that if we crash while executing readonly transactions, the db should not be modified, so we should be able to exit cleanly.

nodeos does not handle bad alloc very well. You end up just getting a terminate. 
You have not shutdown cleanly, so we have not cleared the dirty bit in chainbase. Also no idea if the OS has flushed the shared memory to disk.

**Comment by greg7mdp** [comment]
> nodeos does not handle bad alloc very well. You end up just getting a terminate.nodeos has not shutdown cleanly, so it has not cleared the dirty bit in chainbase. Also no idea if the OS has flushed the shared memory to disk.

We should probably try to improve on that. It might be worth reserving a few megabytes of memory at application startup, that we can free if we get a `bad_alloc` exception to give us some breathing room in order to clean up properly before shutdown.

**Comment by heifner** [comment]
Decided to add a conservative limit for now. See #978
