### ISSUE TITLE
remove/refactor global `WASM::check_limits` which is accessed from multiple threads

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#969]
There is a global here,
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/wasm-jit/Source/WASM/WASMSerialization.cpp#L178-L183
which is accessed throughout WAVM's parsing code.

This global `bool` is toggled via `scoped_skip_checks`
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/wasm-jit/Include/WASM/WASM.h#L12-L18

`scoped_skip_checks` is notably used within `wasm_interface_impl`, part of  `wasm_interface`
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/include/eosio/chain/wasm_interface_private.hpp#L183

There are multiple `wasm_interface`s, one per a thread. This may result in unsafe access to this variable causing some sort of undesirable behavior.

I suspect we can remove the entire parsing inside of `wasm_interface_impl::get_instantiated_module()` because I don't believe there is a need to `parse_initial_memory()` any more.

The other use of  `scoped_skip_checks`,
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/webassembly/runtimes/eos-vm-oc/compile_trampoline.cpp#L27
I'm not as sure about. I think we may need it there. But, _worst case_, we can leave the `scoped_skip_checks` in `compile_trampoline` because it's _process local_. It'd be nice to remove `check_limits` entirely though.

**Comment by linh2931** [comment]
`instantiate_module` in eos-vm and eos-vm-oc do not use the `initial_memory` parameter. I gave it a try removing it plus removing `WASM::scoped_skip_checks`. Tests passed.

**Comment by linh2931** [comment]
Because of the global `WASM::scoped_skip_checks`, it seems this should be fixed before rc3.
