### ISSUE TITLE
parallel ROtrx dispatched to baseline runtime while OC enabled may not be thread safe

### ISSUE THREAD

**Issue by spoonincode** [AntelopeIO/leap#970]
In the case of EOS VM OC being enabled, only a single `wasm_interface wasmif` is created in controller
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/controller.cpp#L2690-L2700
and remember that this is the only `wasm_interface` that is accessible
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/controller.cpp#L2714-L2723
Recall how execution for a wasm is kicked off
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/wasm_interface.cpp#L89-L113
Assuming `my->eosvmoc` is populated (that is, OC tier up enable), which it will be when `--eos-vm-oc-enable`, then nominally it tries to get the `code_descriptor`
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/wasm_interface.cpp#L96
And then executes that entry
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/wasm_interface.cpp#L107
Keep in mind that `exec` is `thread_local`
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/include/eosio/chain/wasm_interface_private.hpp#L66
and `cc` is expected to be safe to access from multiple threads as long as `is_write_window() == false`. So this is correctly thread safe nominally.

However, if obtaining the `code_descriptor` fails -- such as when OC is still compiling the contract and/or has blacklisted a compiled contract due to subjective failure -- then the code will fall back to the baseline runtime
https://github.com/AntelopeIO/leap/blob/d7eb6d7f9fa150a7e2f0e648325ce58ec35b79f9/libraries/chain/wasm_interface.cpp#L112
This appears to then enter code that is _not_ thread safe.

**Comment by linh2931** [comment]
Thanks @spoonincode for the detailed analysis. Would it be OK for now ROtrxs we add an assert when `cd` is `NULL` to fail the transaction, instead of moving along into non-thread-safe code?

**Comment by linh2931** [comment]
Talked with Matt. We will use different assertion types to determine retry in next window or permanent failure like when a contract is blacklisted by OC.
