### ISSUE TITLE
3110006 plugin_config_exception: Incorrect plugin configuration

### ISSUE THREAD

**Issue by hungzinza** [AntelopeIO/leap#971]
I run a nodeos v2.0.13 and sync from the snapshot.
But It stuck at a block of 21/09/2022. I tried to use binary leap-v3.1.0 to run continuously.
I receive this error:
![Screenshot from 2023-04-05 18-07-13](https://user-images.githubusercontent.com/96384818/230063131-2065ef30-7d5a-4138-9d4d-54c9af99b688.png)

I use snapshot from this site: https://snapshots-main.eossweden.org/#2.0
I follow this guide: https://eosnetwork.com/blog/leap-3-1-upgrade-guide/#3-preparing-your-node-for-the-upgrade

- Do you know about this error ?
- If I want run a nodeos from zero, should I use snapshot from v2.0 or from v3.1 ?

I'm Waiting for the support. Thanks

This is my config:

```
http-server-address = 0.0.0.0:8888
p2p-listen-endpoint = 0.0.0.0:9876
p2p-server-address = 0.0.0.0:9876
chain-state-db-size-mb = 32768
contracts-console = false
http-validate-host = false
verbose-http-errors = true  
abi-serializer-max-time-ms = 2000  
chain-threads = 8
http-threads = 6    
access-control-allow-origin = *
access-control-allow-headers = Origin, X-Requested-With, Content-Type, Accept
last-block-time-offset-us = -300000
chain-state-db-guard-size-mb = 128 
p2p-max-nodes-per-host = 150
allowed-connection = any
max-clients = 150
connection-cleanup-period = 30

sync-fetch-span = 2000
enable-stale-production = false
pause-on-startup = false
max-transaction-time = 30
max-irreversible-block-age = -1
txn-reference-block-lag = 0

plugin = eosio::trace_api_plugin
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin

p2p-peer-address = eos.seed.eosnation.io:9876
p2p-peer-address = peer1.eosphere.io:9876
p2p-peer-address = peer2.eosphere.io:9876
p2p-peer-address = p2p.genereos.io:9876
```

**Comment by heifner** [comment]
Looks like you skipped this step:
```
Remove the state file. To delete the files in this directory, you can use:
rm <nodeos data directory>/state/*
```

**Comment by hungzinza** [comment]
@heifner I deleted folder state `rm -rf state`, it has file shared_memory.bin
There are any reason for this error log ?
After remove state folder, should I run with --snapshot and use snapshot version leap3.1 ?

**Comment by hungzinza** [comment]
I use this command to run: 
`--data-dir=/data/eos/data --config-dir=/data/eos/config --snapshot=/data/eos/data/snapshots/snapshot.bin`

If I run nodeos at version v2.0.13, and snapshot before 21/09/2022, everything works fine.
But If I run at version v3.1.0 or v3.2.3 and snapshot the latest (04/04/2023), it has the error.

**Comment by heifner** [comment]
The error: `Snapshot can only be used to initialize an empty database.` means there is a `shared_memory.bin` in your `state` directory.  According to your command line that would be `/data/eos/data/state`. The following should work:

```
rm -rf /data/eos/data/state
nodeos --data-dir=/data/eos/data --config-dir=/data/eos/config --snapshot=/data/eos/data/snapshots/snapshot.bin
```
Using v3.1.0 or v3.2.3 and a recent snapshot.
If not please verify the error is the same error or possibly a different error.

**Comment by hungzinza** [comment]
Thanks for your response, please keep following my issue
I used your recommended way, but that error still exists.
Should I use new node or new VM, and run nodeos v3.1.0 and sync by recent snapshot?

**Comment by hungzinza** [comment]
How about list plugin should use ? 
I used 
```
plugin = eosio::trace_api_plugin
plugin = eosio::chain_plugin
plugin = eosio::chain_api_plugin
```
is It correct ?

**Comment by heifner** [comment]
Are you sure it is the exact same error you show in your image?

**Comment by hungzinza** [comment]
@heifner I'm sure, I tried following you're recommended and it still shows that error.

**Comment by heifner** [comment]
Can you post the error again with command line used.

**Comment by hungzinza** [comment]
I run it in docker,
This is entrypoint:

```
#!/bin/bash

DIR="/data/eos/data/blocks"
COMMAND="/usr/bin/nodeos"

exec "rm -rf /data/eos/data/state"

echo "'$DIR' exists"
exec "$COMMAND"  "$@"

```

and this is dockerfile

```
FROM ubuntu:20.04

RUN apt update -y && \
    apt upgrade -y && \
    apt install wget -y && \
    wget https://github.com/AntelopeIO/leap/releases/download/v3.2.3/leap_3.2.3-ubuntu20.04_amd64.deb && \
    apt install ./leap_3.2.3-ubuntu20.04_amd64.deb -y && \
    mkdir -p /data/eos && mkdir -p /data/eos/config && mkdir -p /data/eos/data && chmod 777 -R /data

COPY entry-point.sh /data/eos/entry_point.sh
RUN chmod +x /data/eos/entry_point.sh

WORKDIR /data/eos

ENTRYPOINT ["/data/eos/entry_point.sh"]
```

**Comment by hungzinza** [comment]
Oh wait, maybe my entrypoint has error syntax, I will fix it and run again now.

**Comment by hungzinza** [comment]
Error still exist :'(
I use this command:

`/usr/bin/nodeos --data-dir=/data/eos/data --config-dir=/data/eos/config --snapshot=/data/eos/data/snapshots/snapshot.bin`

nodeos v3.2.3
snapshot leap3.1
![Screenshot from 2023-04-07 09-52-54](https://user-images.githubusercontent.com/96384818/230531769-54b9e086-368e-42f0-a9fa-85ecbeb077a2.png)

**Comment by heifner** [comment]
@huangminghuang can you provide an example docker setup that works for this.

**Comment by hungzinza** [comment]
@heifner oh, I try again and now there are new error:

![Screenshot from 2023-04-07 11-02-03](https://user-images.githubusercontent.com/96384818/230538569-655f913e-9922-4f95-b86f-063589d18deb.png)

**Comment by hungzinza** [comment]
I add more param: `--delete-all-blocks --disable-replay-opts`
and it's work.
Is It has full data if use this param?

**Comment by hungzinza** [comment]
I know that I should download blocks data if I want to get block info
But I know only one link provides block data: https://snapshots.eosamsterdam.net/. This data is too old (2021-01-27).
Are there any links else?

**Comment by heifner** [comment]
> I add more param: `--delete-all-blocks --disable-replay-opts` and it's work. Is It has full data if use this param?

Yes, that fine to use those options when loading a snapshot.

**Comment by heifner** [comment]
> I know that I should download blocks data if I want to get block info But I know only one link provides block data: https://snapshots.eosamsterdam.net/. This data is too old (2021-01-27). Are there any links else?

https://snapshots.eosnation.io/

**Comment by hungzinza** [comment]
This link has only snapshot. If should deploy a archive node, maybe it will take a long time to sync all block data.

**Comment by heifner** [comment]
It will only sync from where the snapshot starts. Do you have need of old blocks?

**Comment by hungzinza** [comment]
Oh no, now I only need sync from snapshot. 
Thank you so much @heifner 
My issue was resolved. 
I will close this issue
